### ISSUE TITLE
Adding Ad's to the Client

### ISSUE THREAD

**Issue by Qasimmodo** [CigarProject/Cigar#101]
How would I go about doing this using Adsense?

**Comment by J4awesome** [comment]
You could go to google and see if they have an adsense program and paste the html into the server but first see if they have an html code.

**Comment by Qasimmodo** [comment]
Where do I paste it, and how do I create panels.

**Comment by J4awesome** [comment]
Sorry if this is late but I have a server that runs ads also but I use a site called yllix.com which takes about 10 minutes to get approved.I run this on my site and gets me a lot of money depending on the number of visitors on your site.Also to made panels go into the game.hbs file and where ever you want paste this

<div class="What ever you want" style="height:400px; position:absolute; top:3px;left:-345px;width:325px; background-color:#FFFFFF; border-radius:10px;padding:15px 15px 5px 15px;"> 

You can also edit the height and the position of the panel.I would use google chrome inspect element while click on a page.If you need anyone more help just message me

**Comment by J4awesome** [comment]
<div class="What ever you want" style="height:400px; position:absolute; top:3px;left:-345px;width:325px; background-color:#FFFFFF; border-radius:10px;padding:15px 15px 5px 15px;">
