### ISSUE TITLE
playerSpeed does not work and is not in gameserver.ini

### ISSUE THREAD

**Issue by xXAndrew28Xx** [CigarProject/Cigar#102]
I can't change the speed of a cell with "change playerSpeed 400" or adding a line line in gameserver.ini with it. This functionality is in Ogar. Where did it go and is there anything I can change to add speed? 
Even changing this wont work:
this.moveEngineTicks = 10; // Amount of times to loop the movement function
    this.moveEngineSpeed = 1000;

**Comment by Lukkez** [comment]
Cigar is outdated
