### ISSUE TITLE
Adding Regions

### ISSUE THREAD

**Issue by Qasimmodo** [CigarProject/Cigar#104]
When I use [Add] [IP] [PORT] [Region Name] It doesn't work.

E.g: Add 127.0.0.1 1501 AwesomeFFA

I get the response invalid Region name. Anyone know why or a fix?

**Comment by Qasimmodo** [comment]
Bump @J4awesome I know you know how to do this since you have it working on your site. Could you help me out here? agarplay.us My email is: Qasimroot@gmail.com

**Comment by J4awesome** [comment]
Add so they are two ways to do it when you start the server type in select 0.This will select you into the master server and then you can do the command.Or in the masterserver.ini there is a line of code like this to add what you want just add this into your code
regions = {"Region Name":1, "AwsomeFFA":1,}
You can change the region name part to what you want to name your region.You can also add more.When you start the server it will create a gameserver2.ini file.That's where you can edit the ip and port and everything about the server.

**Comment by MastaCoder** [comment]
^^
