### ISSUE TITLE
Wrong leaderboard in tournament mode/HG

### ISSUE THREAD

**Issue by s0me-1** [CigarProject/Cigar#106]
It's displaying an FFA leaderboard instead, I first thought it was coming from the packet but everything seems ok...

**Comment by MastaCoder** [comment]
The board command doesn't seem to even work at all.

**Comment by Elitis** [comment]
fix it?

**Comment by MastaCoder** [comment]
Not yet as the board command is completely wrong.

**Comment by s0me-1** [comment]
Sorry for late answer, I fixed it myselfs somme days ago, but I don't have the code anymore,
I just remember that something was wrong with the leaderboard packet ID

**Comment by MastaCoder** [comment]
@s0me-1 Thanks for the help, I'll check out the packets sometime this week.

**Comment by MastaCoder** [comment]
Fixed in the latest update :)
