### ISSUE TITLE
Memory and Ram

### ISSUE THREAD

**Issue by J4awesome** [CigarProject/Cigar#108]
I would like to know how I would edit the amount of memory that is going to my server because I'm only using about 10 mb ram to the server and it's not laggy but I would like to add more ram because more and more players are joining everyday.
Link to my server:Agarplay.us

**Comment by J4awesome** [comment]
@m-byte 
Could you help me with this?

**Comment by J4awesome** [comment]
@matrixreal 
@vram4 
@m-byte 
hi,
Could anyone of you guys help me with this?

Thanks

**Comment by m-byte** [comment]
I'm not sure, what exactly you are trying to accomplish.
Are you sure the server isn't getting as much memory as it requests? If so, it would be pointless to force the operating system to allocate more ram to the server.

**Comment by J4awesome** [comment]
Even though  it would be pointless to force the operating system to allocate more ram to the server it would still like to know how to do it.

**Comment by m-byte** [comment]
Although I am certain, that this is not only pointless but also stupid (the reason for this is described at the end), here is a "solution" for your "problem"...

The "best" way to increase ram usage would probably be a memory leak. If you are 100% sure you want Cigar to use more ram, read through https://strongloop.com/strongblog/node-js-performance-tip-of-the-week-memory-leak-diagnosis/ and do the opposite of what they recommend. This will cause Cigar to continually use more and more memory.

Please be aware, that this is 100% counterproductive as the additional memory will just be wasted. Neither Cigar, nor any other process on your computer will be able to use it.

**Comment by matrixreal** [comment]
@m-byte 
any update please ?
