### ISSUE TITLE
how do i get this thing to work?

### ISSUE THREAD

**Issue by Agarian** [CigarProject/Cigar#111]
you cannot even connect to the server!

*WebSocket connection to 'ws://127.0.0.1:88/' failed: Connection closed before receiving a handshake response*

this thing doesn't work. i wasted my time. i suggest no one else make the same mistake.

**Comment by m-byte** [comment]
To answer your main question: there is a file called README.md. Reading it should clarify a lot of things.
And regarding the rest of your post: it seems like error code 1D10t. Currently, there is no fix for this error.

**Comment by Agarian** [comment]
oh
