### ISSUE TITLE
What's with the web client?

### ISSUE THREAD

**Issue by nikolaaa4** [CigarProject/Cigar#112]
I see that the index has been removed, so how do i start the client if someone can explain? On localhost to play.

**Comment by iamashay** [comment]
You can use other clients to connect to your server.
Like : 
http://www.mediafire.com/download/zf0yik27z16ryzn/agarweb-client-byChrisF.rar

**Comment by MastaCoder** [comment]
Run the master_server. You can use http://github.com/MastaCoder/Cigar-Plus if it's easier.

**Comment by MastaCoder** [comment]
Added to Cigar!
