### ISSUE TITLE
Hide Chat Option

### ISSUE THREAD

**Issue by J4awesome** [CigarProject/Cigar#116]
How would I hide the chat using the button like set dark mode?

**Comment by J4awesome** [comment]
@m-byte 
@vram4 
Could you help me with this

**Comment by muxahuk** [comment]
Here u go. Should work: https://github.com/muxahuk/Cigar/commit/db35596f4e5229496590f6015459bf5248cdfdb8

**Comment by MastaCoder** [comment]
Thanks @muxahuk Added to Cigar!
