### ISSUE TITLE
People glitch back to around 0 mass when they get to 25k mass too fast!

### ISSUE THREAD

**Issue by xXAndrew28Xx** [CigarProject/Cigar#119]
I have this speedy server where all the food mass is 5. If people eat people too fast and get too big they glitch back to 0 mass and can not play anymore until they refresh or die. How can I fix this? All I edited was the speed in Cell.js

**Comment by Logan7432** [comment]
Did you change the gamemode file in the server files? check to make sure the max mass isnt set too 25k. Im running my own server and i dont get the issue so it might be something you changed that you shouldn't have. Also have you tried reverting the speed back to normal to make sure changing speed isnt the issue?

**Comment by xXAndrew28Xx** [comment]
I fixed it, I copied the addmass function from Ogar and the newvirusedcell function. Everything works now. I will reply again with more details

**Comment by Logan7432** [comment]
Ok, Have Fun!
