### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by elitajmx** [CigarProject/Cigar#123]
THIS ERROR HOW DO I FIX THANKS :)
![wmplayer 2016-02-09 16-02-28-37](https://cloud.githubusercontent.com/assets/16438675/12919929/a11828c6-cf46-11e5-866f-e1435dede647.jpg)

**Comment by MastaCoder** [comment]
http://github.com/MastaCoder/Cigar-Plus

Run install_dependencies.bat

**Comment by MastaCoder** [comment]
Added to Cigar!
