### ISSUE TITLE
Does not work Tournament, Hunger Games

### ISSUE THREAD

**Issue by Red071** [CigarProject/Cigar#126]
Hey. In Tournament mode and Hunger Geyms player stands on the ground and can not move.
In Zombie mode when all become zombies, the game is not updated and it is necessary to update the browser.
The Teams mode, there is a timer before the end of the game.
Tell me how to fix it? Thank you in advance!

**Comment by MastaCoder** [comment]
Can you test this on Cigar-Plus? If you have the issue just make it an issue there.

http://github.com/MastaCoder/Cigar-Plus

**Comment by Red071** [comment]
> Can you test this on Cigar-Plus? If you have the issue just make it an issue there.
> 
> http://github.com/MastaCoder/Cigar-Plus

error 404

**Comment by MastaCoder** [comment]
Cigar and Cigar-Plus were merged. Just download the latest version of Cigar and test.
