### ISSUE TITLE
UPDATE ?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#128]
Hi,
can anyone update this project to the latest ogar please ?
thanks

**Comment by MastaCoder** [comment]
I am working on a better version of Cigar under my repo of Cigar-Plus. I'll be updating it throughout this week.

**Comment by matrixreal** [comment]
@MastaCoder 
thank you ... i'm waiting for ... there is also small bug and i did a fix ... will send you soon

**Comment by MastaCoder** [comment]
Post it on the issues of Cigar-Plus and I can check it out :)

http://github.com/MastaCoder/Cigar-Plus

**Comment by m-byte** [comment]
@MastaCoder I just invited you to the CigarProject group. I think it would be better to a) replace Cigar by "merging" your code into it, or b) to move your repository to CigarProject. For option b), I would recommend to replace the README with text redirecting to the new repo.

**Comment by MastaCoder** [comment]
Haha thank you for giving me this option @m-byte! I think option A is the best, I'll just grab my changes and pull them over to Cigar! I didn't remove anything so far, so it should be fine with the changes I have made :)

**Comment by MastaCoder** [comment]
@m-byte Are you okay if I merged Cigar-Plus with Cigar now? I have also made some changes such as chat spam protection and chat length block :)

**Comment by m-byte** [comment]
Sure, go ahead. Sadly, I don't have much time for things like this project, so I definitely appreciate someone else taking it over for the time being.

**Comment by MastaCoder** [comment]
Alright @m-byte. I'll do my best :+1:
