### ISSUE TITLE
Custom skins [Repost]

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#129]
See agarly.com, agarabi.com the skins are not on name
Like if i put on my server [YT] Lukkez i will get the skin but agarly you can select on settings and don't need to put [YT] on name

**Comment by MastaCoder** [comment]
I'm not really sure how I could do this. Would be great if someone could help!

**Comment by matrixreal** [comment]
this is client issue and need a big work

**Comment by MastaCoder** [comment]
It's not really an issue but an enhancement.

**Comment by MastaCoder** [comment]
I am not going to support this update for the time being as we do have some more important things to work on. As for this, you can simply increase the name characters on the server and in the client while having it hide anything in [].
