### ISSUE TITLE
Package.jSon

### ISSUE THREAD

**Issue by tombalfoort** [CigarProject/Cigar#130]
Hello, 

I just entered the first 3 steps for a new Cigar installation. 
But after step 3 I want to start 'start_masterserver.sh'. Just get this message

start_masterserver.sh node: not found
[batch] server shutdown, wating 15 seconds before a restart.

Tom.

--
Hallo, 
Ik krijg na stap 3 een foutmelding. Ik heb alle stappen gevolgd. Maar ook als ik handmatig npm install en daarna npm start uitvoer. Dan krijg ik een foutmelding. 
Ook de start_masterserver.sh werkt niet. Dan blijf ik de melding
start_masterserver.sh: 6: start_masterserver.sh: node: not found.

Wat kan ik hieraan doen ? 

Tom.

**Comment by MastaCoder** [comment]
Can you type in node -v on your server and tell me what it responds?

**Comment by tombalfoort** [comment]
When I writhe '$ node -v' I see nothing. 
Just a empty line.

**Comment by MastaCoder** [comment]
That means node isn't installed correctly on your server. Are you sure you installed node properly? Try reinstalling it.

**Comment by tombalfoort** [comment]
I have. When I want to install it I get the messege there isn't a better version. 
![node-error](https://cloud.githubusercontent.com/assets/11942420/13353005/877ec50c-dc91-11e5-9b45-12db3961703d.png)

**Comment by MastaCoder** [comment]
That's weird.Try installing JXCore. 

Install it with curl http://jxcore.com/xil.sh | bash and edit the scripts so that instead of node and npm, it will run a command called JX.

So like in start_gameserver.sh it would be jx server/index.js.

**Comment by m-byte** [comment]
It's a bit simpler than that ;)
@tombalfoort you are using debian. If you ran `apt-cache search node`, you would find the line `p   node                                                                                       - Amateur Packet Radio Node program (transitional package)`. Obviously, that is not what you need. Instead, install `nodejs` and also use `nodejs` instead of `node`

**Comment by m-byte** [comment]
Also, you'll have to adjust line 6 of `start_masterserver.sh` to read `nodejs server/index.js --master`

**Comment by m-byte** [comment]
My newest commit includes a fix for this issue.

**Comment by MastaCoder** [comment]
@m-byte Thanks :+1:
