### ISSUE TITLE
Disable web server

### ISSUE THREAD

**Issue by tylerspencer237** [CigarProject/Cigar#132]
I am running start_gameserver.sh but I am using an external client so I want to disable the client that is on port 88.

**Comment by MastaCoder** [comment]
start_gameserver.ini disables the client no?

**Comment by tylerspencer237** [comment]
My server is on Debian 8.3 I'm running start_gameserver.sh and I can confirm the client still runs.

**Comment by MastaCoder** [comment]
I'll check this out.

**Comment by MastaCoder** [comment]
I can confirm this is an issue. Just played around with it on my server and looks like it does launch..

**Comment by MastaCoder** [comment]
Cigar is now client only.
