### ISSUE TITLE
keep runing the server with jxcore?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#134]
hi,
i'm using pm2 to keep runing the server on my vps
i would like to know if there is a way to keep runing the server using jxcore ?
thank you

**Comment by MastaCoder** [comment]
What do you mean? Like using the scripts?

**Comment by matrixreal** [comment]
if you are using a vps
using node index.js or npm start will lunch the server but it will shut down when you close the ssh terminal so i use pm2 start index.js to keep it runing even if i close the shh terminal
now i need to know what we can you to keep runing the server with jxcore that's all

**Comment by matrixreal** [comment]
any news ?
in order to test jxcore and node?

**Comment by MastaCoder** [comment]
Nope :(

**Comment by MastaCoder** [comment]
I just read your comment and I know what you are saying. To run the server even after the terminal box closes, download and install screen. (Find the one for your distro online.) To launch a screen, CD into the directory and type in screen -mdS [name] sh start_masterserver.sh (replace name with anything.)

Now to view the screen, type in screen -r [name] and the screen will pop up.

**Comment by matrixreal** [comment]
and then replace node by jx right ?

**Comment by MastaCoder** [comment]
Yeah.
