### ISSUE TITLE
Stop gameserver

### ISSUE THREAD

**Issue by tombalfoort** [CigarProject/Cigar#135]
Maybe stupid. 
But I use a command line only and the only way for me to stop the server is to reboot it hard. Is there not a stop command? I tried 'stop, exit, shutdown'. 

Very happy the other issue was fixt so quickly ! Thanks. 

Tom.

**Comment by tombalfoort** [comment]
I'm sorry. If you start the server with the sh start_gameserver.sh and you press CTRL+C the server wil stop.

**Comment by MastaCoder** [comment]
Glad you solved it :) I'll be adding a exit command soon!
