### ISSUE TITLE
Multipel fields on 1 server

### ISSUE THREAD

**Issue by tombalfoort** [CigarProject/Cigar#136]
Hi, 

I want to add more 'fields' on a server. So I found in the masterserver.ini information about adding more 'regions'. I did that. But the master server than won't start. See screenshot. 

Greet Tom.

![schermafbeelding 2016-02-26 om 20 39 37](https://cloud.githubusercontent.com/assets/11942420/13363331/184f9aca-dcc9-11e5-80aa-0afa7e41517f.png)

![schermafbeelding 2016-02-26 om 20 41 58](https://cloud.githubusercontent.com/assets/11942420/13363463/d7edaaa2-dcc9-11e5-8483-c811a4daf81f.png)

**Comment by MastaCoder** [comment]
I think you solved this. But just in case someone else had the same question, you have to change the stats port in each of the gameserver.ini's.

**Comment by tombalfoort** [comment]
Thanks for your reply MastaCoder. I did change them. I need to read a bit more. I changed it to 1600, 1601 and 1602.
