### ISSUE TITLE
Use ogar servers here

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#143]
I know a version of ogar who make a option to put on custom clients, how i make? it's Ogar-Unlimited

**Comment by MastaCoder** [comment]
This feature already is in Cigar..

**Comment by Lukkez** [comment]
But my server will be updated, with smooth split, cigar don't have smooth split

**Comment by MastaCoder** [comment]
Smooth split is a major issue. If you leave your server on for more than 1 hour with smooth split, lag will be your worst nightmare. Also the masterTick on Cigar is too low, so the collision is very much messed up when your cells collide.
