### ISSUE TITLE
Use other ip servers

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#144]
How to put like 2 servers of friends on one website like Frinend server 1 "xxx.xxx.xxx:xxxx" and friend server 2 "xxx.xxx.xxx:xxxx" on servers at client

**Comment by MastaCoder** [comment]
Open server/web/view/game.hbs and find the line ```<option selected disabled value=''> -- Select a Region --</option>```. Under it add the lines like this: ```<option value='YourFriendsIP'>Name of the server</option>```

**Comment by Lukkez** [comment]
I can do with 127.0.0.1 too? if yea, i'm happy, MUCH

**Comment by MastaCoder** [comment]
You can't host locally. Otherwise you are the only one that can connect to it...

**Comment by Niall7459** [comment]
DOES THIS REALLY WORK??

SERIOUSLY THIS IS THE BEST AGAR CLONE OUT THERE!!!!!!!!!!!
ITS LIKE THE ONLY ONE WITH A WORKING CLIENT ITS AMAXING!!!
