### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by mogokcp** [CigarProject/Cigar#145]
title says all. it bind to "localhost", first time was working all on my vps but now it doesnt start, please help. Thanks

**Comment by mogokcp** [comment]
PS > it start but does not "bind", i get the error of the title yet.

**Comment by Lukkez** [comment]
My server ppl can't connect to server but can to Client WHY? u can solve this?

**Comment by mogokcp** [comment]
Nope, i don't know and i dont know how to disable that annoying client xD.

**Comment by Lukkez** [comment]
:/ i just wanted to play with friends

**Comment by mogokcp** [comment]
same :/

**Comment by Lukkez** [comment]
I maked for my clan, like 50 ppl are asking at this moment

**Comment by mogokcp** [comment]
Ok, fixed. 

The problem was i tried to protect my gameservers from anti ddos [if anyone know please tell me <3]

It blocked via iptables that. I did this:

`iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 1501 -j ACCEPT`

then my server was working @ port 1501
:smile: 

hope it helps u Lukkez

**Comment by Lukkez** [comment]
I not use ddos protection :/ not helped

**Comment by mogokcp** [comment]
Are you running it on a linux vps? Add me on skype: skyleter

**Comment by MastaCoder** [comment]
Did you change the server IP in masterserver.ini?

**Comment by mogokcp** [comment]
I'm using 127.0.0.1 and it works on my vps. I don't know if Lukezz is running on vps or not

**Comment by MastaCoder** [comment]
For @Lukkez I'm talking about if he is using the client. If the client is still on 127.0.0.1 nobody can join through the client.

**Comment by mogokcp** [comment]
Is there a way to disable that client?

I think iptables drop will do the job

**Comment by MastaCoder** [comment]
The client gets disabled on Windows but not on Linux I don't know why..

**Comment by Lukkez** [comment]
@MastaCoder People can join the client with my external ip, i port forwaded 1500, 1501, 1502, 88, i don't use vps, i use windows

**Comment by MastaCoder** [comment]
Can you copy and paste your masterserver.ini here.

**Comment by Lukkez** [comment]
But can't join at the servers
Can do all, upload skins, see gallery but only don't connect to server/chat

**Comment by MastaCoder** [comment]
"Can you copy and paste your masterserver.ini here."

**Comment by Lukkez** [comment]
serverIP = 127.0.0.1
serverPort = 88
gameserverPort = 1500
updateTime = 60
regions = {"Cigar": 1}

// To add more regions, add a comma and paste the following thing, like the following:
// regions = {"FFA": 1, "Teams": 1}
It's default

**Comment by MastaCoder** [comment]
```serverIP = 127.0.0.1```

Change that to your external IP.

**Comment by Lukkez** [comment]
Ok, i will invite friends now

**Comment by Lukkez** [comment]
Problem solved, but i can't join lol

**Comment by mogokcp** [comment]
try joining via ur ipv4 adress instead of localhost/127.0.0.1

idk if will help but..

**Comment by Lukkez** [comment]
Don't work :/

**Comment by mogokcp** [comment]
Im not sure if i will play on my server, im doing all that things for fun, btw, i can give you the ip and you can set it any config you want, idk, btw, can you add me @ skype?

**Comment by Lukkez** [comment]
Ok, snake.agar

**Comment by Lukkez** [comment]
But i will accept later, i can't now

**Comment by mogokcp** [comment]
Sent. Lets talk about this when you can, good luck

**Comment by Lukkez** [comment]
![image](https://cloud.githubusercontent.com/assets/15003706/13443246/1520359e-dfdf-11e5-85aa-c525550d96d4.png)
When i try to connect by agar.io LOL

**Comment by mogokcp** [comment]
is that the badass butterflies tag? lol dat discord m8 xd

**Comment by Lukkez** [comment]
xD
Yep, i'm co at this clan lol

**Comment by mogokcp** [comment]
Nice, send me discord.gg plz xd

**Comment by Lukkez** [comment]
https://discord.gg/0nZOvpw372DtMXiU

**Comment by Lukkez** [comment]
I think i have a fix =P
I will go to game.hbs and put a line to connect by 127.0.0.1

**Comment by MastaCoder** [comment]
You can't join Cigar through Agar.io. Launch the masterserver and type in your IP in the URL box following by :88. So like 127.0.0.1:88 (But don't do 127.0.0.1, use your own external IP.)

**Comment by mogokcp** [comment]
Yes, thats true. You can't, please read README.md
hope u already read it ;p

**Comment by Lukkez** [comment]
I think you need to enable the connect command at console, will make easier to connect

**Comment by Lukkez** [comment]
like: connect("ws://127.0.0.1:1501")
You know yea?

**Comment by Lukkez** [comment]
![image](https://cloud.githubusercontent.com/assets/15003706/13443475/f8494e14-dfdf-11e5-9271-a18206a7004c.png)
When i try to connect by external ip :/

**Comment by Lukkez** [comment]
Sorry, i'm Brazillian if u don't understand this language

**Comment by mogokcp** [comment]
mmm, i need to repeat x'D, i can run a server for you. But my vps is only 500mb so users -30 and config not too "high values" xD

**Comment by Lukkez** [comment]
I only use border 14k =P

**Comment by Lukkez** [comment]
And max food 5k

**Comment by mogokcp** [comment]
Sent u pm on discord

**Comment by Lukkez** [comment]
Skyleter?

**Comment by mogokcp** [comment]
Yes
