### ISSUE TITLE
Messed up physics when over 5000 mass

### ISSUE THREAD

**Issue by MastaCoder** [CigarProject/Cigar#147]
I was wondering if anyone here can help me with the physics branch that can be found at: https://github.com/CigarProject/Cigar/tree/Physics

Basically when you are over 5000 mass, the cell splits are extremely weird and slow. I think this has something to do with the tick times or collisions, however I am not so sure.

@vram4 any assistance?

**Comment by mayed505** [comment]
@MastaCoder i know this is an old thread but i dont see the messed up physics for me and even im with 10K mass its looks fine

**Comment by MastaCoder** [comment]
@mayed505 It's part of the physics branch where I'm testing the physics. People want the smooth splitting from Ogar into Cigar, but the issue is when I try to add it the 5000+ mass issue occurs.

Download from the physics branch to see: https://github.com/CigarProject/Cigar/tree/Physics
