### ISSUE TITLE
Smooth Split Support?

### ISSUE THREAD

**Issue by tveloper** [CigarProject/Cigar#148]
Hi,

In Ogar, they recently added Smooth Split (tricksplit), but will Cigar support it, too?

Thanks.

**Comment by MastaCoder** [comment]
I have added it to the Physics branch. However, one problem is in place. The collision reset time is pretty much messed up. I am looking into fixing this as we speak, but I don't know if I can get the collision reset to work.

https://gyazo.com/a0b56fa5b748638feec9c107ffda7f54

**Comment by MastaCoder** [comment]
Adding this soon, well trying.
