### ISSUE TITLE
Looking for developers!

### ISSUE THREAD

**Issue by MastaCoder** [CigarProject/Cigar#149]
If you are good at Node.js and can send out at least one proper pull request to Cigar, I will see if you can become part of the CigarProject team :+1: 

This post will close in a week.

**Comment by mayed505** [comment]
@MastaCoder im interested :D

**Comment by MastaCoder** [comment]
@mayed505 Can you make a couple pull requests so I can see your work? :3

**Comment by mayed505** [comment]
@MastaCoder well i made 1 actually :D
