### ISSUE TITLE
In some modes bugs

### ISSUE THREAD

**Issue by Red071** [CigarProject/Cigar#150]
In zombie mode it stops updating the time. At the tournament the player can't move. When you run multiple modes simultaneously gameserver1 gameserver2 gameserver3 - error

**Comment by MastaCoder** [comment]
So does this only happen if you are running multiple servers?

**Comment by Red071** [comment]
Yes. I'm trying to run multiple modes (servers). In the old version I could run multiple modes

**Comment by MastaCoder** [comment]
I just tested Zombie and Tournament.

Zombie Mode: It works, but then there is no countdown like in the newer updates. I think we have to update the modes which is the issue, not really much of a big.

Tournament: As for this, I don't know what you mean. I am running multiple right now on my test server and everything seems to work find.
