### ISSUE TITLE
3 Questions

### ISSUE THREAD

**Issue by Sentaq** [CigarProject/Cigar#156]
**Question 1:**
How can I add amount online players in-game behind gamemodes / region names? Example: http://prnt.sc/abzcfx

**Question 2:**
How can I put a limit of messages per second?

**Question 3:**
Is there any way to add a chatfilter?
<br>Hopefully you can help me!

**Comment by MastaCoder** [comment]
1. In the server files have it write to the client using /this.config.maxPlayers.
2. It's an option in the gameserver.ini.
3. Chat filter is not yet implemented.

**Comment by Sentaq** [comment]
Could you explain how to write to the client using /this.config.maxPlayers in the server files? I appreciate it.

**Comment by mayed505** [comment]
@MastaCoder what do u mean by /this.config.maxplayers? explain for me i want that feature too!

**Comment by MastaCoder** [comment]
I will have to look into the code myself to figure out where to put it. I'll try this feature later this week.

**Comment by mayed505** [comment]
@Sentaq the 1. is already exists https://gyazo.com/b94746453401bbf6ea7a3073e4150979

**Comment by MastaCoder** [comment]
I checked the code to see if I can add the number of players online, but through the app.js shows no sign of the players showing..

**Comment by MastaCoder** [comment]
Update: Just found it in the masterserver.js under a function.

**Comment by MastaCoder** [comment]
To add it, go to line 121 @ masterserver.js. There will be a line called: 

return a;

Simply add a plus after and type anything you want as a string so it will return onto all servers.

**Comment by Sentaq** [comment]
@MastaCoder, what do you mean with ''type anything you want as a string''? Could you give me a example? Sorry, I don't know that much about programming :x

**Comment by MastaCoder** [comment]
So like ```return a + "/500";```

@Sentaq

**Comment by mayed505** [comment]
can someone send a screenshot that it works i dont wanna risk it and break something :P

**Comment by Sentaq** [comment]
@MastaCoder, it doesn't work. Maybe I have to put in somewhere amount online players? Because I don't have that. And where?
