### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#159]
/home/ubuntu/workspace/server/index.js:94
    in_.question("<" + selected.server.realmID + ">", function(str) {
------------------------------- ^

TypeError: Cannot read property 'realmID' of undefined
    at prompt ( as _onTimeout ] (/home/ubuntu/workspace/server/index.js:94:39)
    at Timer.listOnTimeout (timers.js:89:15)
This error...

**Comment by MastaCoder** [comment]
Are you using an edited version of Cigar?

**Comment by Lukkez** [comment]
Nope

**Comment by MastaCoder** [comment]
What do you do to get the error?

**Comment by Lukkez** [comment]
I only start index.js and masterserver.js, i use ubuntu 'vps'

**Comment by MastaCoder** [comment]
So node server/index.js?

**Comment by Lukkez** [comment]
Yes

**Comment by MastaCoder** [comment]
Okay this is weird, I don't get this error..

**Comment by mayed505** [comment]
@Lukkez that error happened to me and the why i fixed it is by deleting /server/index.js
and replacing it with a new one from github... i dont know if it would work but i also reinstalled node.js too so hope it helps u :D

**Comment by Lukkez** [comment]
Now i know, it's because the server don't have port forwadeds, i need to put pot 80, 8080 because this vps use proxy ips and make a custom ip to redirect

**Comment by MastaCoder** [comment]
I think following what @mayed505 said would work.
