### ISSUE TITLE
Skin Doesnt load or bug?

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#161]
im using cigar but i can see the skin loads in main menu but when i click play i dont see it
i tried chaning gamemodes and no luck....
all skins are like "abc" not "ABC"
https://gyazo.com/7ec38d66bfae6b47f147121ac60150b1

**Comment by MastaCoder** [comment]
I'll check out if it's just a bug on Cigar's side or you have implemented something that doesn't work.

**Comment by mayed505** [comment]
@MastaCoder thanks :D

**Comment by mayed505** [comment]
@MastaCoder Bump.

**Comment by mayed505** [comment]
@MastaCoder can u help me code the skins for 3rab.co thats my website for my friends to play on. i just need you to help me do it i might pay u

**Comment by MastaCoder** [comment]
I can't do private projects because I don't have much time. I'll check if the skin issue is a Cigar project **only**.

**Comment by mayed505** [comment]
@MastaCoder any updates if it was my problem with the code can u contact me through skype and try to fix it for me?

**Comment by MastaCoder** [comment]
Yeah I can't do that. I have quite a lot of projects on my hands and honestly helping people right now, sadly is my last priority.

**Comment by mayed505** [comment]
@MastaCoder its alright ill try to use the default one and start from scratch :(

**Comment by mayed505** [comment]
@MastaCoder well i tried alot to fix the skins but i couldnt! i would have a great day if u would help me plz...

**Comment by mayed505** [comment]
Thanks to @m-byte for helping me with this issue a big thumbs up for him!

**Comment by Lukkez** [comment]
How u made this client, i can have?, send the code, for these skins

**Comment by mayed505** [comment]
@Lukkez we will make a wiki later so u would understand. :D

**Comment by Lukkez** [comment]
Ok thanks :D 
P.S: Your arabic?

**Comment by mayed505** [comment]
@Lukkez Yes :D
