### ISSUE TITLE
Can someone explain "Web " Folder is used for?

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#162]
titale says it all.
i just want to understand why theres html and js files in there?
is it so i can upload it to a website?
im trying to fix my skin problem heres the website
[3rab.co](url)
if someone can help me fix the skin problem ill do anything for him.

**Comment by m-byte** [comment]
The web folder is where the actual web server is located. Cigar consists of two parts: the web server and the game server. The web server is used to get the client to any web browser. The client, in turn connects to the game server.

**Comment by mayed505** [comment]
@m-byte so i have to place web folder into my website?

**Comment by mayed505** [comment]
@m-byte i already have all the files combined into one with index.html but i have a problem with cigar that my skins wont work for some reason....

**Comment by Sentaq** [comment]
@mayed505, I have exactly the same problem with custom skins.

**Comment by mayed505** [comment]
@Sentaq Oh i thought i was the only one... did u try to fix it?

**Comment by Sentaq** [comment]
@mayed505, yes, but, didn't work.

**Comment by mayed505** [comment]
@Sentaq well i need someone to fix it! im jelous other people uses cigar and get custom skins.....
like 3rb.io   and agar.gr.sa   they are all arabic but i tried to copy their code and everything worked but except for the skins hmm i tihnk they are using old version of cigar?

**Comment by m-byte** [comment]
@mayed505 I am not sure I understand how your server is set up. Cigar is meant to be set up in a way that everything is handled by node.js. This means that there should not be a file named index.html. Instead, any request from the client is handled by web/app.js, which in turn sends most requests through web/routes/index.js to web/views/game.hbs.

**Comment by mayed505** [comment]
@m-byte do u have skype? the index.html is combined from web folder.

**Comment by m-byte** [comment]
No, I don't have skype. Hangouts would be possible

**Comment by mayed505** [comment]
@m-byte if u go to 3rab.co (my website at the moment) u could see i combined the web folder into an index.html

**Comment by m-byte** [comment]
Yes, but I am still not sure, why you did that. It makes sense, though, that this might make the skin system more complicated.

**Comment by mayed505** [comment]
@m-byte but theres 2 website did that too which i copied their code from them (3rb.io and agar.gr.sa)
they have the same code both of them .
i made index.html so i could have edit them into 1 file but i finished everything on the website but i just need the skin done.

**Comment by mayed505** [comment]
@m-byte okay so if i changed cigar back to default how can i run the web folder then? in 3rab.co
i added the client folder and the web folder now, now what to do?

**Comment by m-byte** [comment]
There is multiple options (I am assuming your server runs some kind of linux):
1. You disable any server application listening on port 80 like apache, nginx, etc and then run the master server (after changing the web port from 80 to 88). This is not recommended, as it might make your server more susceptible to attacks.
2. You start the master server and tell every user to connect to port 88. Still not the best solution.
3. (This is the recommended solution) Set all ports for Cigar (in `server/MasterServer.js`) to ports above 1024, as you won't have to start the program with superuser rights this way. Next, set a regular web server (e.g. nginx) up to forward requests to port 80 to your web server port and requests to port 443 to your game server port. Then, restart your regular web server as well as the master server.

**Comment by mayed505** [comment]
@m-byte mine runs on windows server 2012 r2 maybe thats the problem?

**Comment by m-byte** [comment]
Also, both sites you named are not using a static index.html: http://agar.gr.sa/index.html gets you "Sorry, the page you are looking for could not be found.", while http://3rb.io/index.html displays "The requested URL /index.html was not found on this server."

**Comment by m-byte** [comment]
Well, it is still possible to do the same with windows, the setup is a bit different, though.

**Comment by mayed505** [comment]
@m-byte hmm maybe its because i use darcy ripper to download the website.

**Comment by mayed505** [comment]
@m-byte then how do i run it without index.html? any tutorial?

**Comment by m-byte** [comment]
First of all, you need this extension: http://www.iis.net/downloads/microsoft/url-rewrite
Next, it is probably easiest to only pass the http stuff through iis, as the websocket would require some changes to the code.

**Comment by m-byte** [comment]
As far as I know, there is no tutorial at the moment. (I didn't write one and I guess MastaCoder didn't write one when he added his changes)

**Comment by mayed505** [comment]
@m-byte can we hangout instead of spamming the comments?

**Comment by m-byte** [comment]
Sure. Send a mail to my username at users.noreply.github.com and I will invite you to a hangout

**Comment by m-byte** [comment]
Ah my bad. that's the noreply

**Comment by mayed505** [comment]
yea i just wondered XD

**Comment by m-byte** [comment]
okay, send it to irgendwer2, it's my spam google account, i will respond with my proper account.

**Comment by mayed505** [comment]
Sent.

**Comment by mayed505** [comment]
Thanks to @m-byte for helping me with this issue a big thumbs up for him.

**Comment by Sentaq** [comment]
@mayed505, how did you fix it? I appreciate it if you could tell me the solution. And, do you have also a chat filter?

**Comment by m-byte** [comment]
@Sentaq: We installed it the way I described above.
Which server osdo you use?

**Comment by Sentaq** [comment]
@m-byte: Windows Server 2012

**Comment by m-byte** [comment]
The way we solved it right now is option 1 from my list above, so it is not exactly the best solution. That's why I'd rather not write a detailed guide of how to do it.
I will try to help @mayed505 to set it up as described in 3. Also, I already asked him to add detailed instructions of how we did it to the wiki. So it is probably best if you wait until then.

**Comment by Sentaq** [comment]
@m-byte Sure! Thanks tho!

**Comment by mayed505** [comment]
@m-byte go check the website i edited as much as possible :D

**Comment by mayed505** [comment]
Ill try to make a wiki tommorow
