### ISSUE TITLE
Make a vps options

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#163]
I want soo much to host on a vps but the vps don't have port only ip, like cigar.lukkez.c9users.io, i can't open the server with this vps, but i want to have :/

**Comment by mayed505** [comment]
@Lukkez just instead of ip place that domain it works or just ping the domain to get the ip address.

**Comment by Lukkez** [comment]
That don't work.... it's because i can't use ports on this vps

**Comment by MastaCoder** [comment]
Change the masterserver port to 80 or only use the gameserver. Cigar will always need more than 1 port which is an issue.
