### ISSUE TITLE
What client agarabi use?

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#164]
The title says all and how, much agario's i see use this client, i want to test too

**Comment by mayed505** [comment]
@Lukkez from what i know from extracting the code they use a completely modified code except for the cells or players they just modified the layout and adblocks :+1:

**Comment by Lukkez** [comment]
Can you send or teach how to get?

**Comment by MastaCoder** [comment]
It's a normal client just modified a lot.
