### ISSUE TITLE
Cell Split Speed

### ISSUE THREAD

**Issue by tveloper** [CigarProject/Cigar#165]
Hi,

Is there a way to control the cell split speed?

Thanks.

**Comment by mayed505** [comment]
@tveloper its in gameserver(NUMBER).ini @131 line playerSpeed = (the higher the number the higher the speed)

**Comment by tveloper** [comment]
@mayed505 Isn't that for player cell "moving" speed? or does it apply to **all** speeds?

**Comment by mayed505** [comment]
@tveloper it applies to playercell

**Comment by mayed505** [comment]
@tveloper more speed = faster split and faster feeding " W Key"

**Comment by MastaCoder** [comment]
I can add a split speed function if wanted :)

**Comment by MastaCoder** [comment]
Added d0a1e936ca5dd5857e8e7c1fca46f45cf0460f7b
