### ISSUE TITLE
Chat Filter Code But I dont know where to place it :P

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#166]
> `function filterText(sText) {
                var reBadWords = /FUCK|Gay|Bitch|motherfucker;
                return sText.replace(reBadWords, "****");
            }

            function protectnick(sText) {
                var reBadWords = /Dramex|dramex|〖Δ7ℵ〗♕-HmØØ_đ-♕|Console|console|Nyoof|nyoof/gi;
                return sText.replace(reBadWords, "Protected Nick");

			}
            function protectletters(sText) {
                var reBadWords = /Δ|Ø|7ℵ|♕-|-♕|Ǿ/gi;
                return sText.replace(reBadWords, "*");
            }
			
            function showText() {
                var oInput1 = document.getElementById("nick");
                var oInput2 = document.getElementById("nick");
                oInput2.value = protectletters(oInput1.value);
                oInput2.value = protectnick(oInput1.value);
                oInput2.value = filterText(oInput1.value);
            }
            function showText2() {
                var oInput1 = document.getElementById("chat_textbox");
                var oInput2 = document.getElementById("chat_textbox");
                oInput2.value = filterText(oInput1.value);
            }
`
Hope U enjoy

**Comment by MastaCoder** [comment]
I was planning to add this, I'll take a look at it when I get home.

**Comment by MastaCoder** [comment]
Added!

**Comment by m-byte** [comment]
There is one thing that should be noted, though:
This code is part of the javascript that's run by the client (computer of the user), so it can be easily circumvented. It is impossible to make sure the browser is actually running this code and not a modified version of it.

**Comment by mayed505** [comment]
@MastaCoder no credits for me :(

**Comment by MastaCoder** [comment]
lol @mayed505
