### ISSUE TITLE
[Request]Minimap

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#167]
Minimap like some agarios, and Dopegar have one, if someone teach me how to add here i will be soo happy :>

**Comment by tveloper** [comment]
That is server side.
Get custom clients that others made.

**Comment by Lukkez** [comment]
What clients? i don't know how to start Dopegar

**Comment by MastaCoder** [comment]
Oops, I guess I forgot to set it as client. So many server sided issues >.>
