### ISSUE TITLE
[Bug] Bots doesnt change their names with botnames.txt

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#168]
title says it all
i tried to rename bots in botnames.txt and nothing happens just ( bot1,bot2,bot3)
i tried to check the code but i couldnt fix it..

**Comment by MastaCoder** [comment]
Aw shucks.

**Comment by mayed505** [comment]
@MastaCoder i hope u could fix it and can u add " 3rab.co" as a demo for cigar? since i saw the old server doesnt work :D

**Comment by mayed505** [comment]
@MastaCoder did u fix it?

**Comment by ozdemirr** [comment]
do you think use faker.js for botnames? i can implement it.

**Comment by mayed505** [comment]
@ozdemirr what do u mean?

**Comment by ozdemirr** [comment]
@mayed505, we could use https://github.com/marak/Faker.js/ for generate botnames.

**Comment by mayed505** [comment]
Fixed #174
