### ISSUE TITLE
My skin repository

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#169]
Feel free to put skins on your own cigar server
[SKINS HERE (CLICK ME)](https://github.com/Lukkez/Agario-Skins)

**Comment by MastaCoder** [comment]
I'll leave this up for a week ;)

**Comment by mayed505** [comment]
@Lukkez i dont think people want to install this script manually if your are looking for noob players or not to be mean " new players to play and undetstand to install extensions"

**Comment by Lukkez** [comment]
@mayed505 What manually? only ctrl + a + ctrl + c and paste on Cigar skins, and the skin i will make a pastebin raw later when done

**Comment by Sentaq** [comment]
OF

@mayed505, when are you going to make the wiki about uploading skins?

**Comment by mayed505** [comment]
@Sentaq Its almost done. I just need to add features one yet.

**Comment by mayed505** [comment]
@Sentaq @MastaCoder @m-byte i gave up on the wiki i screwed the hell up after 3 hours of typing i forgot to save it and i got stressed. http://cigar-project.wikia.com/wiki/Cigar_Project_Wikia

**Comment by mayed505** [comment]
i added everything how to install with screenshots and how to install custom skins but now i gave up

**Comment by mayed505** [comment]
I can pass the wiki to anyone if anyone intrested.

**Comment by Sentaq** [comment]
@mayed505, I would like to have it!
