### ISSUE TITLE
restart server problem on centos?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#171]
hi,
i did a try on centos and notice that when i reboot my vps the game server not restart itself
thank you

**Comment by Lukkez** [comment]
This is a problem, i use Ubuntu and happens the same, lol

**Comment by MastaCoder** [comment]
You'd have to add the server to start on boot if you want to do that. Read the documentations about that online :3

**Comment by discoroveryx** [comment]
Centos = the large hemorrhoids
Use Debian or Ubuntu

**Comment by matrixreal** [comment]
@MastaCoder 
i don't find the documentation about adding the server on start boot

**Comment by eevaqueen** [comment]
So any help with this?,I used un successful  
crontab 
*/1 * * * * \cd \Cigar;/bin/sh start_masterserver.sh
it work good on terminal but crontab doesn't work,please help!
Thank you.
