### ISSUE TITLE
Add command gives Invalid Command error

### ISSUE THREAD

**Issue by ozdemirr** [CigarProject/Cigar#172]
Hi all,
I want to add new game server to master server, but when i typed add 127.0.0.1(or whatever) ServerName, it gives me Invalid Command error, i am wrong ? And what's the best way to add gameservers to master server ? 
An example; i have a server (4 core cpu) and i want that every game server should run on different core. Because i want to use full capacity of cpu in my server. What's the roadmap to do it ?
Thanks for your answers.

**Comment by MastaCoder** [comment]
You can try and add them through the masterserver.ini. If you want to use all cores, try using ```JXCore``` as it is a multithreaded version of Node.js.

If you are having issues adding servers, can you paste in your masterserver.ini and tell me what mode you want to add?

**Comment by ozdemirr** [comment]
@MastaCoder , i configured masterserver.ini with server's ip address, and i generated 3 gameserver ini file like gameserver1.ini, gameserver2.ini etc. And i started the app as "node server/index.js" then there are 3 region, everything is ok but node app works on 1 core. I triend to start app via JXCore like "jx mt-keep:4 server/index.js" but then, every player spawn on another core. 
What should ı do ?
Thanks for your help.

**Comment by MastaCoder** [comment]
If that were me, I would just run multiple processes of that and change the client to not auto generate the servers. (So I can add the servers separately) If you're on Linux the start_gameserver function still isn't working as well as I thought.
