### ISSUE TITLE
Master chat Commands

### ISSUE THREAD

**Issue by ElMay0r** [CigarProject/Cigar#177]
Why the commands on the chat if you cant see the ID's of the players on the game?

Example, i want to ban or kill someone. 
/rcon pass kill (ID) or (IP). <- Thats is shown only on the console.

there's any way to kill or ban players by their name?

**Comment by MastaCoder** [comment]
```there's any way to kill or ban players by their name?```

Nope because multiple different people can have that name. Rcon is really for board changing, spawning food, restarting server, etc.

**Comment by ElMay0r** [comment]
i was thinking on contracting administrator who can moderate the name and skins, but this wont help.
