### ISSUE TITLE
Viruses

### ISSUE THREAD

**Issue by ElMay0r** [CigarProject/Cigar#178]
On my server the Virus moves when you shot them.

How can i make them divide when shot?

**Comment by MastaCoder** [comment]
The moving viruses happen on the experimental gamemode. To make them not move you have to change your gamemode to FFA. This can be changed in gameserver.ini by changing the serverGamemode to 0.

**Comment by ElMay0r** [comment]
Nop, they are like that on all gamemode, 0,1,2 ....

**Comment by MastaCoder** [comment]
Fine for me. @ElMay0r

**Comment by ElMay0r** [comment]
Take a look: www.Agar.Blue
