### ISSUE TITLE
Skin Changer

### ISSUE THREAD

**Issue by TheCzechTayen** [CigarProject/Cigar#179]
Hi and sorry, I'm not good in english well.

I want to create skin changer. I want to upload images from a folder skins into div what would have managed in php. Advise someone how to change players skin by clicking on the picture from the div?

`
<?php
  foreach (glob("skins/*.png") as $filename) {
  echo "<div class='galleryImage'><img src='". $filename . "'class='' /></div>";
  }
?>
`

This displays the images from a folder skins, how to assign individual skin on the player by clicking on the image?

Thanks for helping

**Comment by MastaCoder** [comment]
You can create a JS script that changes the text to that skin.

**Comment by TheCzechTayen** [comment]
Can you help me with this script for me? Im not so good in JS

**Comment by MastaCoder** [comment]
Add an onlick attribute to all of the images with an href. Then inside of that type in ```document.getElementById("nick").value = idkwhatyourvariableisfornames.```

**Comment by TheCzechTayen** [comment]
This does not work. I need to click on the image to display on the cell. Top that beneath each picture was button and clicking on it will change the skin of the player so that all could see. I think it will be addressed along with MySQL, but I'm not sure

**Comment by mayed505** [comment]
@TheCzechTayen if you go to my website 3rab.co and you type any skin name mine will appear at the bottom for example type in the nick the skins name like --ace-- the skin image will appear.

**Comment by TheCzechTayen** [comment]
@mayed505 nice, can you upload this issue for me please? :)

**Comment by mayed505** [comment]
@TheCzechTayen Im sorry but its complicated and i dont really have time to give you code.

**Comment by TheCzechTayen** [comment]
Its okay. So any other idea for my issue? :)

**Comment by MastaCoder** [comment]
See the skins file that generates the skins page for information on this.
