### ISSUE TITLE
Client freezes during split

### ISSUE THREAD

**Issue by nandoy** [CigarProject/Cigar#180]
Hi,

I'm having issues during some mass split, when the client be exploded by a virus, some times the game on client-side freezes.

Someone know what I can do to solve that?

I have checked the Console, and don't get any error, the Agario only stop response.

Regards.

**Comment by smatch999** [comment]
increase your CPU cores/socket of your dedicated server, and NOT use VPS.

**Comment by nandoy** [comment]
Hi,

The CPU usage is lower than 2%.
The cause can be it?

Regards.

**Comment by smatch999** [comment]
mhmm... 
what is your server website?

**Comment by nandoy** [comment]
Hi,

The site is: http://agario.tssabrasil.com.br/
I've done some changes on Server configuration, I have limited the max mass to 15K and limed the cells on 8 per player.
And the speed for split is -10.

This helped some players.

Regards.

**Comment by smatch999** [comment]
yes, you adjusts is ok.
and, startMass and maxMass?
what is your configuration VPS/Dedicated?

**Comment by nandoy** [comment]
Hi,

playerStartMass = 10
playerMaxMass = 15000

The server is hosted on USA, with 4GB and 4vCPUs @ 3.5GHz on a E5 6c/12t. Network card is a Realtek 100Mbps.
The official client is that: http://172.106.11.131:88/

This can be the problem?
Because I need make a custom index for the site.

Regards.

**Comment by smatch999** [comment]
ok, is good.

Try download http://code.jquery.com/jquery-1.11.3.min.js and upload this on your host and use
<script src="jquery-1.11.3.min.js"></script>
do the same bootstrap...

you upgraded the cigar to the latest version of this month?
There no are many reasons to "freeze" the cell, or your dedicated issues or html un-optimized.

You host your server in Windows or linux?
If Windows, this can also be a problem!!!
If on Linux, try to update the version of NODE and NPM.

**Comment by nandoy** [comment]
Okay.

I'll update that for CentOs 6.x x64, and check if the problem happens.
The server is updated correctly, on this last version published.

I'll keep you update about that, thank you.

Regards.

**Comment by smatch999** [comment]
You're welcome.

**Comment by nandoy** [comment]
A stupid answer:
The script can't be started with nohup?

I'm trying start the server with: nohup ./start_gameserver.sh &
and an error happens.
---
Log:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:883:11)
    at Server._listen2 (net.js:1021:14)
    at listen (net.js:1043:10)
    at Server.listen (net.js:1109:5)
    at GameServer.startStatsServer (/root/Cigar-master-2/server/GameServer.js:1066:21)
    at GameServer.start (/root/Cigar-master-2/server/GameServer.js:293:10)
    at MasterServer.createServer (/root/Cigar-master-2/server/MasterServer.js:219:8)
    at MasterServer.loadConfig (/root/Cigar-master-2/server/MasterServer.js:141:22)
    at MasterServer.start (/root/Cigar-master-2/server/MasterServer.js:75:10)
    at Object.<anonymous> (/root/Cigar-master-2/server/index.js:55:18)
----

**Comment by nandoy** [comment]
The server start correct with command: ./start_gameserver.sh
But I need close the SSH console.

**Comment by m-byte** [comment]
@nandoy use `screen`

**Comment by smatch999** [comment]
@nandoy after start with command ./start_gameserver.sh PRESS CTRL+A+D on SSH. :+1:

**Comment by MastaCoder** [comment]
@nandoy Just like @m-byte said, download and install screen, run a screen by typing in ```screen -mdS {servername} sh start_gameserver.sh```. Remember to replace server name with your own.

**Comment by MastaCoder** [comment]
2fe4db58b3273dd262a7c763858919cc689bf6c5
