### ISSUE TITLE
Where is index.html

### ISSUE THREAD

**Issue by xmicro** [CigarProject/Cigar#181]
I'm not able to make the client work without it. Where is it? Or has the method of the client changed? If so, how?

**Comment by xmicro** [comment]
Exactly what do I upload to my website? I uploaded client, did nothing, then tried web, did nothing. What am I missing?

**Comment by discoroveryx** [comment]
Nodejs Express framework render html to template server/web/views/*.hbs

**Comment by xmicro** [comment]
Can you explain how I do this?

**Comment by discoroveryx** [comment]
what is your operation system? Linux?

**Comment by xmicro** [comment]
Windows. I'll be using Linux in the future, however.

**Comment by discoroveryx** [comment]
you need install https://www.npmjs.com/package/npm win verison, then download cigar and start install_modules.bat

**Comment by xmicro** [comment]
Done. What files do I upload to my website?

**Comment by discoroveryx** [comment]
Your web site is managed by the apache2 web server or nginx?

**Comment by xmicro** [comment]
I just did something easier. I added a URL Frame to my IP and I'm going to go through there until I get a VPS. At which point I will make the URL Frame to the VPS.

**Comment by MastaCoder** [comment]
If you launch under master_server.bat the master server will automatically make and host the index.html for you.

**Comment by xmicro** [comment]
@discoroveryx I'd like to revisit this alternative. Apache2.
