### ISSUE TITLE
[Bug?] Connecting to other gameservers. Error

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#184]
When i tried to create more than 1 gameserver and i pointed the main_out to the masterserver IP:80
i cant connect it to it. Now my game main_out is now pointed to IP:1501 (GameServer1)
Its just when i point the main_out to master server it doesnt work just opens the normal menu but cant connect to any servers. Anyone help?
Screenshot: [https://gyazo.com/b130a326827cfe33a4d73e33a305bdd4](url)

**Comment by mayed505** [comment]
Bump.

**Comment by MastaCoder** [comment]
Just make a function inside of it that connects to a server and instead of switching just set the value of the dropdown to that server and connect it.
