### ISSUE TITLE
[Pull Request] New Icons For Mobile

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#185]
It Would be awesome to add clean icons not like the old ones which looked like science ish
https://gyazo.com/7b490701dfa776309365f234c5a0ab04
Source: Agario Mobile App 
Someone Can get the icons?

**Comment by m-byte** [comment]
Someone would have to draw new icons. It would definitely be copyright infringement to just add them without permission from their creators.

**Comment by MastaCoder** [comment]
Yeah, it would be nice if someone could create some icons for us ;)

**Comment by mayed505** [comment]
@m-byte your right i never thought of it it would be cool if someone design "CLEAN" Icon not the old one :100:

**Comment by mayed505** [comment]
@m-byte please check my issue #184

**Comment by mayed505** [comment]
@m-byte @MastaCoder Ha. I just got the icon from google :P go to 3rab.co on your mobile and check it out, and if you like it just tell me and ill send in the files.

**Comment by m-byte** [comment]
@mayed505 That's exactly what I said we can't do...

**Comment by MastaCoder** [comment]
^^

**Comment by mayed505** [comment]
@m-byte fine.
