### ISSUE TITLE
When I try to upload custom skins, the page just keeps loading forever... The server works fine.

### ISSUE THREAD

**Issue by xmicro** [CigarProject/Cigar#186]
The way I have it set up is a URL Frame pointing to my IP. The game and gallery work fine. But when I try to add a skin through the URL Frame it will say 404 Not Found, and when I try it through my direct IP, it shows me uploads.html and everything, but when I press submit it just loads forever. The skin would work too, if I add it to /client/skins it works fine, however...

**Comment by xmicro** [comment]
Perhaps I'm not portforwading a certain port? Currently I am doing 88, 1501, and 1600.

**Comment by MastaCoder** [comment]
Upload.html is trash right now. I have to update it :)

**Comment by xmicro** [comment]
Oh ok. If it helps, this came up: http://prntscr.com/al914k

**Comment by xmicro** [comment]
And is the reason that skins don't work because "Upload.html is trash?" Or did I set something up wrong, and Uploads.html is at least functional?

**Comment by MastaCoder** [comment]
Upload.html is built poorly, I have to check it and work on it a bit.

**Comment by xmicro** [comment]
Ok then. Keep me posted :).

**Comment by Lukkez** [comment]
@MastaCoder I can build one upload ? with php/css, on bootstrap i think i can

**Comment by HAlexTM** [comment]
Upload has been fixed, issue can be closed.

**Comment by MastaCoder** [comment]
Need to add upload skin function back sometime.
