### ISSUE TITLE
Agario Server Hosting

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#188]
So i made a agario website for my school and everyone loved the game and played it including the teachers. The tech department blocked agario so many times that they blocked every single ip meaning just type random numbers in search like 19.72.18.10 it says its blocked... is there a way i can host the agario server without using an ip so it is unblocked, meaning the server ip that the website connects to. Anyone know a way to cover up the ip, and if so how to put the domain or cover up in as the ip? this might sound confusing but please help!

**Comment by J4awesome** [comment]
Use the website noip.org you type in the IP address that you setup for your agario server and it makes a website that redirects you to your server and it's free also you can make many urls if they block.I used it when I Did it for my school.

**Comment by J4awesome** [comment]
The website is noip.com not noip.org sry.

**Comment by mayed505** [comment]
@Logan7432 I would suggest as @J4awesome Use noip.com and update the name everytime they block it as i did too :D

**Comment by Logan7432** [comment]
you know whats funny? I used no-ip as a web redirect to my Website. So are you saying i can do the same for the server that the website connects to? just a reminder that they blocked every ip possible so will this be able to bypass that?

**Comment by Logan7432** [comment]
I also forgot to say, the client is unblocked meaning my website is unblocked but the server that the site connects to is blocked

**Comment by mayed505** [comment]
@Logan7432  can u give me an example like : web server: web.no-ip.org   server: server.no-ip.org which one is blocked if its the server just change the server.no-ip.org to server1.zapto.org just like that 
.zapto.org already exists.

**Comment by Logan7432** [comment]
@mayed505 Actully thanks for your guys help i figured out how to set it up with no-ip and it was unblocked! Thanks!!!
