### ISSUE TITLE
hidechat

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#189]
hi 
i'm using the client with cigar server
please i would like to know what is the js call to hide the chat please ?
thank you

**Comment by matrixreal** [comment]
my code in main_out.js is 
wHandle.setHideChat = function (arg) {
hideChat = arg;
if (arg) {
wjQuery("#chat_textbox").hide();
}
else {
wjQuery("#chat_textbox").show();
}
};
but i dont know what is the js call / function to hide the chat
thanks for help

**Comment by MastaCoder** [comment]
There is no function yet in it.

**Comment by matrixreal** [comment]
yes i pick it from a client

**Comment by MastaCoder** [comment]
Yeah. But that function isn't working to hide chat text.

**Comment by Sentaq** [comment]
@MastaCoder, are you going to implent this function? Or not yet?

**Comment by MastaCoder** [comment]
I would, but I can't >.>

**Comment by Logan7432** [comment]
Guys.

**Comment by Sentaq** [comment]
@Logan7432 if you want, why not?

**Comment by Logan7432** [comment]
https://www.mediafire.com/?aqp9z84id12vn4v This is the website I heavily modified to work with the Cigar Server. This site is the site I made for my school so its going to have stuff like  WestAgario all over it, which you can just change. Btw you need a web hosting thing like http://aprelium.com/abyssws/download.php which is what i use or you can use a web host like x10hosting.

**Comment by mayed505** [comment]
@Logan7432 i couldnt get yours to work with my cigar can you also provide me the full cigar server too?

**Comment by Logan7432** [comment]
@mayed505 http://www.mediafire.com/download/4s6rw13x4fgeu6o/WestServer.zip Heres my server i use with the client. Make sure you forward the port 1501 or what every port your going to be using and dont forget to change the ip address that the website is coneecting to in the mainout.js. Also thanks I so many hours trying to make that site, and theres still so many thing i would love to add.

**Comment by mayed505** [comment]
@Logan7432 it was amazing... i tried just like yours but theres was a problem with my leaderboard i wanted it to be rounded just like agairo.sx but failed :D

**Comment by MastaCoder** [comment]
The hide chat option doesn't work in yours, it only hides the chat box.

**Comment by Logan7432** [comment]
Oh, My bad I didnt read the right! Now I know what you mean.

**Comment by Logan7432** [comment]
@mayed If you want it to be round you might need to change something in the mainout.js or index.html, I cant remember exactly.

**Comment by mayed505** [comment]
It's in the main out

**Comment by MastaCoder** [comment]
I need to add this, I know how to add it. I'll do it soon 👍

**Comment by HAlexTM** [comment]
Should be fixed with #383

**Comment by MastaCoder** [comment]
👍
