### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#190]
I am not sure how to use admin...... i put my admin name in and my adminnewname and then i try to go in the game using just admin name hoping it would change me to my adminnewname and its not and i have admin enabled? can someone walk me through how to set this up?

**Comment by MastaCoder** [comment]
Can you paste in your gameserver.ini? Only the part for admin.

**Comment by Logan7432** [comment]
Yes, I'll paste it in the morning if your reading this around when I posted this which is 11:03pm EST

**Comment by Logan7432** [comment]
@MastaCoder I wont be home till late tonight so cant get you the code till later but in the mean time can you please walk me through how to set up the admin properly? Like can you please tell me how to like put a password or something in so i can use commands in game.

**Comment by MastaCoder** [comment]
adminConfig = 1, and set the admin names. That's really all you need to do.

**Comment by Logan7432** [comment]
So what do i do after i set the names? cause i spawn in as the name i set and it dosnt changed me to the newadminname thing

**Comment by MastaCoder** [comment]
Do you get an error? Can you screenshot the error?

**Comment by Logan7432** [comment]
@MastaCoder http://postimg.org/image/simj67bel/ Here is my console are i type in the name1. BTW i put the code for it back to default and turned admin back on.

**Comment by MastaCoder** [comment]
Fixed in latest commit!

**Comment by Logan7432** [comment]
@MastaCoder  Thanks! Works perfect. But there is a very small bug with it so if someone spawns with my admin name they get the 500 mass but it renames them to unnamecell, this only happens if for example im in the server playing and somebody tries to spawn as me.

**Comment by MastaCoder** [comment]
Strange. It doesn't seem to happen on my end..

**Comment by Logan7432** [comment]
@MastaCoder Ok, dosnt matter ill just work around it and put the start mass to 10 so even if it bugs out  the other person will just end up with 10 start mass anyway instead of 500.

**Comment by MastaCoder** [comment]
Haha I'll try my best to find this issue ;) Wait. Make adminBlockNames to 1 :+1:
