### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#191]
@MastaCoder Is there a way to customize the grid on the client? I want to add a picture to the middle of my map.

**Comment by mayed505** [comment]
@Logan7432 i think it would be possible since you can change the grid to dark theme since what i saw in main_out.js BUT it gonna take a long time.

**Comment by Logan7432** [comment]
@mayed505 you think? You can't just get. Link to a picture and slap it on somewhere in the grid
