### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sentaq** [CigarProject/Cigar#192]
Hi,

What does this error mean: [Error] RangeError: attempt to write beyond buffer bounds

And is it also possible to fix it?

**Comment by mayed505** [comment]
@Sentaq where does this occur?

**Comment by Sentaq** [comment]
@mayed505, well, that I don't know. When people were playing (around 20, I don't know exactly) yesterday, it started to occur multiple times in the emulator.

**Comment by MastaCoder** [comment]
Make sure you are on a fresh copy.
