### ISSUE TITLE
Hide nickname when skin is using

### ISSUE THREAD

**Issue by YameCz** [CigarProject/Cigar#196]
I think that idea to hide nickname will make game cleaner

**Comment by Logan7432** [comment]
What do you mean? Are you talking about an option to remove names while using the skins or just when you use skins it removes the name? Because most people like me like to see the names of people when using a skin to see what skin there using and to see who they are.

**Comment by YameCz** [comment]
> Are you talking about **an option to remove names while using the skins**
Yes, that's what i mean. If more people wanted to have their names displayed even if skin is used, we can close this issue.
