### ISSUE TITLE
I get tag code but idk at what place put

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#197]
<div class="form-group clearfix">
                <input list="clan-tags" id="clan-tag" type="text" class="form-control dropdown pull-left" onblur="getTag('0','0','jacques');" placeholder="Tag" maxlength="10" style="width:80px">
                    <datalist id="clan-tags">
                        <option value="ΔCΣ ">Ace</option>
                        <option value="ᎯᏰᑬ ">AgarbotsPro's</option>
                        <option value="〖ᗩǤ〗 ">Arcade Go</option>
                        <option value="《ƸӜƷ》 ">Badass Butterflies</option>
                        <option value="βυгƝ ">Burn</option>
                        <option value="ᗪƐѴ ">Dev</option>
                        <option value="Heяø ">Hero</option>
                        <option value="MƓR ">Magarro</option>
                        <option value="ℳℜℭ ">Miracle</option>
                        <option value="ƝƁƘ ">Natural Born Killers</option>
                        <option value="《ℝ》 ">Reddit</option>
                        <option value="〖ＲƗＰ〗 ">Rip</option>
                        <option value="ƬψƬ ">Team Youtube</option>
                        <option value="〖ᏉᎥᎮ〗 ">VIP</option>
                        <option value="ᗯᗩᖇᗪ ">Ward</option>
                        <option value="〖ƔŤṦ〗 ">YTS</option>
                        <option value="ƵŦ ">ZT</option>
                        <option value="❰☯❱ "></option>
                    </datalist>
            </div>

**Comment by Lukkez** [comment]
@MastaCoder

**Comment by Lukkez** [comment]
I already put, i don't need more, i made different

**Comment by MastaCoder** [comment]
This is more preference thing.
