### ISSUE TITLE
Admin Improvement/feature

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#199]
@MastaCoder Hey, a really cool feature i thought of is when your signed in as a admin and talk in the chat, you name should be a different color then the other people so instead of what you said being white like everyone else it should be for example, blue and you should be able to choose what color you would like to have. Dosnt seem that hard to implement into the game and i think its something cool to have.

**Comment by MastaCoder** [comment]
You can change a person's color in the console I believe.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
