### ISSUE TITLE
Black Username in Chatting

### ISSUE THREAD

**Issue by tveloper** [CigarProject/Cigar#201]
Hey,

Recently (? - about when you merged Cigar and Cigar-Plus), some of the nicknames on chat turned black. Even through their cell color is not black, it shows up as black, which makes it very hard to read in dark mode. This wasn't a client side issue, so it is the server issue. Is there a way to change to color code?

Thanks @

**Comment by MastaCoder** [comment]
I think this is a client side issue. I'm pretty sure when we added the new colors text, the method that the client reads the colors is messed up. I know the fix in the client, just forgot what it was. I'll get back to this post once I figure that out.

**Comment by tveloper** [comment]
Hmm... I used an another client, and it still didn't fix.

**Comment by iBanex** [comment]
**add these functions in client:**
function componentToHex(c) {
        var hex = c.toString(16);
	return hex.length == 1 ? "0" + hex : hex;
	}

function rgbToHex(r, g, b) {
return "#" + componentToHex(r) + componentToHex(g) + componentToHex(b);
}

**look for:**
        var r = view.getUint8(offset++),
            g = view.getUint8(offset++),
            b = view.getUint8(offset++),
            color = (r << 16 | g << 8 | b).toString(16);
        while (color.length > 6) {
            color = '0' + color;
        }
        color = '#' + color;

**and reclape for:**
var r = view.getUint8(offset++),
            g = view.getUint8(offset++),
            b = view.getUint8(offset++),
			color = rgbToHex(r,g,b);

**Comment by mys** [comment]
I have switched in my version:

> while (color.length > 6)

to 

> while (color.length < 6)

**Comment by MastaCoder** [comment]
Added in latest commit :dancer:
