### ISSUE TITLE
Bots with skins! 

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#204]
Is there a way to make it so people cant put skins on bots? Because on my server people are adding skins to bots and its very annoying! Thanks!

**Comment by MastaCoder** [comment]
What type of bots are we talking about..

**Comment by Logan7432** [comment]
Like, when you do addbot # in console those bots, the AI's. People keep adding skins to them for me. Also please make it so people cant name themselfs as bots! like for example, if the bot is named bot100 is there a way to block the name bot100 so that people cant name themselfs as bot? when i block the name of the bot it turns the real bot into a un named cell unstede of just blocking the name from real people trying to name themselfs as bots.

**Comment by MastaCoder** [comment]
Just add that name to the blockNames section so people can't use them. It's in the gameserver.ini under playerBlockedNames.

**Comment by Logan7432** [comment]
Yes, But then it blocks the bots from using the name for example if i block the name bot100 and the bot is named bot100 it will block the bot from using it and change the name to An Unnamed Cell

**Comment by zPoseidon** [comment]
MastaCoder Dear u can help? Add me on skype and please help me. My skype: thiago.lourenco6

**Comment by tveloper** [comment]
@Logan7432 Make a .js file to verify nicknames in the client.
