### ISSUE TITLE
Bots improvement

### ISSUE THREAD

**Issue by ElMay0r** [CigarProject/Cigar#205]
The Bots are very "Stupids" The run in to your cell, the eat the viruses, they dont even split that much.

it would be nice to see them play even a lil bit better.

**Comment by Logan7432** [comment]
I personally love them being stupid because i love how they always run into viruses and i can just eat them. But other people i can see wanting them being smarter.

**Comment by ElMay0r** [comment]
yes but that makes the game very easy.
people likes competitives

**Comment by mayed505** [comment]
Hmm. Mode1 = Stupid.        Mode 2 = Smart.  so people can choose between them.

**Comment by Logan7432** [comment]
Great Idea! ^^

**Comment by MastaCoder** [comment]
Will need to work on this.

**Comment by MastaCoder** [comment]
Cigar is now client only.
