### ISSUE TITLE
mysql / highscore

### ISSUE THREAD

**Issue by efsysefsys** [CigarProject/Cigar#206]
add please highscore to records in the mysql database.

**Comment by YameCz** [comment]
Totally agree! Great idea.

**Comment by Logan7432** [comment]
^^^^ I think this would be awesome! Maybe even a login system and players that are members get there high scores placed.

**Comment by MastaCoder** [comment]
#4 

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
