### ISSUE TITLE
Improved Splitting Physics

### ISSUE THREAD

**Issue by tveloper** [CigarProject/Cigar#207]
Hello,

Is there a way to improve the splitting physics?
I have tried some tricks in splitting, and it wouldn't do so for the Cigar server.
Is there a way to improve this, so that users could tricksplit etc. 

Thanks :)

**Comment by MastaCoder** [comment]
I've tried this but the physics gobble up too much resources and the tick times are messed up.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
