### ISSUE TITLE
When eat a virus game will freeze of the player

### ISSUE THREAD

**Issue by djoey123** [CigarProject/Cigar#21]
When someone eat a virus there game will freeze is it a server problem or website problem?

And will admin commands in game added? And maybe a kick command?

**Comment by djoey123** [comment]
I found a new 1 when i edit the site in /client it will not be editted to the website
When i edit the index.html it will not change anything

**Comment by m-byte** [comment]
That last one isn't really a bug.. It's more that we forgot to delete index.html. What gets sent to the client can be edited in [game.hbs](https://github.com/m-byte/Cigar/blob/master/server/web/views/game.hbs)
Your first bug sounds like something we should look into.

**Comment by djoey123** [comment]
Ty for the fast replay, My next problem is people can easyly flood the server with a http attack.
and when i run create Dutch 0. It says Invalid command! i run linux.

**Comment by m-byte** [comment]
Can you send a screenshot?

**Comment by djoey123** [comment]
http://prntscr.com/7ts4fo here it is

**Comment by m-byte** [comment]
As far as I remember, the commands are case sensitive. Also, you have to do a `Select 0` first. Last, but not least, custom regions are not yet supported.

**Comment by djoey123** [comment]
ahh never know you most do select 0.

What are the supported regions where can i see it?

**Comment by djoey123** [comment]
New thing found you cant upload your own skin

**Comment by m-byte** [comment]
@djoey123 Are you running Cigar on Windows?

**Comment by djoey123** [comment]
no i am running linux centos 7

**Comment by ElMay0r** [comment]
Yes this happens in my server too! i use windows VPS 8GM RAM 300+ Brandwith

**Comment by MastaCoder** [comment]
Can anyone confirm if this bug still exists?

**Comment by MastaCoder** [comment]
This shouldn't exist with the new packetHandler code.
