### ISSUE TITLE
Packet handler error!? Please fix!!

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#212]
Hey, Im having trouble with server crashing with the new cilent im working on, When the client trys to connect to server it connects for a split second and then the server crashes! The crash error is this http://postimg.org/image/u7y5ci1sl/ Please fix or help me fix this issue as soon as possible, Thanks!

**Comment by Logan7432** [comment]
@MastaCoder Hey, if you can address this issue that would be great, I really badly need this fixed. Thanks

**Comment by mayed505** [comment]
@Logan7432 reinstall server folders and delete node_modules and run the isntall modules.bat
