### ISSUE TITLE
Please Add mysql highscores and login players just like normal agario.

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#213]
Please Add mysql highscores and login players just like normal agario. its possible and it would be awesome if someone tries to actually do it.
Idea1: mysql databases that write/read player highest score and level up
idea2: add login protocol system for players to be able to receive xp and able to unlock super rare skins that uses coins
idea3: add you can use any skin without entering the name of the skin so we get the skin, the idea is that you can choose any skin with any name. Just like normal agario
I think its kinda hard but it would be great please tell me your opinions.

**Comment by Logan7432** [comment]
Very good idea, i think this should be implamented!

**Comment by MastaCoder** [comment]
#4 

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
