### ISSUE TITLE
Admin Panel? manage servers and much more :D

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#214]
I got an idea Admin panel for any cigar server owner which you can remotely edit server configs,game server configs and more importantly console.
forexample for how to access admin panel if the game is http://cigargame.com the admin panel will be http://cigargame.com:1234  port is changeable and when you go to the admin panel you will be redirected to login and password screen which is setup through the master server config or game server.

**Comment by Logan7432** [comment]
@mayed505 Wow, Thats a great idea, I really need something like this mostly because i run my server for school and i would really like to be able to work on the config files remotely.

**Comment by MastaCoder** [comment]
This will be too much work for a simple client. The console is your best bet, as then we would need more things installed just for that, like MySQL, PHP (for sure), etc.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.

**Comment by Niall7459** [comment]
You can use OgarServ it comes with a management panel.
