### ISSUE TITLE
Add Serverlist file

### ISSUE THREAD

**Issue by Roken120** [CigarProject/Cigar#215]
Hello
Please add server list file for add server ip and more 
for exemple on the masterserver.ini
regions = {"FFA": 1, "TEAMS": 0}
server = {"TEAMS": ip:port; ip:port, "FFA":ip:port}

**Comment by mayed505** [comment]
@Roken120 nice idea. Can you explain the use?

**Comment by Roken120** [comment]
Hello
For not execute add commande
After SERVER restart 
Sorry my english is not verry good

**Comment by MastaCoder** [comment]
The growth is for the client to simply use a for command. Far too much work if we want to add this, but I'll keep it in mind.

**Comment by Roken120** [comment]
Ok because is veery very null after master server restart all server is disconnected to master please help me

**Comment by MastaCoder** [comment]
Cigar is now client only.
