### ISSUE TITLE
Option to control Sun's Max Size

### ISSUE THREAD

**Issue by tveloper** [CigarProject/Cigar#216]
Hello,

In the Experiment mode, there are "Sun" that spawns food. Is there a way to limit the maximum size?
If the "sun" gets too big, than food won't be able to spawn.

Thanks :)

**Comment by mayed505** [comment]
@tveloper is it avaliable in ogar? If you didnt know cigar uses ogar but modified alot.

**Comment by MastaCoder** [comment]
I can add this pretty easily. I'll see if I can do it if I ever have time these months.

**Comment by MastaCoder** [comment]
Cigar is now client only.
