### ISSUE TITLE
[Not Issue]Helping

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#217]
Guys, after some time learning html/css and a bit of JS i will start to help out the client, making better pages, ;)

**Comment by mayed505** [comment]
Do you have an example? i am the same like you http://3rab.co

**Comment by m-byte** [comment]
Here are a few sites and tutorials that might be useful to you. I put the topic in round brackets and an indication of who it might apply to in square brackets. Also, they are in the order I'd recommend:
- http://www.w3schools.com/ (html, css, basic js) [client]
- http://www.tutorialspoint.com/javascript/ (js) [server]
- http://nodeguide.com/beginner.html (basic node.js) [all]
- http://www.sitepoint.com/beginners-guide-node-package-manager/ (npm) [all]
- http://expressjs.com/ (express.js - we use it configured for hbs) [client]
- http://code.tutsplus.com/tutorials/an-introduction-to-handlebars--net-27761 (handlebars) [client]
- http://handlebarsjs.com/expressions.html (handlebars) [client]
- https://daringfireball.net/projects/markdown/basics (markdown) [documentation]
- https://git-scm.com/docs/gittutorial (git) [all]

**Comment by mayed505** [comment]
@m-byte some cigar servers if you dont write any username in the text bar you spawn like ( cell1245 )

**Comment by Lukkez** [comment]
I used w3schools, codeacademy to learn, sorry for later reply
Now i'll start to make some client things

**Comment by Lukkez** [comment]
@mayed505 I think it's like this
- The servers check your name
- If the name is nothing
- Get a name from a random string generator and set to play
(Not is only this only fast things)

**Comment by MastaCoder** [comment]
Not a random string generator. There is a variable that grows everytime a player spawns and sets the name to that.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
