### ISSUE TITLE
Chat/Spam Glitch

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#218]
Im not sure why or how to fix this but my client starts spamming the chat in game without me doing anything...... Like it just keeps spamming the chat! Heres an example, http://postimg.org/image/3tbfmtznt/

**Comment by mayed505** [comment]
@Logan7432 how did you get people get like cell(number)? cell348? i want that for my unnamed cells.

**Comment by Logan7432** [comment]
@mayed505 I can try and help you out when i get home, i wont be able to access the my computer till tomorrow night, Im actully still in development for this and its stuck on cell348 and dosnt change, its hard to explain but i will try and help you out when i get home. But if someone can help me out with the original problem im having that would be great.

**Comment by MastaCoder** [comment]
Make sure you are on a fresh copy.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
