### ISSUE TITLE
Autorename

### ISSUE THREAD

**Issue by TheCzechTayen** [CigarProject/Cigar#220]
Hello, how do I change a file uploads.php to file automatically when recording renamed the nickname players and also how to enable a 512x512 picture size. If the same user uploaded the picture again, so will overwrite the original.

Thanks in advance

**Comment by MastaCoder** [comment]
This is some PHP that can be solved using stackoverflow.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
