### ISSUE TITLE
Dot Colors Please HELP!!!!

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#222]
Where in the client side can you change the color of the food that spawns? I want to have my food and viruses look like the ones on Agario.wtf

**Comment by Logan7432** [comment]
@MastaCoder Also this is the client im using http://goo.gl/8OJbLa Please Get back to me!

**Comment by Logan7432** [comment]
So how do i make my dots cell, viruses, and food look like this? https://i.imgsafe.org/7433d2e.png Please Please help!

**Comment by Logan7432** [comment]
@MastaCoder Mastercoder, Please let me know where i can find this stuff so i can change the color of the dots. This is on client side im pretty sure and i cannot find out where the dot colors are. Im starting to get frustrated about this cause i cant find it. Please Help it takes like min to let me know. Thanks!

**Comment by Logan7432** [comment]
Someone please let me know soon!

**Comment by MastaCoder** [comment]
https://github.com/CigarProject/Cigar/blob/master/server/GameServer.js#L329 and the virus is in cell.js.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.

**Comment by Logan7432** [comment]
@MastaCoder How do I change the transparency of viruses?

**Comment by djbencrazy** [comment]
I have the transparent virus found badger not as hard as you 've efjes gedult I'll put it online.
You want it so if http://crazyogar.ga

**Comment by MastaCoder** [comment]
Open the main_out.js and find where it has the opacity for viruses? I don't know much about the client side.

Virus can be changed in cell.js at the top.

**Comment by Logan7432** [comment]
Thanks Ill try it out.

**Comment by Logan7432** [comment]
@MastaCoder The post i said "and  what part do I edit to change the color" My fault I didn't be exact, what i meant was what part do i edit to change the color for the food" you told me a few post above on what line but where do i change the colors for the food? and the line around the food thats a little darker i want to change to black. I really want the food to look like Agario.wtf Please check that sight out and let me know how to make the food look like on there.

**Comment by djbencrazy** [comment]
you have a game mode that lets you change all the time the colors of the nourishment

**Comment by djbencrazy** [comment]
_I have found you an update and I will send you now_

**search this**
if ((show color || 15 <this.size) &&! b) {
                     ctx.strokeStyle = '# 000000';
                     ctx.globalAlpha * = .1;
                     ctx.stroke ();
                 }

**and change to this**
if ((show color || 15 <this.size) &&! b) {
                     ctx.strokeStyle = '# 000000';
                     ctx.stroke ();
                 }
**it's something that you need to change
search this**
this.updatePos c = ();
                 this.destroyed && (ctx.globalAlpha * = 1 - c);
                 ctx.lineWidth = 10;
                 ctx.lineCap = "round";
                 ctx.lineJoin = this.isVirus? "Miter", "round";

**and change to this**
this.updatePos c = ();
ctx.globalAlpha = 1;
                 this.destroyed && (ctx.globalAlpha * = 1 - c);
if (this.color! = '# 0a0a0a') {
ctx.lineWidth = 10;
ctx.lineCap = "round";
ctx.lineJoin = this.isVirus? "Miter", "round";
}

_have fun_

**Comment by Logan7432** [comment]
@djbencrazy Wow, Thanks for the detailed response! But unfortunately my client looked like this after i added the code i gave you. http://postimg.org/image/nn6638o9t/

**Comment by Logan7432** [comment]
@djbencrazy Wow, Thanks Man! This very very much helped me!!

**Comment by djbencrazy** [comment]
but do you mean transparent because I also sit in main_out me and want a wall around your field so that you can see how far you can

**Comment by Logan7432** [comment]
Yes i mean transparent so they look like on agario.wtf Cause i dont think you mentioned that in your small tutorial.

**Comment by Logan7432** [comment]
Also if you want to see my client im using go to my agario site at WestAgario.no-ip.org, it will be up for next hour.

**Comment by djbencrazy** [comment]
I 'm tired and it's night here .
am now on mobile so tomorrow I will help you around one hour or 13 hours to 14 hours

**Comment by Logan7432** [comment]
@djbencrazy Sounds Good.

**Comment by djbencrazy** [comment]
@Logan7432 it is the wall around the game and also the transparent virus
main_out.js =
**search this**
wHandle.setNames = function (arg) {
        showName = arg
    };
**place it under this**
wHandle.setVirusTrans = function (arg) {
        virussaydam = arg
    };
	wHandle.setKoseGoster = function (arg) {
        kosegoster = arg
    };

**search this**
else {
                    this.movePoints();
                    ctx.beginPath();
                    var d = this.getNumPoints();
                    ctx.moveTo(this.points[0].x, this.points[0].y);
                    for (c = 1; c <= d; ++c) {
                        var e = c % d;
                        ctx.lineTo(this.points[e].x, this.points[e].y)
                    }
						
                }

**place it under this**
if (virussaydam && this.isVirus) { //XXX
                            ctx.globalAlpha = 0.6;
				}

**search this**
showMass = false,
**place it under this**
kosegoster = false,
virussaydam = false,

**search this**
if (drawLine) {
            drawLineX = (3 * drawLineX + lineX) /
                4;
            drawLineY = (3 * drawLineY + lineY) / 4;
            ctx.save();
            ctx.strokeStyle = "#FFAAAA";
            ctx.lineWidth = 10;
            ctx.lineCap = "round";
            ctx.lineJoin = "round";
            ctx.globalAlpha = .5;
            ctx.beginPath();
            for (d = 0; d < playerCells.length; d++) {
                ctx.moveTo(playerCells[d].x, playerCells[d].y);
                ctx.lineTo(drawLineX, drawLineY);
            }
            ctx.stroke();
            ctx.restore()
        }
				// border -->
**place it under this**
if (!kosegoster) {
		if (showDarkTheme) {
		ctx.strokeStyle = '#ffffff';
		}
		else
		{
		ctx.strokeStyle = '#FF0000';
		}
		ctx.lineWidth = 10;
		ctx.lineCap = "round";
		ctx.lineJoin = "round";
		ctx.beginPath();
		ctx.moveTo(leftPos,topPos);
		ctx.lineTo(rightPos,topPos);
		ctx.lineTo(rightPos,bottomPos);
		ctx.lineTo(leftPos,bottomPos);
		ctx.closePath();
		ctx.stroke();
		}


game.hbs=
**search this**
<label><input type="checkbox" onchange="setChatHide($(this).is(':checked'));">chat uitschakelen</label>
**place it under this**
<label><input type="checkbox" onchange="setKoseGoster($(this).is(':checked'));">muurlijn uitschakelen</label>
<label><input type="checkbox" onchange="setVirusTrans($(this).is(':checked'));"> Virus Trans</label>

**Comment by Logan7432** [comment]
@djbencrazy I cant find this
<label><input type="checkbox" onchange="setChatHide($(this).is(':checked'));">disable chat</label>
In my mainout.js.

**Comment by MastaCoder** [comment]
@Logan7432 game.hbs

**Comment by djbencrazy** [comment]
@logan7432 locate the file game.hbs

**Comment by Logan7432** [comment]
Ok thanks ill try it out

**Comment by Logan7432** [comment]
Im sorry but i have no clue where the game.hbs is can you please guide me to it?

**Comment by Logan7432** [comment]
http://www.mediafire.com/download/jtkciefbfa2bkd0/Client.zip This is my client if this helps at all.

**Comment by Logan7432** [comment]
@djbencrazy You seem good at estracting code or coding something in that another site has. Would you be able to help me get the Winner thing that pops up when you go on the server and it says something like "Congrats, (playername)" I looked over the code and its called the winnersdiv but everything i try and add it to my code it wont work and it would be nice to get some help for that.

**Comment by djbencrazy** [comment]
@Logan7432 I 'll see what I can do for you . I will test on my own server . for I am working on changes.
I will look. to create codes

**Comment by djbencrazy** [comment]
@logan7432 game.hbs which is not client but somewhere in the server search there again

**Comment by Logan7432** [comment]
@djbencrazy https://i.imgsafe.org/0d72f3d.png This is what i want to add to my server really bad. If you can figure out how to add this to my client that would be amazing!

**Comment by Logan7432** [comment]
@djbencrazy Any updates on this or ideas? Thanks
