### ISSUE TITLE
Problem with client cell mass URGENT!

### ISSUE THREAD

**Issue by mayed505** [CigarProject/Cigar#223]
If your cell mass is more than 22500 you get bigger than the screen and you can't zoom out just like Ogar is there a way not to get forced to limit player mass before getting automatically splitted.??!!!??

**Comment by MastaCoder** [comment]
playermaxmass in the gameserver.ini

**Comment by mayed505** [comment]
@MastaCoder but I don't want to limit my client mass you should do it and fix this lazy thing

**Comment by MastaCoder** [comment]
> is there a way not to get forced to limit player mass before getting automatically splitted.??!!!??

...?
