### ISSUE TITLE
background lines

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#224]
Hi,
i would like to remove completely the lines like in the picture attached ... i don't want lines 
at all .... only white background 
any help please?
thank you
![lines](https://cloud.githubusercontent.com/assets/6823974/14610999/76077102-0590-11e6-83cf-cc9fb800ad3e.png)

**Comment by Logan7432** [comment]
yeah, i would want something like this also.

**Comment by MastaCoder** [comment]
This is more preference stuff which can be changed in the main_out.js.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
