### ISSUE TITLE
Cigar For Slither.io

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#227]
That would be awesome if we could make a cigar client and server but for the new thing Slither.io! I think it would be possible and make the game have some awesome features that the main one dosnt like chat, Chat was one of the best features added in cigar that agar.io dosnt have.

**Comment by mys** [comment]
Do You have any sources? It would be a pain to make it from scratch :\

**Comment by mayed505** [comment]
Here [https://github.com/PlitherProject/Plither](url)  and here [https://github.com/circa94/JSlither](url)

**Comment by mayed505** [comment]
@mys

**Comment by mayed505** [comment]
@Logan7432 i was gonna ask that yesterday but i was too shy to say it since they would say " ITS TOO HARD"

**Comment by mayed505** [comment]
@mys if you need to make a client one Plither is the right choice if you want a server JSlither is the right one but its kinda weird to play. so combine those?

**Comment by Logan7432** [comment]
I don't really like pitcher though because you can't customize the way the site looks and it's just way to hard to use, and for some reason when I hosted pither I could only type in localhost and it would work, when I used my up it didn't even though I forwarded the ports.

**Comment by mayed505** [comment]
@Logan7432 the owner of that one is still in development!

**Comment by Logan7432** [comment]
Still

**Comment by Logan7432** [comment]
dosnt matter how long it will take i think we can do it!

**Comment by MastaCoder** [comment]
I am waiting for one to be completely done and I can include the client with it.

**Comment by Logan7432** [comment]
@MastaCoder What do you mean? For a server to completely be done?

**Comment by Logan7432** [comment]
If you can do a early release for the client please so i can customize and edit it? And if you haven't started on it please make it in html and java script so i can use on a web server hosting site. Thanks

**Comment by mayed505** [comment]
@Logan7432 he will do it just like cigar its better means = faster connecting to direct server just like slither.io
