### ISSUE TITLE
Cigar, cant change start Title.

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#228]
Hello, so i basically wanna make my own private server. I wanna change the "Cigar" when you are at the start to what i want. I dont know how to, i have searched the files but couldn't find anything.
https://gyazo.com/4653e39be405905e8c4929bc65b27934

**Comment by ItzLevvie** [comment]
https://github.com/CigarProject/Cigar/blob/master/server/web/views/game.hbs#L13

**Comment by CalvinDKHD** [comment]
Thank you!

**Comment by ItzLevvie** [comment]
..

**Comment by ItzLevvie** [comment]
try now

**Comment by MastaCoder** [comment]
https://github.com/CigarProject/Cigar/blob/master/server/web/views/game.hbs#L13

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
