### ISSUE TITLE
Issue with multiple servers!

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#229]
I get an error when i try making multiple servers/regions
this is what i put in the "masterserver.ini" - https://gyazo.com/a60a68856de1a3197fb6170ec7ab694a

And this is the error - https://gyazo.com/d0d6b8fcafb61f2aacb1981f217856ab
and it generates a new Config. fks, "gameserver2.ini".

**Comment by MastaCoder** [comment]
The stats port in gameserver2.ini is the same.

I am not giving personal help with much as I am very busy with all my other projects for the upcoming months.
