### ISSUE TITLE
Skin upload FIX

### ISSUE THREAD

**Issue by peteracs** [CigarProject/Cigar#234]
Hey, you have an error in this file:

Cigar/server/web/app.js

Line 175 : if (fieldname == 'avatar'  

This should be if (fieldname == 'fileToUpload'

since the uploads.html <input type="file" name="fileToUpload" id="fileToUpload">

BTW Skin works well except you use capital letter, for example if I upload cell.png it works but if I upload Cell.png it doesn't work although my name is Cell.

Space also doesn't work, special characters neither. If you could fix the capital letter problem there would be good, I have a server where people upload Skin even though I warn them no special character, they upload the name containing space or capital letter. Otherwise it works fine. Thank you.

**Comment by mastah7991** [comment]
` var skinName = this.name.toLowerCase();`
should be  
`var skinName = this.name;`
in client/main_out.js

**Comment by MastaCoder** [comment]
Added to beta repo.
