### ISSUE TITLE
throw new TypeError('"callback" argument must be a function');

### ISSUE THREAD

**Issue by ArnoldoFreitas** [CigarProject/Cigar#235]
![image](https://cloud.githubusercontent.com/assets/8689989/15060901/8cff29c2-1305-11e6-99ac-ea303ceab6a5.png)

**Comment by peteracs** [comment]
what is your node version ?
type node-v

**Comment by ArnoldoFreitas** [comment]
v6.0.0

**Comment by peteracs** [comment]
I'm running it on 4.4.3 and it works fine. The reason I mentioned node version because I think I saw this kind of error before and after I changed node version it disappeared. But I might be wrong. Are you using those bat files ? start_gameserver or start_masterserver

**Comment by ArnoldoFreitas** [comment]
Yeah, both gives me the same error

**Comment by MastaCoder** [comment]
Error should be resolved in the beta repo: https://github.com/ItzLevvie/Cigar
