### ISSUE TITLE
My Server is in another language?!

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#238]
Title says it, i wanna change it to english.
Picture : https://gyazo.com/b4b1873b07889f88114e51389e6123b1

Look at leaderboard and Mass. it says Ranglista and Pontszam

**Comment by mayed505** [comment]
Redownload the main_out or " client" folder.

**Comment by CalvinDKHD** [comment]
I cant because i got a fix thats in main_out, where do i change the language?

**Comment by mayed505** [comment]
@CalvinDKHD its all in the main_out just hold  Control+f then search those words and replace them its that simple for send me the main_out.js and i will do it for you.

**Comment by CalvinDKHD** [comment]
Worked! Thanks!

**Comment by mayed505** [comment]
NP :D im always helping other people...
