### ISSUE TITLE
Multiple Regions error.

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#239]
This is my setup in "masterserver.ini" -  https://gyazo.com/4f6a19d9198f9ffd0018d3f12d898b84
This is the error - https://gyazo.com/a329bb51e70dc955453e34a23dee6322

**Comment by mayed505** [comment]
Close Skype and go to gameserver.ini and change stats port from 1601 or 1600 to 1603

**Comment by mayed505** [comment]
Should fix the problem :+1:

**Comment by CalvinDKHD** [comment]
Nope, cuz i disable that port on skype and i need my skype meanwhile having the server open.

**Comment by CalvinDKHD** [comment]
I didnt have to do the skype thingy, just change the port. Thanks!

**Comment by mayed505** [comment]
np im always helping instead of mastacoder

**Comment by MastaCoder** [comment]
:dancers:
