### ISSUE TITLE
Skins not working

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#240]
Hello i put a skin into the skins folder and when i use the selected name the skin just doesnt appear on the player.

**Comment by mys** [comment]
the skin name has to be listed here
https://github.com/CigarProject/Cigar/blob/master/client/main_out.js#L1244

**Comment by CalvinDKHD** [comment]
still not working, i did it.
https://gyazo.com/fe8a255f734d40b2f7eed078a598c394
The file it self is LPCLAN.png    its not LPCLAN.png.png

**Comment by mys** [comment]
maybe try lower case

**Comment by CalvinDKHD** [comment]
Works! THANKS!
