### ISSUE TITLE
the server physics are WAY to outdated

### ISSUE THREAD

**Issue by Agarian** [CigarProject/Cigar#242]

**Comment by CalvinDKHD** [comment]
Yeah i agree, i want to be able to tricksplit and such.

**Comment by Agarian** [comment]
try https://github.com/AJS-development/Ogar-unlimited even though miniclip broke it ATM

**Comment by mys** [comment]
is it possible to merge differencies?

**Comment by Agarian** [comment]
idk

**Comment by CalvinDKHD** [comment]
I tried merging them, but all i get is errors.
