### ISSUE TITLE
Can i merge the new ogar with cigar? 

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#246]
I wanna do this because cigar physics are soooooo outdated, you cant tricksplit etc.
but in the new ogar you can. when i try replacing the files it comes with errors.

**Comment by mys** [comment]
What repository do You merge with? Can You share links?

**Comment by CalvinDKHD** [comment]
Just Ogar, because they have good physics, they can t split etc. Or Ogar Unlimited. Ogar best though.

**Comment by CalvinDKHD** [comment]
Ogar - https://github.com/OgarProject/Ogar
Ogar Unlimited - https://github.com/AJS-development/Ogar-unlimited

**Comment by Agarian** [comment]
actually ogar unlimited has premium skins :P

**Comment by CalvinDKHD** [comment]
Nice, but i just need a proper server where ppl can trick split etc. so i wanna merge ogar and cigar

**Comment by Agarian** [comment]
its not possible.

**Comment by ItzLevvie** [comment]
There you go https://github.com/ItzLevvie/Cigar

**Comment by Agarian** [comment]
doesnt work levvie, page doesnt load

**Comment by Lukkez** [comment]
@ItzLevvie Thanks, worked, FINALLY :+1:

**Comment by Agarian** [comment]
how it worked for you??

**Comment by Lukkez** [comment]
Idk, i'm just using Koding

**Comment by Lukkez** [comment]
And, i do npm install again on the folder

**Comment by Agarian** [comment]
not fair, i get

main_out.js:2161 Uncaught TypeError: Cannot read property 'cloneNode' of null
http://127.0.0.1:88/img/background.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://127.0.0.1:88/img/split.png Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Agarian** [comment]
IT DOENT WORK ON KODING OR EVEN C9

**Comment by Agarian** [comment]
running files gives me
"Could not find nodejs! Please run "apt-get install nodejs" & "apt-get install npm" to install it."
and doing 
"apt-get install nodejs" or "apt-get install npm"
gives this
"E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?"

**Comment by Agarian** [comment]
am i talking to myself? lol

**Comment by Agarian** [comment]
omfg forget it

**Comment by m-byte** [comment]
@Agarian: here is a video for people just like you: https://www.youtube.com/watch?v=KxVSSIXZYzI Although it is about his channel and not an open source project, the concept still applies.

**Comment by Lukkez** [comment]
@Agarian Do you want the fix? just use the original Cigar main_out.js, np

**Comment by Lukkez** [comment]
Will be some bugs, but all will be working correctly, the only bug i find is the background, the zoom isn't the correct, so will bug

**Comment by Agarian** [comment]
Id like the fix

**Comment by CalvinDKHD** [comment]
Ok, cool. Ill try it when i am home. If it works i will be releasing my server soon. Please dont close this Issue.

**Comment by polmp** [comment]
ItzLevvie method works perfectly, but now it isn't working chat. How I can disable it?

**Comment by CalvinDKHD** [comment]
Look it doesnt work, its port fowarded on 0 and on gamserver1.ini it says 1600 
https://gyazo.com/008c44a347cbad30f04a8c8410f6ffc9

**Comment by mayed505** [comment]
@CalvinDKHD you port forward 0 for stats only go to masterini and put where gameserver port to 0

**Comment by CalvinDKHD** [comment]
Ok, done Thanks!

**Comment by Lukkez** [comment]
@Agarian Do you want to use this with Ogar-unlimited? i found how

**Comment by Agarian** [comment]
yes please

**Comment by MastaCoder** [comment]
@ItzLevvie You *have* to make a pull request for that! Just fix the glitching background on load and we are good to go :+1:

**Comment by Agarian** [comment]
That is the scramble coords/minimaps thing that causes that

**Comment by Agarian** [comment]
why cant i use this on c9.io?

**Comment by Lukkez** [comment]
@Agarian Client port = 8080, game server ports, 8081 and 8082 ;)
