### ISSUE TITLE
Error Cigar, linux.

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#248]
Hello i am getting this error.
https://gyazo.com/9151bd2c361a8d6230011d25c643bbe1
Anyone know how to fix?

**Comment by ItzLevvie** [comment]
Run it using root privileges.

**Comment by CalvinDKHD** [comment]
Itz Levvie, thanks for answering quick. But i dont have root privileges. Ill get it from my host. Well, ill try.
BTW: this is the site agarextreme.ml

**Comment by CalvinDKHD** [comment]
IT will be up when i fix this issue.

**Comment by CalvinDKHD** [comment]
Please add me on skype : calvin.leonhardt. I am using filezilla. I gave the files all the perms i think.

**Comment by Roken120** [comment]
you have error because your have already start sever is a bug on node uninstall and reinstaller cigar is a better solution my skype for more help : emres120
Sorry for my bad english

**Comment by MastaCoder** [comment]
You *need* root to use Cigar. How else would you have access to ports.
