### ISSUE TITLE
Welcome Chat Message

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#249]
Could we implement something into the server so when someone joins the server it will say a colorful welcome message like "Welcome To My Server!"  in the chat or something, but so it just says that to that person that joins not to everyone else on the server.

**Comment by mys** [comment]
I have some concept to achieve this. Will try to implement because this is needed in my own project

**Comment by Logan7432** [comment]
@mys Yeah, and it dosnt seem like it would be that hard to implement compared to most of the stuff in this.

**Comment by djbencrazy** [comment]
normally this should happen that you have to be docement in chat.js.
I'll figure this out later.
I've been here a person helped to find something.

**Comment by MastaCoder** [comment]
I can add this later this week if I ever have time.

**Comment by Logan7432** [comment]
@MastaCoder  Thanks it would be a small but useful feature!

**Comment by mayed505** [comment]
@Logan7432 i loved the idea and i started to hack cigar servers like a boss with bots :)

**Comment by Logan7432** [comment]
@mayed505 Uh, what do you mean hack the servers?

**Comment by Logan7432** [comment]
@MastaCoder What is the estimated time for this to be implemented?

**Comment by MastaCoder** [comment]
@Logan7432 Couple months. I'm very very busy these next few months due to school.

**Comment by MastaCoder** [comment]
Cigar is now client only.
