### ISSUE TITLE
Upload Skins Error

### ISSUE THREAD

**Issue by eevaqueen** [CigarProject/Cigar#250]
Hello,
Please i need help with Upload Skins,when i try to upload any skin less than 2mb and size small like 100x100,I got this error ?uploaderr=unknown any idea how to fix that?,by the way i don't use port 88,is this the cause?
Thanks

**Comment by mastah7991** [comment]
https://github.com/CigarProject/Cigar/issues/234

**Comment by eevaqueen** [comment]
Thank you it works:).
