### ISSUE TITLE
Server Lag

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#253]
Im not sure why but all of a sudden im getting large amounts of server lag making me and all the other player stutter and im not sure what the issue is. Any Ideas?

**Comment by eevaqueen** [comment]
I didn't have lag,but server keep crashing every 2h without restart!

**Comment by MastaCoder** [comment]
This is due to server with bad latency or just a weak server. @eevaqueen Can you screenshot the error message?

**Comment by eevaqueen** [comment]
@MastaCoder so what is the normal requirement vps for cigar?,because i used same vps for ogar without problem!

**Comment by Logan7432** [comment]
@MastaCoder Im not sure what the problem is... My internet running the server is top of line and it never use to do this before. I also re downloaded the server it it still wont run so i dont know what the problem is... its probably my pc idk... ill do some more research.

**Comment by mys** [comment]
@Logan7432 check out ram usage. Maybe there is a bug and it overflow so restarts :|

**Comment by Logan7432** [comment]
@mys the server dosnt restart it just stutters really bad like theres a high ping or something....
