### ISSUE TITLE
For ITZLevvie

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#254]
@ItzLevvie, what about the bugs? i saw much bugs on your version and like every 1 hour it crash :S with "split is not defined"

**Comment by eevaqueen** [comment]
same here every 2h server crash without restart i need help too  :(.

**Comment by Logan7432** [comment]
Huh, that dosnt happen to me.

**Comment by Lukkez** [comment]
Logan, send your main_out.js?

**Comment by MastaCoder** [comment]
Error should be resolved in the beta repo: https://github.com/ItzLevvie/Cigar
