### ISSUE TITLE
What is the  client who the another famous agario clones use?

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#255]
What is the  client who the another famous agario clones use?, like agario.sx, agarw.com, agarabi.com agarz.com and more, i just wanted to get some code and make a good client... :/ i never find, if someone find a vid about them or download links i will give a huge
# THANKS

**Comment by Logan7432** [comment]
@Lukkez Most of those popular agario sites created there own clones in HTML5 and javascript and didnt use any client someone else made. Lucky for you i made my cigars client and coded it very heavy, and I wouldnt mind sharing my site files with you would like me to. If you accept i will also help you set it up if you would like me to.

**Comment by eevaqueen** [comment]
@Logan7432 if you server is up can you hlep me with linux ubuntu,to make server restart with crontab ? cuz my command doesn't work.

Thank you!

**Comment by Logan7432** [comment]
@eevaqueen Sorry, I use windows not linux.

**Comment by eevaqueen** [comment]
@MastaCoder 
the hole game just froze and you can not move the cell,there is no any error message showing!,just press F5 to fix that.

**Comment by Logan7432** [comment]
@eevaqueen Open a new issue for this, the issue dosnt have anything tot do with that  problem

.

**Comment by Lukkez** [comment]
@Logan7432 You could help me?

**Comment by Logan7432** [comment]
@Lukkez Yes, i can give you the client i use and tell you how to modify it, and i can also tell you how to make the server work with my client.

**Comment by mayed505** [comment]
@Lukkez  you wanna have a look at this https://agario.biz/privacy.txt

**Comment by Logan7432** [comment]
@mayed505 Whats that for?

**Comment by mayed505** [comment]
@Logan7432 this says that @Lukkez was talking about was using cigar server and ogar-client together.

**Comment by mayed505** [comment]
@Logan7432 https://gyazo.com/8b5ef830d5fca7149d5ba0b368832ca4
