### ISSUE TITLE
On a certain server when typing in chat server crashes!

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#256]
https://gyazo.com/bd29301c296ec43dd6322318fdc0f4ff

Thats the error, so basically the server crashes if i write in chat on a specific server, but not on the others.

**Comment by CalvinDKHD** [comment]
I fixed it, dont worry.

**Comment by MastaCoder** [comment]
Error should be resolved in the beta repo: https://github.com/ItzLevvie/Cigar
