### ISSUE TITLE
Lag and hang every 20sec!

### ISSUE THREAD

**Issue by eevaqueen** [CigarProject/Cigar#258]
Hello,
I need help as title say the game hang and lag every 20sec!,after server stable for 30min all is ok without problem,then when we go to 45min game start to lag and hang alot also the ram usage have a alot of free ram! and still laggg every 20 or 15sec bad lag make you can't move the cell.

Please help.
Thanks.

**Comment by CalvinDKHD** [comment]
it could be your CPU aswell, you have to take into a count that the host or the PC might not be fast enough. Your wifi/ethernet could be the problem, but if it runs smoothly the first 20 minutes it is not that likely to be your wifi.

**Comment by eevaqueen** [comment]
@CalvinDKHD 
Thank you can you tell me the requirement vps for cigar?

**Comment by eevaqueen** [comment]
I found the problem that cause big lag,but i can't fix it,it happen every 20 sec without reason here is the image
http://prnt.sc/b4g9va
any idea to fix that ?
Thanks!!!!!!!!!!

**Comment by CalvinDKHD** [comment]
I run my server - agarextreme.ml on a dedicated host.

**Comment by eevaqueen** [comment]
I found the problem was in start_masterserver.sh just fixed it with start_gameserver.sh.
now all is ok :).
