### ISSUE TITLE
Error! I made a new gamemode, changed the port.

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#260]
this is the issue / https://gyazo.com/8d88aaa8c33bddfc26f9af3df27f96b3

Title says it.

**Comment by eevaqueen** [comment]
@CalvinDKHD can you tell me,your vps you use?,because i have lag with my vps,and i dont know what type vps to use.
Thank you

**Comment by CalvinDKHD** [comment]
Ok i fixed the issue, i run it on a dedicated host btw.
