### ISSUE TITLE
Adding adsense. < PLS HELP

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#261]
Title says it, i have around 120 people on my servers daily.

**Comment by MastaCoder** [comment]
Add the code to game.hbs?

**Comment by Logan7432** [comment]
Whats your server? WOuld like to check it out.

**Comment by CalvinDKHD** [comment]
agarextreme.ml

**Comment by mayed505** [comment]
To my study of cigar bots I relized those aren't real players they are bots or maybe they are stupid because I know how bits works dude.

**Comment by CalvinDKHD** [comment]
No xD they are not bots. They are real players.

**Comment by Logan7432** [comment]
How do you get all these players?  Also, @mayed505 There real people. To use adsence i think you have to add the code onto your site.

**Comment by mayed505** [comment]
@Logan7432  he advertized his website to N♥A Clan and SR

**Comment by Logan7432** [comment]
@mayed505 How do you do that?

**Comment by CalvinDKHD** [comment]
I know the owner of many clans.
