### ISSUE TITLE
Admin approved for skins 18+

### ISSUE THREAD

**Issue by eevaqueen** [CigarProject/Cigar#263]
Hello,
There is no way to make Admin approved for skins?,because some players upload porn and 18+ skins also I can't control this,any idea how to fix that? without closing upload section.
Thank you.

**Comment by tveloper** [comment]
You can make it so that you approve before uploading, but there isn't any automated solution for this.

**Comment by eevaqueen** [comment]
@tveloper 
Thank you can you tell me how to approve it before uploading?.

**Comment by tveloper** [comment]
Make the script to upload it to a separate folder, than move the images to the 'skins' folder if you want the skin..

**Comment by eevaqueen** [comment]
@tveloper 
Thank you.
