### ISSUE TITLE
Is Cigar Multi threaded?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#264]
Is Cigar Multi threaded? My pc has 8 cores in it. And it seems cigar runs on only 1 core! I want it to use all.

**Comment by ItzLevvie** [comment]
use jxcore

**Comment by CalvinDKHD** [comment]
jxcore?

**Comment by eevaqueen** [comment]
@CalvinDKHD 
 JXcore
Swiching fomr node to JXcore, JXcore is faster, multitreaths and bether memory managment for long hour running prodjects. Please see JXcore for more info.
https://github.com/jxcore/jxcore/blob/master/doc/INSTALLATION.md

**Comment by MastaCoder** [comment]
Solved.

**Comment by Logan7432** [comment]
Wow, this helps.
