### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by RelTakeover** [CigarProject/Cigar#266]
The chat not working on cigar of ItzLevvie

**Comment by ItzLevvie** [comment]
This is because i've not implemented it yet on my version. If you want chat, you'll have to code it in or use the official Cigar for now.

**Comment by CalvinDKHD** [comment]
ItzLevvie if you mean ogar + cigar i can fix the error. If you make the masterserver.ini make the new config for a server the error will happen. Just use a generated config from Cigar. And if you want to make a 2nd server copy that and rename it and change settings!

**Comment by MastaCoder** [comment]
I've fixed it.
