### ISSUE TITLE
How to Run Ogar on Cigar's Client

### ISSUE THREAD

**Issue by KrulYuno** [CigarProject/Cigar#270]
Hi I'm new to Github and programming. Agar.io won't allow private servers anymore so, how can I run Ogar on Cigar's Client. Trying to figure it out but I can't. I need help....

**Comment by CalvinDKHD** [comment]
You will have to merge the latest ogar and cigar. Ask ItzLevvie.

**Comment by KrulYuno** [comment]
OK Thanks. :)

**Comment by KrulYuno** [comment]
Now I have no IDEA where I can find him...

**Comment by MastaCoder** [comment]
https://github.com/ItzLevvie/Cigar | Currently the only working one.
