### ISSUE TITLE
ItzLevvie - When are you going to implement chat?

### ISSUE THREAD

**Issue by darknight99x** [CigarProject/Cigar#273]
@ItzLevvie 

I really like your independent update to Cigar, as it's not as buggy and broken as this one's version.

But, I really would like to have a chat with your version, do you know when you'll implement the chat on?

**Comment by ItzLevvie** [comment]
I'll reimplement it in the next couple of days.

**Comment by darknight99x** [comment]
Okay sounds great, thank you @ItzLevvie !

**Comment by Logan7432** [comment]
I dont see any differences between this one and ItzLevvies verson.

**Comment by Logan7432** [comment]
what are the differences?

**Comment by Logan7432** [comment]
@ItzLevvie Why when i use your version of cigar my cpu usage becomes super high and the server becomes unplayable?

**Comment by Logan7432** [comment]
@ItzLevvie Heres a video of what it looks like [](https://youtu.be/0TRQKhh_mp4) I even switched to my high end pc to run it and had the some problem.

**Comment by darknight99x** [comment]
@Logan7432 

ItzLevvie inplemented smooth splitting in his version.
