### ISSUE TITLE
Creating a server in console

### ISSUE THREAD

**Issue by JandyCZ** [CigarProject/Cigar#276]
Hello, cant create server usinc command Create. Always gives me an error "Invalid Region"

**<0>**create regionname 2
**[Master]** Invalid region name!

If I want to add a server, it gives me invalid IP (case IP:PORT), or again invalid region (case IP PORT).

Thanks for help

**Comment by MastaCoder** [comment]
I'll look into it.

**Comment by MastaCoder** [comment]
Cigar is now client only.
