### ISSUE TITLE
How to add minions?!

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#277]
Hello Cigar!
So i want to know how to add minions, like ogar unlimited has. command - minion [ID] [amount]
Is this possible?
has anyone made a script?

**Comment by MastaCoder** [comment]
This could possibly be tried to be added through @ItzLevvie's version, however, that version is not fully complete yet.

**Comment by Bagsio** [comment]
do you will send me beta of cigar with minions? :*
