### ISSUE TITLE
How to add new mode from Ogar-unlimited to Cigar?

### ISSUE THREAD

**Issue by eevaqueen** [CigarProject/Cigar#278]
Hello,
I would like to add new mods from Ogar-unlimited to Cigar,any idea what files need to change on Cigar to make mod work?
Thanks.

**Comment by CalvinDKHD** [comment]
Hey, this will work. I am trying to add minions from unlimited but get an error.

**Comment by CalvinDKHD** [comment]
Not really, maybe try merging them.

**Comment by eevaqueen** [comment]
@CalvinDKHD 
Can you tell me how to merging?,because i got error when i using Ogar-unlimited on Cigar files!
Thank you

**Comment by CalvinDKHD** [comment]
Ok, its because the files are different. Ask ItzLevvie He/She merged ogar and cigar successfully - https://github.com/ItzLevvie/Cigar    < Thats Ogar and Cigar merged.

**Comment by eevaqueen** [comment]
@CalvinDKHD 
thank you also I saw your server agarextreme.ml , can you tell me how you made instant merge ?
Thank you again!.

**Comment by ItzLevvie** [comment]
Change ```playerRecombineTime = 30``` to ```playerRecombineTime = 0```

**Comment by eevaqueen** [comment]
@ItzLevvie 
Thank you i do that before,but the problem is when the cell become bigger the merge become slow and doesn't merge instant.
Can you tell me why?
Thanks.

**Comment by Lukkez** [comment]
@CalvinDKHD What host did u used?

**Comment by CalvinDKHD** [comment]
I am using a dedicated host.

**Comment by eevaqueen** [comment]
why no one trying to help ?
@CalvinDKHD 
@MastaCoder 
@ItzLevvie 
Thank you i do that before,but the problem is when the cell become bigger the merge become slow and doesn't merge instant.
Can you tell me why?
Thanks.

**Comment by CalvinDKHD** [comment]
eevaqueen, it because you now need to set the merge time to 0 or -10 i think.
