### ISSUE TITLE
How to add new command?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#279]
Hey i have been trying to add minions from ogar unlimited to ItzLevvie's version and Cigars.
but i get this error - https://gyazo.com/1eeecaf4f9e422927ea5907ca505e327

I think i add it correctly - https://gyazo.com/4651d3fd2f16de8b5fc96b69a129e785

And i add all the files etc their AI - https://gyazo.com/fb5d0f21c4e38500f709363be344497a
MinionLoader etc.

Please help!

**Comment by MastaCoder** [comment]
Pretty sure there is much more than that. Look through the code a bit more.

**Comment by CalvinDKHD** [comment]
Yes maybe, but i dont know. I am not that good at this.....
