### ISSUE TITLE
Big update soon, project dead for some weeks.

### ISSUE THREAD

**Issue by MastaCoder** [CigarProject/Cigar#285]
This is going to be long, but I will keep it as short as I can. For the upcoming weeks, I have myself very busy with school. I'm trying to be a 90 student, so my projects outside of school are pretty much lower priority at the moment. I haven't updated Cigar or possibly any of my other projects for a couple weeks now due to this. Once my summatives and exams are over, I can come back to work with all my projects. My number one priority would be finishing the abs0rb.me v2 update that I worked on for a couple months now, then come back to Cigar and do some adjustments to it.

As most of you have seen, @ItzLevvie was kind enough to merge the official Ogar with Cigar and use the new features from Ogar in Cigar. Now I have had around 10 minutes to play with it just a couple days ago and I haven't had much more time doing more testing to find smaller bugs or crashes. I did make a pull request with some quick changes I found to make and make it better, however I don't think it is stable enough to be "publicly" released. However, you can still get your hand on it at the following link https://github.com/ItzLevvie/Cigar.

I hope everyone understands why no answers are being given and why I haven't done much these weeks. So please refrain from opening or responding to issues until I am back.

Thanks everyone!

**Comment by eevaqueen** [comment]
@MastaCoder Thank you so much,I hope the adjustments include new ogar and Ogar-unlimited mods,also the pop slpit :).

Thank you again :heart:

**Comment by MastaCoder** [comment]
bumb to the top

**Comment by CalvinDKHD** [comment]
Thank you! You take all the time you need.
And 1 question, will you release the abs0rb.me source?

**Comment by MastaCoder** [comment]
@CalvinDKHD I am planning to make a separate program that contains some of the things from abs0rb.me, but that won't be for a long time. As for the client, it has far too much information and backside all around the code to be developed straight into the a client.

**Comment by MastaCoder** [comment]
Cigar is now client only.
