### ISSUE TITLE
serverTeamingAllowed variable does not work. (ItzLevvie's Modification)

### ISSUE THREAD

**Issue by darknight99x** [CigarProject/Cigar#286]
serverTeamingAllowed set to 0 does not function at all.
No changes.

I really need it as people are complaining about teamers.

**Comment by MastaCoder** [comment]
Should start an anti-team mass losing function. Not sure if it works yet as I haven't had time to test it.

**Comment by darknight99x** [comment]
Well it doesn't make a player lose mass for teaming. It just doesn't work, at least on ItzLevvie's version.

**Comment by MastaCoder** [comment]
I'll test it out.

**Comment by MastaCoder** [comment]
Cigar is now client only.
