### ISSUE TITLE
how add more servers ?

### ISSUE THREAD

**Issue by RelTakeover** [CigarProject/Cigar#287]
WHAT CONFIGURE FOR ADD SERVERS ? 

FFA1 , FFA2 , EXPERIMENTAL1 , ETC

**Comment by RelTakeover** [comment]
HEEEEEEELP MEEEE PLSS

**Comment by MastaCoder** [comment]
https://github.com/CigarProject/Cigar/blob/master/masterserver.ini

**Comment by RelTakeover** [comment]
must be attached with the index of the combined cms and how?


my masterserver :+1: 

serverIP = 127.0.0.1
serverPort = 89
gameserverPort = 8080
updateTime = 60
regions = {"FFA": 1, "Experimental" : 1}
// To add more regions, add a comma and paste the following thing, like the following: = null


I put on index.html of my cms web:

 <div class="form-group">
                <input id="nick" style="background-color: #D3D4D4; border-radius: 0px;" class="form-control" placeholder="Nick" maxlength="45"/>
                <select id="gamemode" style="border-radius: 0px; background-color: #D3D4D4;" class="form-control" onchange="setGameMode($(this).val());" required>
                    <option  selected value="FFA">FFA</option>
					<option  selected value="BIG">Big</option>
                  
                </select>
                <br clear="both"/>
            </div>

but it takes me to the same server !!!!!!!!!!!!
