### ISSUE TITLE
how add more servers ?

### ISSUE THREAD

**Issue by RelTakeover** [CigarProject/Cigar#288]
HOW ADDD MULTIPLE SERVERS ? PLS HELP ME

**Comment by ItzLevvie** [comment]
Edit your masterserver.ini

**Comment by RelTakeover** [comment]
must be attached with the index of the combined cms and how?


my masterserver :+1: 

serverIP = 127.0.0.1
serverPort = 89
gameserverPort = 8080
updateTime = 60
regions = {"FFA": 1, "Experimental" : 1}
// To add more regions, add a comma and paste the following thing, like the following: = null


I put on index.html of my cms web:

 
                <input id="nick" style="background-color: #D3D4D4; border-radius: 0px;" class="form-control" placeholder="Nick" maxlength="45"/>
                <select id="gamemode" style="border-radius: 0px; background-color: #D3D4D4;" class="form-control" onchange="setGameMode($(this).val());" required>
                    <option  selected value="FFA">FFA</option>
					<option  selected value="Experimental">Experimental</option>
            
                    <option value=":experimental">Experimental</option> -->
                </select>
              

>>>>> but it takes me to the same server !!!!!!!!!!!! <<<<<<< !!!!!!!!!!!!!!!!

**Comment by RelTakeover** [comment]
PLS HELP ME

**Comment by RelTakeover** [comment]
I NEED CONECT INDEX.HTML WITH SERVERS OF MASTERSERVER.INI , currently both buttons, lead me to the same server

**Comment by RelTakeover** [comment]
how i need help

**Comment by MastaCoder** [comment]
Please stop creating duplicates of already topics. If you need help with your own client we don't help here, the master server writes it to the main master server file. You will have to figure out how to edit your own client in a method which you find best.
