### ISSUE TITLE
WHERE INDEX.HTML ?

### ISSUE THREAD

**Issue by RelTakeover** [CigarProject/Cigar#289]
WHERE IS THE INDEX?

![image](https://cloud.githubusercontent.com/assets/19374681/15629451/8c2ff444-24ef-11e6-9707-8186609c4594.png)

**Comment by darknight99x** [comment]
It's not index.html.

In server > web > views > game.hbs and layout.hbs

are the files you need to edit the menu.
They're both in CSS and HTML so you should be good. Just open them in Notepad++ or something else you prefer.
