### ISSUE TITLE
how add more servers ? IT IS LIKE ABS0RB ( BUTTON )

### ISSUE THREAD

**Issue by RelTakeover** [CigarProject/Cigar#290]
IT IS LIKE ABS0RB
 , HOW DO IT?
> <select

 id="gamemode" class="form-control" onchange="checkSelector(); if ($(this).val() == 'otherRequest') { customServer(); } else { setServer(); setserver($(this).val()); ServerPlayers(); ServerTotal(); }" required="" style="background-color: #1abc9c; color: white;">
<option disabled="" selected=""> Default Gamemodes:</option>
<option id="server1" value="69.195.128.162:1501">- FFA</option>
<option id="server2" value="69.195.128.162:1502">- Teams</option>
<option id="server3" value="69.195.128.162:1503">- Experimental</option>
<option disabled=""> Crazy Gamemodes:</option>
<option id="server4" value="69.195.128.162:1511">- Crazy</option>
<option id="server5" value="69.195.128.162:1512">- Crazy Insta</option>
<option id="server6" value="69.195.128.162:1513">- Crazy Mega</option>
<option id="server7" value="69.195.128.162:1514">- Crazy Rainbow</option>
<option id="server8" value="69.195.128.162:1515">- Crazy Plus</option>
<option id="server9" value="69.195.128.162:1516"> - Crazy Giant</option>
<option disabled=""> Minigame Gamemodes:</option>
<option id="server10" value="69.195.128.162:1531">- Hunger Games [CLOSED TEMP]</option>
<option disabled=""> More Gamemodes:</option>
<option value="94.212.26.90:44411"> European Test Server by Jara [ONLINE]</option>
<option value="otherRequest"> Custom Server</option>
</select>

>

**Comment by MastaCoder** [comment]
The IP's are in the values and ```setserver()``` just sets it to the IP..?

**Comment by RelTakeover** [comment]
The buttons lead me to the same server

**Comment by RelTakeover** [comment]
not understood "SETSERVER" pls help me mi agar is agarx.cf

**Comment by darknight99x** [comment]
You can go to masterserver.ini and add them in...

Once you add them in as the example that is provided with the file by default, they'll start on the next server startup, then you can edit their configs to your liking.
