### ISSUE TITLE
Adding adsense.

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#292]
Hello! my server has been very successful and i would really love to add adsense since i am paying for a host. I am able to use it now but the problem is that the code is in JS and not HTML which game.hbs is. And when i try adding it too index.html, like this > https://gyazo.com/eadca339b336a1931b4694d56ea710f4

This error occurs > https://gyazo.com/5c6b83f96a3f41f7354a9e1a278a8f7f
If you know where to place the code, or how i do this then please help me!

Thank you! / From Calvin

**Comment by ItzLevvie** [comment]
Add it in layout.hbs or game.hbs

**Comment by CalvinDKHD** [comment]
No because the code is in Javascript. SO it doesnt work.

**Comment by ItzLevvie** [comment]
"No because the code is in Javascript. SO it doesnt work." It's because you're adding it in the wrong place. For it to work, you'll have to add it in layout.hbs which can be found at https://github.com/CigarProject/Cigar/blob/master/server/web/views/layout.hbs

**Comment by mayed505** [comment]
@CalvinDKHD the error occurs because you are adding html into index.js and index.js is javascript and NOT HTML.

**Comment by CalvinDKHD** [comment]
ItzLevvie, thank you. But where do i add it in? In the layout.hbs

**Comment by ItzLevvie** [comment]
Maybe after https://github.com/CigarProject/Cigar/blob/master/server/web/views/layout.hbs#L17?

**Comment by mayed505** [comment]
@ItzLevvie to add adsense he has to go to game.hbs and add it under the play button.

**Comment by ItzLevvie** [comment]
@mayed505 yeah or you can do that ^

**Comment by mayed505** [comment]
@ItzLevvie yes i owned a server just like @CalvinDKHD and earned like $300 but school exams came and i had to stop with it :)

**Comment by CalvinDKHD** [comment]
mayed505, please send me a line. Because i added it under the play button but no ads appear.

**Comment by CalvinDKHD** [comment]
It doesnt even work if i add it to the layout.hbs as ItzLevvie said.

**Comment by eevaqueen** [comment]
@mayed505 how adsense work with you and Cigar is illegal ?,because it is not original ogario,it is not against adsense terms?.

**Comment by CalvinDKHD** [comment]
This is not adsense, its an alternative. But when i try adding code into game.hbs or layout.hbs the ads dont appear.

**Comment by ItzLevvie** [comment]
I'm not sure about Chitika but Google Adsense works fine for me.

**Comment by CalvinDKHD** [comment]
Well google adsense is not accepting me. :/  
Please add me on skype - calvin.leonhardt

**Comment by eevaqueen** [comment]
@CalvinDKHD 
the code will work with you fine when you use iframe tag try it now.

**Comment by CalvinDKHD** [comment]
eevaqueen, how do i use iframe?

**Comment by eevaqueen** [comment]
@CalvinDKHD you said you using alternative "like what?"  right?,they will give you code with iframe tag.

**Comment by CalvinDKHD** [comment]
I am using Chitika as the adsense thing.

**Comment by CalvinDKHD** [comment]
They give me this code
`<script type="text/javascript">
  ( function() {
    if (window.CHITIKA === undefined) { window.CHITIKA = { 'units' : [] }; };
    var unit = {"calltype":"async[2]","publisher":"CalvinDK","width":550,"height":250,"sid":"Chitika Default"};
    var placement_id = window.CHITIKA.units.length;
    window.CHITIKA.units.push(unit);
    document.write('<div id="chitikaAdBlock-' + placement_id + '"></div>');
}());
</script>
<script type="text/javascript" src="//cdn.chitika.net/getads.js" async></script>`

**Comment by eevaqueen** [comment]
@CalvinDKHD it will not work,it must to be iframe tag not script

**Comment by CalvinDKHD** [comment]
Yes but can you help me adding a script in?
skype - calvin.leonhardt

**Comment by CalvinDKHD** [comment]
yllix seems good, but the signup page is blank.

**Comment by eevaqueen** [comment]
@CalvinDKHD 
https://yllix.com/en/publishers/

**Comment by CalvinDKHD** [comment]
Look / https://gyazo.com/0062125f4967ea5fa8d222759d91cee0

**Comment by eevaqueen** [comment]
@CalvinDKHD it's work fine with me,try another browser or use proxy.

**Comment by mayed505** [comment]
@eevaqueen i had google adsense on cigar and there was no problems with it at all. google will accept your account if your leave cigar 24/7 in the reviewing process atleast.

**Comment by eevaqueen** [comment]
@mayed505 great but question please.how long did you use adsense with cigar?
THank you.

**Comment by mayed505** [comment]
@eevaqueen it took me 3 or 5 cant remember.

**Comment by CalvinDKHD** [comment]
Umm, I tried 4 times to get into adsense but they wont accept me. Its on 24/7.

**Comment by CalvinDKHD** [comment]
Eevaqueen, look - https://gyazo.com/9e3889804f2cd0714ef418fd7d7b2832
So now when i add it to my real server, that was just a local test. Will i make money?

**Comment by mayed505** [comment]
@CalvinDKHD its because you HAVENT added the code you must add the ads code first before submitting a review

**Comment by CalvinDKHD** [comment]
No No, i added the code and everything.

**Comment by eevaqueen** [comment]
@mayed505 he didn't use google adsense.

@CalvinDKHD yes you will earn money but use banner 300x250 is better,also if you can use google adsense will be better,because they pay more than yllix

**Comment by mayed505** [comment]
@CalvinDKHD you need real people = money and dont use leaderboard banner for ads it looks bad

**Comment by eevaqueen** [comment]
@mayed505 do you mind to showcase your website?

**Comment by CalvinDKHD** [comment]
I wanna showcase mine when i added ads on it.

**Comment by mayed505** [comment]
@eevaqueen im too lazy :P

**Comment by CalvinDKHD** [comment]
Ok, done - agarextreme.ml

**Comment by CalvinDKHD** [comment]
eevaqueen, i added the site. When will i make money?

**Comment by eevaqueen** [comment]
@CalvinDKHD great try to make new ad tag and disable "Display layer ads" "No",you will see your account balance start after 1 day,also you can wait 7 day to see the final estimates,but again google adsense pay much more than yllix.

**Comment by CalvinDKHD** [comment]
Yeah i now, but adsense aint accepting me. Thanks!

**Comment by RelTakeover** [comment]
my server with adsense http://agarx.cf

**Comment by CalvinDKHD** [comment]
RelTakeover PLEEASEE! Help me to change the start thingy!!! like the menu. PLEASE ILL PAY YOU!
skype - calvin.leonhardt
