### ISSUE TITLE
How to change interface?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#293]
Hey guys, so far i have only changes it like this - https://gyazo.com/360270aa54e7ca57f2f735df6adc6705

I want to like make it like  this - http://agario.city/

**Comment by CalvinDKHD** [comment]
Anyone have a game.hbs?

**Comment by RelTakeover** [comment]
is my agar , contact me on fb , https://fb.com/theeduardosebastian
