### ISSUE TITLE
Prevent Lag?

### ISSUE THREAD

**Issue by ElMay0r** [CigarProject/Cigar#294]
Hi, i hosted my website www.Agar.blue whit this emulator, and i dont know why is the game so lagged out, I use 8GB RAM and 500Mbps speed.

Can any one play the game and check whats making it lagg?

I also use an HTML website on IIS not the server one.

**Comment by RelTakeover** [comment]
Yo también tengo un agar con 16gb de ram tienes medio de contacto para preguntarte algo?

**Comment by RelTakeover** [comment]
Mi fb fb.com/theeduardosebastian

**Comment by MastaCoder** [comment]
How many cores? Where is the site hosted?

**Comment by ElMay0r** [comment]
Here's the System: http://i.imgur.com/tQsG12R.png .

Any solution for the lag?

**Comment by darknight99x** [comment]
Yes @MastaCoder I seem to have this issue too.
I don't believe it's server lag, it's just the optimization for the client itself is very unstable and laggy.
WIth my 3.8ghz 8core processor and GTX 750 Ti graphics card should be plenty enough to handle the client, even with Smooth Rendering setting on, it seems to have massive FPS drops, I believe main_out.js needs some optimizations.

**Comment by MastaCoder** [comment]
No it's server sided.

**Comment by darknight99x** [comment]
@MastaCoder It can't be.

I'm running a very strong host as well, running just NodeJS on it, and it's only using 5% of the total CPU.

In fact I only see people on my server complain of n FPS drop.
I have 7-15 people on a day with no problems.

**Comment by MastaCoder** [comment]
FPS drops would be cutting frames. If the cells are slowing down, then that is server sided.

**Comment by CalvinDKHD** [comment]
No, its because Cigar only runs on 1 core. I tried JXCore but it just makes it lag more.

**Comment by darknight99x** [comment]
CalvinDKHD, do you have Skype? I wish to talk to you about Agar.io

**Comment by CalvinDKHD** [comment]
Darknight, yes i do. Its CalvinDK.
skype  - agarextreme.ml

**Comment by CalvinDKHD** [comment]
Yes i do, its CalvinDK
its - calvin.leonhardt

**Comment by Niall7459** [comment]
Had no problems running on a ubuntu server 2 core 4gb ram 

Even still the server only uses 15 mb of ram with absolutley no lagg.
