### ISSUE TITLE
JXCore

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#296]
Hey i installed JXCore and ran the server on it.
But there is still A LOT of lag. There is less lag with node. Do i need to enable it somehow?
Can someone please send me a start_masterserver.sh configured for JXCore?

Thanks!

**Comment by MastaCoder** [comment]
That's probably based on the server. Try doing some troubleshooting with different servers. I haven't had much time to test it on my dedicated server with hundreds of players yet.
