### ISSUE TITLE
For ItzLevvie, ERROR!

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#298]
PLS HELP!

I have been getting this error > https://gyazo.com/9849c20db62ecf90d798989554c39552
something to do with the packethandler!

**Comment by darknight99x** [comment]
You might have a map size for your server that is too big to handle, or one of your players in game has gotten to big for your server to handle, can I see your gameserver config?

**Comment by CalvinDKHD** [comment]
Yes

**Comment by CalvinDKHD** [comment]
https://www.mediafire.com/?xjfn04adl4z7amk

Those are all the configs.

**Comment by darknight99x** [comment]
Nothing seems out of the ordinary here...
Who's version of Cigar are you using?
@MasterCoder 's or @ItzLevvie 's ?

**Comment by CalvinDKHD** [comment]
ItzLevvie's

**Comment by CalvinDKHD** [comment]
FOUND ISSUE! if i do !crash in game chat, the server crashes o.o

**Comment by ItzLevvie** [comment]
Doesn't happen to me on the latest version of my Cigar.

**Comment by CalvinDKHD** [comment]
Ok, umm its an error with the packet handler. I tried !crash again. Nothing. And i updated the packet handler etc.

**Comment by CalvinDKHD** [comment]
Now its happening again.

**Comment by CalvinDKHD** [comment]
Working. Levvie add meh on skype pls  - agarextreme.ml
