### ISSUE TITLE
Chat gone!!

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#300]
Hello so i was just playing on my server and i refreshed and the server chat was gone!
https://gyazo.com/b86c2d72ae59f08f36fab1903142c2e1

When i actually refresh i quickly see the chat here ||
https://gyazo.com/adb6d21bc05a09978204e38093843b74

Any idea?
If so pleas help, PS this is ItzLevvie's version.

**Comment by MastaCoder** [comment]
Custom client changes, can't help with that. Sorry!
