### ISSUE TITLE
Gallery with Pages

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#316]
I am having a problem with gallery, i have 500+ skins (really) and when a person enter on the gallery (one time) use more than 100mb on secs, my bandwidth isn't unlimited and i don't want the server get blocken, so i wanted to know how to make a gallery with pages, like [Happyfor.win](http://happyfor.win/galery.php) have. That's a problem.

**Comment by MastaCoder** [comment]
You'd have to find a way to separate them using image numbers so that each page will have a number of them. I can do this, but will not try because I don't really need it and won't help much for Cigar. 

You can try researching some about PHP and see how you can seperate them.

**Comment by Lukkez** [comment]
I have find that:

``
$trtrack = 0; 
       $total = mysql_num_rows($results); 
       $images_per_page = '2'; 
       $pages = ceil($total/$images_per_page); 
       if(intval(!isset($_GET['page'])) or intval($_GET['page'])  > $pages) 
       { 
       $page = '1'; 
       } 
       else 
       { 
          $page = intval($_GET['page']); 
       } 
       $start = $page * $images_per_page - 1; 
       if($page == '1') 
       { 
          $start = '1'; 
       } 
       $end = $start + $images_per_page; 
       echo "$start<table style=\"width:100%\">\n<tr>"; 
       $imgtrack = '0'; 
       while($result = mysql_fetch_array($results)) 
       { 
         ++$imgtrack; 
        if($imgtrack >= $start and $imgtrack < $end) 
        { 
         if($trtrack == '2') 
         { 
            echo "</tr>\n<tr>"; 
            $trtrack = '0'; 
         } 
         ++$trtrack; 
         $photographer = $result['photographer']; 
         $ship = $result['ship']; 
         $location = $result['location']; 
         $datetaken = $result['datetaken']; 
         $datetaken = date('l d M Y',$datetaken); 
         $pichref = $result['pichref']; 
         $bigpichref = $result['bigpichref']; 
         echo "<td style=\"width:50%; text-align:center\"><a href=\"javascript:imgviewer('$bigpichref')\"><img src=\"$pichref\" alt=\"Photo Gallery Picture\" class=\"pg_img\" /></a><div style=\"text-align:center\">$ship<br />$location, $datetaken<br /><i>$photographer</i></div></td>\n"; 
       } 
      } 
      echo "</tr></table>"; 
      }  

``
But i don't know how to implement it to Cigar. Always give errors

**Comment by Lukkez** [comment]
I finished to find and i make one, 
![image](https://cloud.githubusercontent.com/assets/15003706/15987381/b269235c-2ffc-11e6-8fd3-899a961075aa.png)
There's the progress and is mostly made by php

**Comment by RelTakeover** [comment]
como lo haz hecho ?
