### ISSUE TITLE
Multithread

### ISSUE THREAD

**Issue by Alontrle** [CigarProject/Cigar#319]
I have JX Core and when I run it on multiple threads it opens the server 4 times and breaks all commands, Can someone help me make a jx core startup .sh for linux using 8 cores.

**Comment by CalvinDKHD** [comment]
try launching gameserver.sh instead.
I think it would run all the servers on seperate consoles.

**Comment by Alontrle** [comment]
That's not what we want we still need the master server. We are looking for a way to run all the servers on 8 cores.

**Comment by MastaCoder** [comment]
Won't be multi thread until something happens in an update.
