### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#32]
hi,
is there another website to test the game i have tested this http://eureland.me
is there another ?
thanks

**Comment by Eureka22** [comment]
@matrixreal Actually eureland.me is for testing agar-clone. What do you mean by another?

**Comment by matrixreal** [comment]
i want to test it on mobile but it lag so i'm searching about new website ...

**Comment by Eureka22** [comment]
@matrixreal Oh,well, you can test that on your localhost. Then there should be no lagging.

**Comment by matrixreal** [comment]
@Eureka22 thanks a lot you are magic
but can i install a full server on my home pc and friends come to play (not protected server)
what you suggest to me ?
ogar or cigar ?

**Comment by m-byte** [comment]
The fundamental difference between Ogar and Cigar:
Cigar will always work with custom clients, Ogar will always work with the official site. As far as I know, at the moment Cigar does not support the official client, while Ogar prevents custom clients from connecting.

**Comment by matrixreal** [comment]
officiial site ? you mean agar.io ?

**Comment by m-byte** [comment]
Yes

**Comment by matrixreal** [comment]
i don't want agar.io because i can't use it on mobile it always redirect to the play store to download the official app

**Comment by m-byte** [comment]
In that case, you can't use Ogar.

**Comment by matrixreal** [comment]
ok i just start from begining
i download lastest cigar-master extract and lunch the cigar.exe
it gives me the screenshoot below
when i lunch localhost:88 the game run (the game server is listen to 88 right ?)
![cigar](https://cloud.githubusercontent.com/assets/6823974/8877980/c3c72338-3228-11e5-98a8-1d85f06572da.png)
my ip adress is 88.167.14.2 
when i try to lunch my ip 88.167.14.2 or 88.167.14.2:88 not work 
my router is listening to 88 (prouf is if just for example i install xampp and start apache server and put just simple index.html or index.php) it run from local or public from 88.167.14.2:88
so the problem is where ?

**Comment by m-byte** [comment]
Most likely, your firewall is blocking the connection.

**Comment by matrixreal** [comment]
my firewall is disabled :(
just question ... i have to redirect the port of my router to 88 (like the one for cigar ?)

**Comment by m-byte** [comment]
Yes, you have to redirect port 88 for the master server and port 450 for the first game server. (Check your `masterserver.ini` to make sure these are correct)
If you have more game servers, check their ports in the corresponding `gameserver.ini`.

**Comment by matrixreal** [comment]
@m-byte 
that's okay i will give it a test
as the screenshoot i have posted before
i have to redirect 88 and 451 ? right ?

**Comment by m-byte** [comment]
Yes, forgot to check the screenshot. Port 88 and 451 should be enough.

**Comment by matrixreal** [comment]
thats okay ..
what about ip's ? master ip etc ? do i need to change them to my ip too?

**Comment by ElMay0r** [comment]
www.agar.blue   But when ny player get big his game crash (freeze)
