### ISSUE TITLE
Running different servers independently?

### ISSUE THREAD

**Issue by darknight99x** [CigarProject/Cigar#321]
Instead of using the multiverse feature.

Is there anyway I can run more than one server independently from each other?

I have alot of players, and running a multiverse on one core of my four core processor is making alot of lag.

I wish to spread the four servers I have on different cores, utilizing them more efficiently.
Is there anyway to do this?

**Comment by RelTakeover** [comment]
my agar have this ... agario.city

**Comment by RelTakeover** [comment]
agario.city

**Comment by MastaCoder** [comment]
@darknight99x Run different processes of Cigar, should throw you onto different cores.
