### ISSUE TITLE
Multithread

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#323]
So i have been around and asked a lot of people about this, they say "Use JXCore". And yes. I tried but it opens 4 of the same consoles. If someone can please send me a start_masterserver.sh edited for JXCore please do so, i need a .SH one!

**Comment by darknight99x** [comment]
Strange, mine works fine with JXCore, can I see your start script?

**Comment by CalvinDKHD** [comment]
uhh, can you please send me yours. Cause i am on the phone and i cant now.

**Comment by CalvinDKHD** [comment]
But i switched Node with jx so like if it said node index.js i did jx index.js

**Comment by darknight99x** [comment]
I don't know the issue is man, I did the same as you did, and it's working fine for me ;v

**Comment by CalvinDKHD** [comment]
But pls send me your script! .SH pls

**Comment by MastaCoder** [comment]
JXcore won't just fix it, we have to make it work in clusters and all together on different cores which will require work.
