### ISSUE TITLE
What do i do?

### ISSUE THREAD

**Issue by aqweqwel123** [CigarProject/Cigar#325]
[SyntaxError: Unexpected token o]
[Master] Master Server started at port port 88
/root/server2/Cigar/server/index.js:94
    in_.question("<" + selected.server.realmID + ">", function(str) {
                                      ^

TypeError: Cannot read property 'realmID' of undefined
    at prompt [as _onTimeout] (/root/server2/Cigar/server/index.js:94:39)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by darknight99x** [comment]
Your version of NodeJS is too high.

Uninstall NodeJS, go to the official website,

>  https://nodejs.org/en/

 and install 4.4.5

**Comment by aqweqwel123** [comment]
already downgraded to 4.4.5 and im still getting this error

**Comment by darknight99x** [comment]
> [SyntaxError: Unexpected token o]
[Master] Master Server started at port port 88

Delete your Master server ini and let it generate a new one, 
it's best to use @ItzLevvie 's version for this.

**Comment by codetrr** [comment]
![asdasd](https://cloud.githubusercontent.com/assets/20255765/16540331/16909736-408b-11e6-9d88-02ea0c8e9cbf.png)
