### ISSUE TITLE
How to hide IPS?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#326]
https://gyazo.com/59d2016b62a0ff3c9f9fc5fdcb0f7ee2
those are what i wanna hide

**Comment by darknight99x** [comment]
I don't think there is a way to hide those.

**Comment by CalvinDKHD** [comment]
What, there should be. Because someone made bots for my server!

**Comment by MastaCoder** [comment]
Open up main_out.js and search up "Connecting", then you should find the console.log that is outputting the information.
