### ISSUE TITLE
I want "Pick Skin" system, don't you?

### ISSUE THREAD

**Issue by FlexibleSwift** [CigarProject/Cigar#327]
Hi! Is it possible to add pick skin system instead of writing the name of it?
Im gonna try to code something for it.

Thanx

**Comment by MastaCoder** [comment]
I am adding this quite soon ;)

**Comment by Lukkez** [comment]
I have one simple, if want just reply here

**Comment by FlexibleSwift** [comment]
Yes please my skype is mirtre3

**Comment by CalvinDKHD** [comment]
Lukkez, please add me aswell! - calvin.leonhardt on skype.
Or gmail c4lvinx@gmail.com

**Comment by FlexibleSwift** [comment]
@Lukkez My skype is mirtre3, would love to get that!

**Comment by FlexibleSwift** [comment]
@Lukkez ...

**Comment by FlexibleSwift** [comment]
bump
