### ISSUE TITLE
Can anyone help with multi threading?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#333]
So here, i have been stuck with this a looooooooooooooooooong time.
I cant get JXCore too work. Agario.City is using Node and is somehow multithreading.
I would pay someone to help me get this done! THANKS, I have 8 cores, i want the server too use all of those cores not only 1.

my skype - calvin.leonhardt

**Comment by Barbosik** [comment]
you cannot utilize multithreading from node.js

**Comment by CalvinDKHD** [comment]
yes, its called a child process. dunno how to use it.
