### ISSUE TITLE
Error running Cigar!

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#334]
Title says it, here is the error -
https://gyazo.com/a374aff89e3f7ec4c50dd5b5cc313032

The masterserver.ini is in the server folder, it is!

**Comment by ItzLevvie** [comment]
Should be outside the server folder, I believe.

**Comment by CalvinDKHD** [comment]
lemme try

**Comment by CalvinDKHD** [comment]
FOUND THE ISSUE! so for some reason it thinks the masterserver.ini and the gameservers.ini is in  server. I actually redownloaded your version and it did the same. But i was using JX CORE thats why probably!

**Comment by CalvinDKHD** [comment]
Works now!
