### ISSUE TITLE
How too edit game screen?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#335]
So i wanna edit this - https://gyazo.com/980f7ee806c5b070c478599818371f9f
but not this - https://gyazo.com/0a525cdbd338fce62397f8a315ed7006
So like where the leader board is

Hope you understand!

**Comment by FlexibleSwift** [comment]
Uhm, why?

**Comment by FlexibleSwift** [comment]
Ask me first lol

**Comment by FlexibleSwift** [comment]
in main_out.js

**Comment by CalvinDKHD** [comment]
Ok
