### ISSUE TITLE
Admin should get a specific color in the chat!

### ISSUE THREAD

**Issue by FlexibleSwift** [CigarProject/Cigar#336]
Instead of regular white color in chat or leaderboard, the admin should be highlighted with a specific color or animation! 

Is this possible? 
Thanks.

**Comment by FlexibleSwift** [comment]
bump

**Comment by MastaCoder** [comment]
Client sided, yep. Just haven't tried it yet.

**Comment by FlexibleSwift** [comment]
I'd love to if you could take a look at it and make a code for it ;)

**Comment by Barbosik** [comment]
https://github.com/Barbosik/MultiOgar/issues/120
