### ISSUE TITLE
Can addbot [amount] be used too test server lag?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#339]
Hey so i added about 500 bots on a server with the command addbot and NOOOO LAGGG no SLOMO, i multithreaded it. I just gotta know if that can be used? is it the same as if i put 500 real people on there?

**Comment by FlexibleSwift** [comment]
I think so, becuase its still the same.

**Comment by FlexibleSwift** [comment]
It is still "players"

**Comment by MastaCoder** [comment]
But they are not real connections. Your server is not being filled with bandwidth connections from different places in the world.
