### ISSUE TITLE
add 6 server error

### ISSUE THREAD

**Issue by codetrr** [CigarProject/Cigar#340]
I can only add 5 game server ...
if more than 5 server bot does not move and the player can not take food or player. is there is wrong with setting masterserver.ini?

===============================
masterserver.ini
===============================
serverIP = 192.168.137.1 //adhoc sharing ip
serverPort = 88
gameserverPort = 1500
updateTime = 60
regions = {"FFA": 1, "Teams": 1,"Experimental": 1, "Tournament": 1,"Hunger Games": 1, "Zombie Teams": 1}
// To add more regions, add a comma and paste the following thing, like the following: = null
// regions = {"FFA": 1, "Teams": 1}

===============================
![aaa](https://cloud.githubusercontent.com/assets/20255765/16540302/3703fc16-408a-11e6-90f9-62f8b41ae234.png)

![asdasd](https://cloud.githubusercontent.com/assets/20255765/16540309/783e92f4-408a-11e6-9591-c4a69b2dc2f0.png)

**Comment by ItzLevvie** [comment]
You've to change the stats port

**Comment by codetrr** [comment]
i have change all stats port

**Comment by ItzLevvie** [comment]
try disabling the stats port

**Comment by codetrr** [comment]
ok thanks :D... my mistakes

**Comment by codetrr** [comment]
how add line border?

**Comment by MastaCoder** [comment]
main_out.js I think, someone made a post about this a while ago, don't remember what issue though.
