### ISSUE TITLE
cells spawn ?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#344]
Hi,
is it possible to add spawn small triangle with the small cells that we can eat it will be more funny?
something like the picture attached?
thank you
(and please where can i change the color of the virures ?)
![cig](https://cloud.githubusercontent.com/assets/6823974/16858007/09a1962c-4a24-11e6-8769-5ab0c892d530.png)

**Comment by tveloper** [comment]
To change the virus' color, you have to change the client (`main_out.js`).

**Comment by matrixreal** [comment]
thanks a lot can you tell me wich lines please ? i did not find it since this morning

**Comment by matrixreal** [comment]
@tveloper 
@all
any reply please?

**Comment by matrixreal** [comment]
@tveloper 
i did not find howto change the virus color? sad

**Comment by ZfsrGhS953** [comment]
Open up Virus.js in entity and change ( function Virus() ) It should look like: ( for blue color)
this.cellType = 2;
    this.spiked = 1;
    this.fed = 0;
    this.color.r=0;
this.color.g=0;
this.color.b=255;

**Comment by matrixreal** [comment]
@ZfsrGhS953 
ohhhh thanks a lot you saved me

i would like to ask you last thing please
how can i remove completely the lines in the map ?

**Comment by ZfsrGhS953** [comment]
For this, you need to change the client. (main_out.js) Find "drawGrid()" and remove it. Remove the line that says "drawGrid();". Don't remove the line "function drawGrid() {"

**Comment by matrixreal** [comment]
@ZfsrGhS953 
thanks a lot you saved me
cause i'm working on html5 version for mobile and the grid lines are heavely for that so i decided to remove them completely
so by removing this line , that make them just invisible or don't draw them at all ?

**Comment by matrixreal** [comment]
@ZfsrGhS953 
here is my old code
  function drawGrid() {
    ctx.fillStyle = showDarkTheme ? "#111111" : "#F2FBFF";
    ctx.fillRect(0, 0, canvasWidth, canvasHeight);
    ctx.save();
    ctx.strokeStyle = showDarkTheme ? "#000000" : "#000000";
    ctx.globalAlpha = .2;
    ctx.scale(viewZoom, viewZoom);
    var a = canvasWidth / viewZoom,
      b = canvasHeight / viewZoom;
    for (var c = -.5 + (-nodeX + a / 2) % 50; c < a; c += 50) {
      ctx.beginPath();
      ctx.moveTo(c, 0);
      ctx.lineTo(c, b);
      ctx.stroke();
    }
    for (c = -.5 + (-nodeY + b / 2) % 50; c < b; c += 50) {
      ctx.beginPath();
      ctx.moveTo(0, c);
      ctx.lineTo(a, c);
      ctx.stroke();
    }
and i remove what you say
so now the code is 
  function drawGrid() {
  }
but now the dark mode is not working
is there a solution please ?
thanks

**Comment by ZfsrGhS953** [comment]
Then you should leave 3 first lines in the function, like this:
function drawGrid() {
ctx.fillStyle = showDarkTheme ? "#111111" : "#F2FBFF";
ctx.fillRect(0, 0, canvasWidth, canvasHeight);
ctx.save();
}

**Comment by matrixreal** [comment]
@ZfsrGhS953 
@MastaCoder 
Hi,
thanks a lot for your help
what about spawn different shapes (triangle etc ....) with cells ?
thanks a lot
