### ISSUE TITLE
I need Help ASAP!

### ISSUE THREAD

**Issue by ElMay0r** [CigarProject/Cigar#346]
Hello, 

I been using cigar since last year (I update all releases)

My server www.Agar.Blue has been targeted on a Bots (Minions) spammer, and every time they spam the Bot make my server Crash!

Here's the error that shows the console: 

> Error: Uncaught, unspecified "error" event. (reserved fields must be empty)
>     at WebSocket.emit (events.js:144:17)
>     at Receiver.onerror (C:\Users\Administrador\Desktop\Cigar-master\server\node
> _modules\ws\lib\WebSocket.js:832:10)
>     at Receiver.error (C:\Users\Administrador\Desktop\Cigar-master\server\node_m
> odules\ws\lib\Receiver.js:317:8)
>     at Receiver.processPacket (C:\Users\Administrador\Desktop\Cigar-master\serve
> r\node_modules\ws\lib\Receiver.js:191:12)
>     at Receiver.add (C:\Users\Administrador\Desktop\Cigar-master\server\node_mod
> ules\ws\lib\Receiver.js:91:24)
>     at Socket.firstHandler (C:\Users\Administrador\Desktop\Cigar-master\server\n
> ode_modules\ws\lib\WebSocket.js:774:22)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at Socket.Readable.push (_stream_readable.js:111:10)
>     at TCP.onread (net.js:536:20)

Any solution? :'(

**Comment by mohmed78980** [comment]
plez pleeeeez :( help me plez 
ElMay0r 
my email facebook https://www.facebook.com/mohmed78980
plez

**Comment by codetrr** [comment]
https://youtu.be/nqcWuiOGD98?list=PLpkWZ6MYUg3FC4QFAZvVVaerByIdwqyPV

**Comment by ZfsrGhS953** [comment]
They just added sendUint8(90) somewhere in main_out.js and now your server is crashing. Avoid using Cigar, it hasn't been updated for a long time.

**Comment by MastaCoder** [comment]
I need to fix this.

**Comment by ZfsrGhS953** [comment]
Good! Did you fix it?

**Comment by MastaCoder** [comment]
@ZfsrGhS953 This has been fixed in MultiOgar, we are now Client only. So yeah, technically fixed :)
