### ISSUE TITLE
[Error] CallBack ?

### ISSUE THREAD

**Issue by dinhduynhat** [CigarProject/Cigar#347]
![untitled](https://cloud.githubusercontent.com/assets/20450856/17161494/3acae592-53d8-11e6-83d1-8f3bc5d19e80.png)
HELP ME !!!!

**Comment by discoroveryx** [comment]
Use nodejs 4.x or 5.x version

**Comment by dinhduynhat** [comment]
but, a later version of Node.js already installed. setup will now exit, how to uninstall nodejs ?

**Comment by discoroveryx** [comment]
remove 6.x and install 4.x

**Comment by dinhduynhat** [comment]
how to remove :)) i can't find file nodejs :))

**Comment by ZfsrGhS953** [comment]
JXcore ( https://github.com/jxcore/jxcore )

**Comment by CalvinDKHD** [comment]
how do i use jxcore, i installed chakra version and in start masterserver.bat i changed node to jx still lag

**Comment by ZfsrGhS953** [comment]
use v8 version
