### ISSUE TITLE
Cigar Full ( Chatbox + Minimap )

### ISSUE THREAD

**Issue by dinhduynhat** [CigarProject/Cigar#348]
https://github.com/dinhduynhat/Agar-Ogar-Cigar-web-client

**Comment by CalvinDKHD** [comment]
So i did excatly what the youtube video did
but when i go to 127.0.0.1

its just a white screen
https://gyazo.com/d9691e3f39efd88843d5769b9bec2098

and i did edit it too 127.0.0.1 in the mainout

**Comment by Lukkez** [comment]
It doesn't show the skins how i fix that?
