### ISSUE TITLE
When server running Experimental (No connection established)

### ISSUE THREAD

**Issue by CineXMike** [CigarProject/Cigar#35]
I eddited some code to 
create: function(masterServer,split) {
        if (typeof masterServer.REGIONS[split[1]] == 'undefined') {
            console.log(masterServer.getName()+" Invalid region name!");
            return;
        } 

        var mode= parseInt(split[2]);
            
        // Adds
        masterServer.createServer(split[1],mode);
    },
After that i created an server with gamemode 2 (succesfully)
But when i click gamemode Experimental gamemode it doesnt connect

Please look into it

Ty

**Comment by m-byte** [comment]
@CineXMike The game mode settings currently are ignored.

**Comment by CineXMike** [comment]
How can i run an teams server and an experimental server???? In same region under right gamemode

**Comment by MastaCoder** [comment]
I'll try to fix this soon.

**Comment by MastaCoder** [comment]
Fixed this, well partially.
