### ISSUE TITLE
How to allow cigar too use all the ram it wants?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#350]
Title says it,

PLUS jxcore still lags...

**Comment by ItzLevvie** [comment]
Using JXCore by it's self isn't true multi-threading, and will not reduce lag that much. For true multi-threading you'll have to implement clusters on your server.

**Comment by CalvinDKHD** [comment]
On my phone atm. But I would pay you to do this for me... my Skype:
calvin.leonhardt

Please I actually wishes money for my bday to be able to pay someone to fix
this xD
