### ISSUE TITLE
Please help as soon as possible

### ISSUE THREAD

**Issue by mohmed78980** [CigarProject/Cigar#351]
hi 
When I change the ip of the local ip 127.0.0.1:88 to the IP number of the year me so my friends can login with me, it shows me a problem in the game and I can not enter to play and I Biased In spite of the piece I got up to open Port in the modem and the firewall did not work the game and show them this problem please reply as soon as
_**# Image mistake**_: http://up.harajgulf.com/do.php?img=977742

**Comment by MastaCoder** [comment]
Port forward error.
