### ISSUE TITLE
Cigar.io Eater the ios version of Cigar is out

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#353]
Hi,
i'm happy to present you the ios Appstore version of CigarProject (Agar.io like Game)
after 6 months of work the game is out
you can check it here https://itunes.apple.com/app/id1025331871
i will be happy if you test the game on your different devices (iPhone, iPad) and report any lag , bug or suggestions
all your feed-back are welcom 
thanks

**Comment by J4awesome** [comment]
Hi,
Could I work on his game ? I used cigar before and have been programming in ios development for about 3 years.

**Comment by matrixreal** [comment]
@J4awesome 
yes of course ... you are welcome
add me on skype matrix.real

**Comment by Niall7459** [comment]
Not work ):
