### ISSUE TITLE
Players spam in chat Help!!!!

### ISSUE THREAD

**Issue by eevaqueen** [CigarProject/Cigar#354]
![rara](https://cloud.githubusercontent.com/assets/17146668/17826428/92a532b8-6625-11e6-85fa-900adfc4d5f9.jpg)
some bad players spam like this screenshot, There is no way to mute them without close holy chat with hidden chat?
need help please thanks!

**Comment by HAlexTM** [comment]
Deny these characters in the gameserver1.ini

**Comment by HAlexTM** [comment]
For a list of these characters here's a great link: http://www.fileformat.info/info/unicode/block/geometric_shapes/list.htm

**Comment by MastaCoder** [comment]
Cigar is now client only.
