### ISSUE TITLE
white screen when start to play problem ?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#355]
Hi,
some times when i'm playing on cigar and i click on play i got white screen with nothing and i need to tap esc or refresh the page to get in the game
look to the attached image
![problem](https://cloud.githubusercontent.com/assets/6823974/18065071/a169d9c4-6e32-11e6-8af5-c6e760bdeb98.jpg)

**Comment by HAlexTM** [comment]
This is caused by network problems, please check the correct port and Internet by the server

**Comment by matrixreal** [comment]
@HAlexTM
where can i check the correc ort and internet by the server ?

**Comment by HAlexTM** [comment]
The correct port is in the gameserver1.ini and in your main_out.js file
You can check the connection of the server by typing "ping -c 1 google.com" (replace -c with -n if windows)

**Comment by matrixreal** [comment]
ok thank you
but in wich line exactly in main_out.js?

**Comment by HAlexTM** [comment]
Line 8

**Comment by MastaCoder** [comment]
Cigar is now client only.
