### ISSUE TITLE
how to.. ABS0RB

### ISSUE THREAD

**Issue by arxn** [CigarProject/Cigar#358]
how to put Online Players on the index ? the same players online appear on the emulator , that appear on the index.html , how to?

like this ( say 8 players on the selector of gamemodes )

![image](https://cloud.githubusercontent.com/assets/21227214/18608999/a759c49e-7ccd-11e6-97ae-2f1cfad6422d.png)

**Comment by MastaCoder** [comment]
When you setup a server, you have an option to set the port to stats. On your client have it ajax and parse the response to anywhere you like.

I have personally removed this in the v2 update due to the fact that it causes a subtle bit of lag every update.

**Comment by arxn** [comment]
you can help me with the code in index.html ?

**Comment by MastaCoder** [comment]
?

**Comment by arxn** [comment]
you can help me with the code in index.html like abs0rb.me ( online players viewer )

**Comment by MastaCoder** [comment]
http://abs0rb.me/assets/js/players.js

**Comment by MastaCoder** [comment]
Cigar is now client only.
