### ISSUE TITLE
wss:// websockets

### ISSUE THREAD

**Issue by HAlexTM** [CigarProject/Cigar#362]
Hi, I just tried to run a https server and use it in the websocket, the result was... nothing the connection works, but no websocket is being sent (I tried even using a normal http, using express but still nothing)
Is there something that I should know? Thank you :)

**Comment by MastaCoder** [comment]
You can't use secure sockets on connections to unsecure servers. The only fix is to use MultiOgar right now as it has SSL verification on it.

**Comment by HAlexTM** [comment]
Unsecure servers? The client is on https:// (no proxy, real certificate) and I can use the same cert for the node server as the domain is the same (as I said I tested it, and the server was working, just not sending/receiving sockets)

So... what do you mean?

**Comment by MastaCoder** [comment]
Yes but use to the same cert you would need a special module set on the server that right now only MultiOgar has configured.

**Comment by HAlexTM** [comment]
Yes I saw the source and the way it uses custom methods, once I get a wifi (and not my phone's 32kb/s ahah) I'll try to implement it, thanks for sharing your knowledge

**Comment by HAlexTM** [comment]
Without opening a new issue, what is the "knownNameDict" var in the main_out.js for?

**Comment by HAlexTM** [comment]
Fun fact: I just worked on wss like... 2 hours ahahaha, they're not working.

**Comment by MastaCoder** [comment]
It's the known names for skins from what I can remember. So if you want to add skins, you need to add them to that first. But since their is a checkdir.php file, you don't need to do that.

**Comment by HAlexTM** [comment]
@MartaCoder thanks for the reply,  I was wondering if you can enable the wiki, I'd like to write some tutorial like how to add a new key and so on :)

**Comment by MastaCoder** [comment]
@HAlexTM I'll do it soon 👍

**Comment by HAlexTM** [comment]
Resolved using Cloudflare and nginx, the issue may need to stay open

**Comment by MastaCoder** [comment]
Cigar is now client only.
