### ISSUE TITLE
Skin Rotation

### ISSUE THREAD

**Issue by linkslip** [CigarProject/Cigar#363]
I would like to rotate the doge skin, in order for its eyes to always be looking at the users mouse cursor while in game. It has to be rotated for the eyes to point at the mouse cursor every time the cursor changes position. Can anyone advise where to put the ctx.rotate statement in? And any specific way to format it? I have been trying to put it in various parts around main_out.js with no prevail.

**Comment by HAlexTM** [comment]
As the server calculates the direction not by angular inclination but by x and you coordinate you need to calculate it yourself
Variables of mouse position are: posX and posY

The skin drawing is in the "DrawOneCell" function, exactly line 1411
Place an if checking if the name is doge, if leave it drawing normally (line 1478 https://github.com/CigarProject/Cigar/blob/master/client/main_out.js#L1478

(Sorry for formatting, currently working from Android)

**Comment by linkslip** [comment]
Thanks for your response @HAlexTM !
I have tried to rotate it 20 degrees just to start, to see if I can get it rotated, using the following code 
`ctx.rotate(20*Math.PI/180);`
I have tried placing it in a variety of places, including before and after line 1446, 1478, and 1521. Any more clues?

**Comment by HAlexTM** [comment]
Try to leave out these 2 .translate and place before ctx.rotate: context.save();
After ctx.drawImage: context.save();

**Comment by linkslip** [comment]
Thanks! I was able to do this!
