### ISSUE TITLE
Adding external gameservers

### ISSUE THREAD

**Issue by Niall7459** [CigarProject/Cigar#365]
How can i run client on one machine with a few gameservers locally and have the client connect to etxernal servers as well?

**Comment by HAlexTM** [comment]
If you're using the provided client on the server run
`select 0` and `add ip port region` (of course replace ip, port and region with your data)
If you're using an external client you should add the server ip and port by the main.php but this file should have some POST check (eg: give ip by region) or it would give just one IP

**Comment by Niall7459** [comment]
Hey thanks for response.

1. I get "Invalid region name"
2.

Do you have a example main.php becuase I am thinking of hosting the client externally and I have source files but I have no experience with PHP.

My current main.php is `
<?php
  echo '127.0.0.1:443';
?>`

I would like to be able to have 4 servers on 

x.x.x.x  Port 1501
x.x.x.x port 1502
x.x.x.x port 1503
x.x.x.x port 1505

and two on

willowmead.ddns.net 1501
willowmead.ddns.net 1502

I would really appreciate it if you could help.

**Comment by Niall7459** [comment]
BTW i have modified code to include the port as a url to bypass port blocking at my school using nginx.

minecraft.appletec.uk.com:1501  -> becomes
minecraft.appletec.uk.com/gameserver1501/

**Comment by Niall7459** [comment]
I changed the wsUrl in main_out.js to
`wsUrl = "ws://minecraft.appletec.uk.com:80/ncoms" + CONNECTION_URL.split(":")[1] + "/";`

It would be nice if I could specify a specify the exact URL in the masterserver regions file or in main.php on external clients

**Comment by HAlexTM** [comment]
Do you really do this at school!? Why am I still in Italy :(
Anyway, the region name is defined in the masterserver.ini and in the main.php you may do a simple random echo eg:
``` PHP
<?php
    $array = ["url1","url2"];
    array_rand(array_flip($array), 1);
?>
```

I'm not sure that is going to work on the fly as I'm writing from my phone.

Talking about the changed url, the way

**Comment by Niall7459** [comment]
I dont do it at school I do it at home and play it at school (:

**Comment by HAlexTM** [comment]
Oh, got it ahah like me but they block the connection😢

**Comment by Niall7459** [comment]
Do yuo know how I can use cigar client files with OgarUnlimited?

**Comment by HAlexTM** [comment]
The client should work with any server that is based on Ogar, just try and list here your errors (don't open a new thread)

**Comment by HAlexTM** [comment]
Edit I just remembered that Cigar serves the client by the server (I am using external files)
Here's what I did:
    - Downloaded this https://github.com/ItsVoid/agario-client
    - Replace the main_out.js
    - in the main_out.js find `.ajax` and replace the URLs (the dot with main.php, checkdir with checkdir.php)

**Comment by Niall7459** [comment]
Also staff would like to be able to see player ids, I tried adding them to the leaderboard but the number is completely different than the real player ids in playerlist

**Comment by HAlexTM** [comment]
'Cause the ID is never sent to the client

**Comment by Niall7459** [comment]
aww.

**Comment by MastaCoder** [comment]
I'll be updating the client pretty soon. Remove the server files to move onto MultiOgar and update the protocol of the client to protocol 5 :)

**Comment by MastaCoder** [comment]
Cigar is now client only.

**Comment by Niall7459** [comment]
Works perfectly, and very very good for school usage since my school even block port 443! ( I think )

So I use nginx and connect using reverse-proxy on port 80!
Theres no way they block port 80!

**Comment by HAlexTM** [comment]
They can't block the 443 port or any HTTPS website will not work ahah

**Comment by Niall7459** [comment]
Exactly, and thats right.

I swear the only ports accessible by students are 80 and 1509 (For the schools student insight  service)

**Comment by Niall7459** [comment]
Any 443 webpage fails to load. Connetion reset.

**Comment by Niall7459** [comment]
As well since my OgarServ server on port 443 was never accessable at school.

**Comment by HAlexTM** [comment]
Wow... you can't use Google, wtf is this rule!?

**Comment by Niall7459** [comment]
thinking of it.. you can.

But cant Https be on port 80 or has to be 443?

**Comment by Niall7459** [comment]
i pretty sure school uses HTTP google not HTTPS

**Comment by Niall7459** [comment]
anyway im no expert in how it works.

**Comment by Niall7459** [comment]
I might help contribute to cigar

**Comment by Niall7459** [comment]
In my cigar I made so that the Popup Gallary you can click on skin and it sets it for you. its great

**Comment by HAlexTM** [comment]
We did it months ago LOL

**Comment by Niall7459** [comment]
Yes but the <skinname> tag is hidden, since I only want the registered users to be able to get skins!

**Comment by Niall7459** [comment]
![screen shot 2017-01-03 at 10 39 46](https://cloud.githubusercontent.com/assets/9781846/21605395/f934965e-d1a0-11e6-9cca-6abef805a963.png)
And then..
![screen shot 2017-01-03 at 10 40 04](https://cloud.githubusercontent.com/assets/9781846/21605401/064196c6-d1a1-11e6-975f-dc8122e3c13b.png)

**Comment by MastaCoder** [comment]
Two things to note.

Issue with the tag thing is a user can just use inspect elements to check what the skin is being called from, so that's one issue there :)

Also about the school things, you guys are so lucky. At my school all ws connections are blocked other than damn 443. Before a couple Agar.io servers worked, now none.

**Comment by Niall7459** [comment]
I did think that, my temperarory solution was to base64 encode it. not that its very sucure anyways

**Comment by MastaCoder** [comment]
There is almost no point on encoding something if you're going to encode it client side. For those skin methods you're going to have to set it on the server with some sort of hash with the users IP or something. Just setting it on the client will never work. (Since inspect elements is such a beautiful thing.

**Comment by Niall7459** [comment]
Basically, Server PHP Encode <skinname> to base64.
Client recieve the base64 skin.
Decodes clientside as the real skinname.

I know its worthlesss.
But none of my players have discovered it...

**Comment by Niall7459** [comment]
Help Help! The school have blocked my domain??? What can I do??
I don't want to use the direct IP because its static and they could ban it..

**Comment by Luka967** [comment]
All that stuff to reach to a server and my school has all ports open...

**Comment by Niall7459** [comment]
I have fixed it by using a Dynamic IP Address with DDNS that uses nginx to proxy pass to the original server..
