### ISSUE TITLE
Client: Canvas font flickering

### ISSUE THREAD

**Issue by HAlexTM** [CigarProject/Cigar#366]
While playing everything in the canvas that is using the Ubuntu font (or other if you change it) sometimes switch to the fallback one
Eg: font = "30px Ubuntu, Arial";
for some reason it uses Arial (the fallback font)
P.S. no errors.

**Comment by MastaCoder** [comment]
Make a pull request for this so that it would be easier for your contributions to count :)

**Comment by HAlexTM** [comment]
And why did you close this? Ahah

**Comment by MastaCoder** [comment]
I can't seem to replicate this, how does it happen?

**Comment by HAlexTM** [comment]
Like every 1-2 minutes the font starts changing, this happens on 4 PC with varius versions of Google Chrome, if there is any way I can help with the repo, I'm happy to help

**Comment by MastaCoder** [comment]
I just tried it on the new update, doesn't seem to be happening anymore, can you confirm?

**Comment by HAlexTM** [comment]
I’m not able right now, I need to merge the changes on my side and this will take some time

**Comment by MastaCoder** [comment]
Alright.

**Comment by HAlexTM** [comment]
Didn't fix

**Comment by MastaCoder** [comment]
Do you have pictures or a video?

**Comment by tveloper** [comment]
![image](https://cloud.githubusercontent.com/assets/13702277/20453005/9d5a866c-ae5b-11e6-95f3-92c9d7b7153c.png)

Canvas flickering

**Comment by tveloper** [comment]
Oops, wrong issue.

**Comment by HAlexTM** [comment]
Sorry for the delay I was sleeping, I'll take a video today

**Comment by MastaCoder** [comment]
Alright! 👍

**Comment by HAlexTM** [comment]
Oh.. I forgot it... sorry ahah I'll make it

**Comment by HAlexTM** [comment]
https://youtu.be/3InrR4_J-h4 (Sorry for the 16:9 ratio)

**Comment by MastaCoder** [comment]
This has never happened to me.. Weird. If anyone else confirms this happens to me I can see what it is.

**Comment by HAlexTM** [comment]
We should write a FAQ section and a FRI (Frequently reported issues) like "If you got canvas flickering check this and this)" (😂)

**Comment by MastaCoder** [comment]
😄

**Comment by MastaCoder** [comment]
Is this still an issue?

**Comment by HAlexTM** [comment]
This is weird because it doesn't happen on my wamp installation... I'll close it for now
