### ISSUE TITLE
How to tell if the current cell is the player?

### ISSUE THREAD

**Issue by linkslip** [CigarProject/Cigar#367]
I'm trying to check if the current cell is the player, and using the userNickName variable isn't reliable because some players may have the same nickname. I have added a boolean "isUser" to the Cell prototype, but am not sure how to figure out if it is the user or not. Can anyone help?

**Comment by HAlexTM** [comment]
`.getType() == 0`

**Comment by linkslip** [comment]
What value am I supposed to pass inPlayerTracker if the current user is a player? this.pID returns 1

**Comment by HAlexTM** [comment]
I don't know what you mean because on my server is working and returns the correct pID

**Comment by linkslip** [comment]
What ID should I be looking for? For the owner to match the ID in PlayerTracker?

**Comment by HAlexTM** [comment]
Yes, the pID variable in PlayerTracker

**Comment by linkslip** [comment]
Thanks @HAlexTM , but I am still having a hard time, I apologize. I have added in all these methods, how do I access them in main_out.js ? Do I have to add the property to the bytes being sent?

**Comment by HAlexTM** [comment]
Yes, but why are you trying to send the ID? This should be server-only...

**Comment by linkslip** [comment]
My rotation code is in main_out.js, I need to make it so that the other players are not rotated in the same way that the user himself is rotated

**Comment by HAlexTM** [comment]
Got it... maybe youy should trying using `console.log()` with some Cell's variables

**Comment by linkslip** [comment]
HAlexTM I am doing that, but am trying to transfer additional variables as well

**Comment by linkslip** [comment]
HAlexTM I think you might have misunderstood the question. **I am trying to figure out if the cell is the current user.**

**Comment by MastaCoder** [comment]
There is no variable, you need to get it through a users playertracker. It has to be in a function of some sort where a cell that has done something is called through. We can't help you much since you'd need to know where you're adding the code to the server and how you're executing it.

**Comment by linkslip** [comment]
I have solved this! nodesOnScreen contains the ids of all the cells that belong to the player!
