### ISSUE TITLE
How to let food overlap each other?

### ISSUE THREAD

**Issue by linkslip** [CigarProject/Cigar#368]
Here's the thing - I am trying to change the food to be slices of fruit which have different shapes and sizes, I am having a hard time removing the borders which move around with each other because of the boundary stroke. Here is a screenshot of what it looks like now:

<img width="316" alt="screen shot 2016-10-20 at 8 24 46 pm" src="https://cloud.githubusercontent.com/assets/12027390/19585705/813c5c5e-9703-11e6-946c-0f4720906fbc.png">

See that weird distortion? How can I get rid of that?

**Comment by HAlexTM** [comment]
Please show the code you're using, currently I'm not able to help

**Comment by linkslip** [comment]
HAlexTM I have the following code after [line 1431 in main_out.js](https://github.com/CigarProject/Cigar/blob/master/client/main_out.js#L1431) to remove the background color and to remove the border:

```
                if (this.size < 29)
                {
                    this.size = 40;
                    ctx.lineWidth = 0.00001;
                    ctx.fillStyle = "rgba(0, 0, 0, 0)";
                    ctx.strokeStyle = "rgba(0, 0, 0, 0)";

                    this.name = 'watermelon';
                }
```

**Comment by HAlexTM** [comment]
Try removing this and see results (I can't currently) [main_out.js](https://github.com/CigarProject/Cigar/blob/master/client/main_out.js#L1437)
on `ctx.lineWidth = 0.00001;` try using just 0, try setting a higher size, let me know

**Comment by linkslip** [comment]
Here is what it looks like when I set it to 0:

<img width="365" alt="screen shot 2016-10-24 at 1 45 31 pm" src="https://cloud.githubusercontent.com/assets/12027390/19663321/4657fed2-99f0-11e6-92bb-522b90213c57.png">

It has a faint outline because there is some problem with rendering transparency here in HTML5, but the issue where they have a separator persists.

**Comment by linkslip** [comment]
I was able to do this by removing the "points" in drawOneCell
