### ISSUE TITLE
How to add new properties to Cell prototype?

### ISSUE THREAD

**Issue by dfiverr** [CigarProject/Cigar#369]
Hi, I would like to add new variables/properties to the Cell prototype, both on the server and on the client. How would I go about doing that? How can I send newly added variables/properties to main_out.js from Cell.js. Do I have to add them to the Cell prototype in main_out.js? Do I have to add them to the Cell prototype in Cell.js? Do I have to add them to the list of bytes being sent through sockets? If so, how would I do that?

**Comment by ZfsrGhS953** [comment]
You need to send them to the client only if they affect the appearance of the cell. So, for example if it's something like split cooldown you don't need to send it to the client.

**Comment by dfiverr** [comment]
@ZfsrGhS953 I would like to specifically add new stuff. Not just the appearance of the cell.

**Comment by ZfsrGhS953** [comment]
Add appearance of the cell to Cell.js, main_out.js and UpdateNodes.js. Everything else should be added to Cell.js only.
