### ISSUE TITLE
Updates Following

### ISSUE THREAD

**Issue by ElMay0r** [CigarProject/Cigar#37]
Is the Download Pack always updated, or we have to download the pack then add the commits updates?

**Comment by CineXMike** [comment]
download zip format (everything included.

**Comment by djoey123** [comment]
Ogar gets more updates then Cigar

**Comment by m-byte** [comment]
It's something we'll work on. Currently, my work keeps me very busy. I'll try to get to this as soon as possible, though.

**Comment by ElMay0r** [comment]
Ok, but other question, why when some one gets big he/her gets freeze and have to reload the page

**Comment by m-byte** [comment]
@ElMay0r Please open a new issue for this. It's not related to this issue.

**Comment by m-byte** [comment]
Never mind, #21 already exists.
