### ISSUE TITLE
How to make map bigger?

### ISSUE THREAD

**Issue by linkslip** [CigarProject/Cigar#372]
I've been struggling for hours to make the map bigger. Can anyone point me in the right direction?

**Comment by HAlexTM** [comment]
gameserver1.ini
```
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000
```` change 6000 to your number

**Comment by ZfsrGhS953** [comment]
Also, for sizes more than 32767, decrease borderLeft and borderTop to negative values instead of increasing borderRight and borderBottom.
