### ISSUE TITLE
Having problem when launching  the server!

### ISSUE THREAD

**Issue by ElMay0r** [CigarProject/Cigar#375]
Here is a screenshot: 

http://imgur.com/v6J4WFP

thanks,

**Comment by HAlexTM** [comment]
Of you made modifications we can't help you, if not re-download the server

**Comment by ZfsrGhS953** [comment]
Use JXcore v8 version.

**Comment by ElMay0r** [comment]
I downloaded the zip from here yesterday and got the same error

**Comment by ElMay0r** [comment]
ZfsrGhS953 

can you give me a link if you wont mind please.

**Comment by ZfsrGhS953** [comment]
https://github.com/jxcore/jxcore-release/blob/master/0311/jx_win64v8.zip

**Comment by ElMay0r** [comment]
it would work if i just download it?

**Comment by ElMay0r** [comment]
I downloaded it and still have the error

**Comment by ZfsrGhS953** [comment]
Because it's not a module for Node, you need to run Cigar using it instead.

**Comment by ElMay0r** [comment]
i did it only showed this "..." three points...

**Comment by MastaCoder** [comment]
Cigar is now client only.
