### ISSUE TITLE
How to kill a cell?

### ISSUE THREAD

**Issue by linkslip** [CigarProject/Cigar#376]
I want to kill a cell through code. How do I make it so a cell is killed, in Cell.js? Also, a separate question, how can I hook up the bottom functions (such as onConsume, onAdd, onRemove) in Cell.js?

**Comment by ZfsrGhS953** [comment]
```javascript
this.gameServer.removeNode();
```

**Comment by agariotips** [comment]
@ZfsrGhS953 Do you have skype? You seem to know ALOT about the client.

**Comment by dfiverr** [comment]
@ZfsrGhS953 I am interested in communicating with you too, send me an email (linkslips@gmail.com) I want to hire you to modify this project for me.

**Comment by HAlexTM** [comment]
Can we close this issue? It's becoming a hiring issue ahah.

**Comment by linkslip** [comment]
HAlexTM please email me as well, I am interested in you as well.
