### ISSUE TITLE
How to make a skin picking system in the .html file.

### ISSUE THREAD

**Issue by agariotips** [CigarProject/Cigar#377]
For those who have been requesting it, it's really easy to create a skin pick system.

In your HTML file, add in 
```html
<a onclick="document.getElementById('nick').value='<skinName>';document.getElementById('nick').focus()"   class="btn-danger btn btn info" role="button">Name Of Skin</a>
```

Let me explain.

the onclick getElementById will tell Main_out to get the nickname box. In this case, 'nick' is the ID of it.

The .value='<skinname>' is the thing you want the system to put in the nickname box. So i could use <kraken> or [kraken] etc.

the class= 'btn-danger btn btn info' is the bootstrap button that adds the text into the box. When you click it, it will put <kraken>. 

The text before the `</a>` is what you want the button text to have. 

Remember, you could also use images with `<img>`
Streamable video: https://streamable.com/n0s8

**Comment by MastaCoder** [comment]
Fixed in the new update, we now use <skin>.
