### ISSUE TITLE
How to make it so food never spawns on top of each other?

### ISSUE THREAD

**Issue by linkslip** [CigarProject/Cigar#379]
I want to make it so that food never spawns on top of each other. Does anyone know how I can modify it so that before I spawn a food, I make sure there is no food in that place?

**Comment by HAlexTM** [comment]
The spawn process of a Virus is what you're looking for

**Comment by linkslip** [comment]
Are viruses never spawned on top of each other ?

**Comment by HAlexTM** [comment]
They don't spawn where players are

**Comment by MastaCoder** [comment]
Cigar is now client only.
