### ISSUE TITLE
mobile lagg

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#38]
@m-byte 
thats work perfect with new update everyone should access here 88.167.14.2
but the game still lag on mobile (i have good internet)
and can you ajust joystick control on mobile and make it like original ? thanks

**Comment by CineXMike** [comment]
Here no laggs on mobile
Its on your side

**Comment by smatch999** [comment]
update your CPU cores/sockets.
No have lags on mobile.

**Comment by matrixreal** [comment]
@smatch999 
please hoow can i do it ? how can i update cores / sockets ?

**Comment by matrixreal** [comment]
@smatch999 
cpu : Intel Core i5 430M
ram : 8 gb 1066Mhz DDR3
graphics : intel hd 3000
hard drive : ssd 120 go kingstone sv300

upload 114.5 Kio/s
donwload 1031.8 Kio/s

**Comment by m-byte** [comment]
@matrixreal as far as I remember, there is an option to disable the joystick in the settings.

**Comment by matrixreal** [comment]
I dont find it .... 

Envoyé de mon iPhone

**Comment by m-byte** [comment]
@matrixreal never mind. It's something Eureka22 wrote about some time ago, but apparently he did not implement it.
