### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Gimmo** [CigarProject/Cigar#388]
setName: function(a) {
            if (this.name = a) {         <<  ???????????????????????????????????????????????
                if (null == this.nameCache) {
                    this.nameCache = new UText(this.getNameSize(), "#FFFFFF", true, "#000000");
                    this.nameCache.setValue(this.name);
                } else {
                    this.nameCache.setSize(this.getNameSize());
                    this.nameCache.setValue(this.name);
                }
            }
        },

Please explain.  I think its typo, but when I try to edit it, Cygar dies....

**Comment by HAlexTM** [comment]
When you pass it to the if you set the local name variable to a, nothing else, if you write "==" it will never work as this is the function to set the name

**Comment by Gimmo** [comment]
It's a place for conditional expression , am I wrong?

**Comment by HAlexTM** [comment]
You're not wrong but there isn't any typo

**Comment by Gimmo** [comment]
My editor hates this. I agreed with it.
