### ISSUE TITLE
Gameplay Lag (Client continusly spamming server with connect packets)

### ISSUE THREAD

**Issue by Niall7459** [CigarProject/Cigar#389]
I am experiencing some lag whilst playing. Gameplay seems to be a bit jumpy

I believe this maybe a client issue since the results from my Web Socket inspector seem to be spamming connect packets to the server continusly.

Possibly all these packets could be overloading the server?

I did not experience this with the old Cigar.
Also I am using MultiOgar server software.

![wscigar](https://cloud.githubusercontent.com/assets/9781846/20461595/c1138898-aefa-11e6-87cc-1580d7f05a72.png)

![Uploading Screen Shot 2016-11-20 at 08.20.36.png…]()

**Comment by Niall7459** [comment]
@MastaCoder

**Comment by Niall7459** [comment]
I dont think is cigar because ogar ul does the same

**Comment by MastaCoder** [comment]
Weird, I'll look into this later.

**Comment by Niall7459** [comment]
This does not seem to be too severe now.. I think it is a MultiOgar problem

works fine with MultiOgar-Edited,
