### ISSUE TITLE
No skins gallery page

### ISSUE THREAD

**Issue by MastaCoder** [CigarProject/Cigar#390]
Just remembered we need to add one, was in the old Cigar but was written through the server. Need to make it run through the webserver directly.

**Comment by dark84s** [comment]
http://prntscr.com/d9nbyt
Looking for skin on behalf of every user chrome consol
How can i fix it.

**Comment by HAlexTM** [comment]
@dark84s we are fixing the problem

**Comment by MastaCoder** [comment]
@dark84s It was already fixed in 111f7b5653206a499e35673066fa14765e322c1c

**Comment by HAlexTM** [comment]
The code will be ready in minutes

**Comment by HAlexTM** [comment]
Pull request #394

**Comment by MastaCoder** [comment]
Needs to be cleaned up a bit, but it's fine right now.

**Comment by dark84s** [comment]
Looking for skin on behalf of every user playing console
http://prntscr.com/d9o267

**Comment by MastaCoder** [comment]
@dark84s It works fine. You're not updating files properly.

![GIF](https://i.gyazo.com/9cea69dad14d4b1cb380b3ae8bda8c1a.gif)

**Comment by dark84s** [comment]
http://slitherioplay.us/tester2/   please test

**Comment by HAlexTM** [comment]
@dark84s index.html Line 23: `    <script src="assets/js/main_out.js"></script>`
Use `assets/js/main_out.js?v2`

**Comment by dark84s** [comment]
thank you

**Comment by dark84s** [comment]
Firstly the script is very nice.
It will be a final responsibility.
My old script also looks like baits.
http://prntscr.com/d9p3kj
But your clientte
http://prntscr.com/d9p37w

Looks like this server files Multiogar
Where can I fix it from the clientte.

**Comment by HAlexTM** [comment]
Am I the only who didn't understand what you said?

**Comment by dark84s** [comment]
First of all thank you for your help.
I'm sorry for my bad english.

That seems to be the bait on the client I am using.
http://prntscr.com/d9pakd

It looks like your client baits.
http://prntscr.com/d9pbdw

You can understand from the look of the baits.

**Comment by HAlexTM** [comment]
We need to find anoyher way to check the food

**Comment by MastaCoder** [comment]
@dark84s Turn on smooth render.

**Comment by HAlexTM** [comment]
Should I uoload some stock skin?

**Comment by MastaCoder** [comment]
I didn't upload many skins because it would creating a big download size for those that might not want the skins either.

**Comment by HAlexTM** [comment]
Ok in the future I'll make a zip package and I'll upload it on my webserver
