### ISSUE TITLE
Loading skins that don't exist

### ISSUE THREAD

**Issue by MastaCoder** [CigarProject/Cigar#391]
For some reason the checkdir.php doesn't seem to be working. The main_out.js is still trying to load skins that don't exist.

![IMAGE](https://i.gyazo.com/fefbf806188a98445b7c11f77ba12767.png)

**Comment by HAlexTM** [comment]
Are you using the "test" test somewhere in some variable?

**Comment by MastaCoder** [comment]
Nope. I tried every single skin idea from alex to test1238. It seems like it is ignoring the knownDis.. variable that has the list of skins.

**Comment by HAlexTM** [comment]
So any name that you use is considered a skin?

**Comment by MastaCoder** [comment]
Updated post above ^

I know how to fix this, patching now.

**Comment by HAlexTM** [comment]
Yeah there was a missing test

**Comment by HAlexTM** [comment]
Just to speed up things: `-1 != knownNameDict.indexOf(skinName)`

**Comment by MastaCoder** [comment]
I found it right when you said that 😆
