### ISSUE TITLE
Hello server direct connection eror

### ISSUE THREAD

**Issue by dark84s** [CigarProject/Cigar#392]
First of all thank you for the script.

I want to connect to ffa1 directly on first login.

 <Option value = "151.80.108.25:5008" selected> FFA </ option>

I'm adding Select. but not connected

Ws: \\ empty looks chrome console

But then how do I fix it when I choose to open it.

**Comment by HAlexTM** [comment]
Run when document is loaded `setserver("IP:PORT");`
```
    <script>
    $(function(){setserver("IP:PORT");});
    </script>

**Comment by dark84s** [comment]
Thank you!

**Comment by dark84s** [comment]
http://prntscr.com/d9nbyt


Looking for skin on behalf of every user chrome consol
How can i fix it.

**Comment by MastaCoder** [comment]
Or an easier way, just open the main_out.js and change the CONNECTION_URL from EMPTY to anything you want it to be.

That issue was fixed 111f7b5653206a499e35673066fa14765e322c1c

**Comment by dark84s** [comment]
I have already updated it like this.
The same error continues.

**Comment by MastaCoder** [comment]
@dark84s Are you sure you cleared your cache and updated the main_out.js? It works fine on my side.
