### ISSUE TITLE
Galery problem.

### ISSUE THREAD

**Issue by Gimmo** [CigarProject/Cigar#398]
It doesn't working for me "from the box" - maybe have some dependencies from old versions....

**Comment by HAlexTM** [comment]
Can you describe the problem?

**Comment by MastaCoder** [comment]
The gallery right now just indexes to the skins folder. That'll need to be fixed.

**Comment by HAlexTM** [comment]
Hope 25d5d51 solves the issue

**Comment by MastaCoder** [comment]
No update on this issue to date. Closing!
