### ISSUE TITLE
Authentication (registered names)

### ISSUE THREAD

**Issue by m-byte** [CigarProject/Cigar#4]
We will need a protocol extension for this.

I think, authentication should go like this:
1. client connects to the http server and authenticates
2. if the client has been authenticated by the server, it receives a token
3. on connection the client sends a third packet with the token when also sending packets 254 and 255
4. the server checks whether the token has already been used, whether the origin of the websocket matches, age of the token, .... We should probably add some more security checks here...

Setting the nickname should go like this:
1. the client sends the normal name set packet
2. server checks whether the client has permission to use the name
3. if the client has no permission, it either adds something to the name to show it's not authenticated or completely clears the name
4. the server sends a 'please authenticate' packet to the client
##### C2S: auth token (ID 253)

auth version, currently 0 (uint8)
token (2 \* uint32)
name (uint16 charcodes)
'/0' (uint16)
##### S2C: error (ID 4)

error code (uint8)

> ###### error codes:
> 
> If there is a http 4xx error defined, use `httpCode - 400`
> I.e. not authenticated turns into error 1.

**Comment by Eureka22** [comment]
Oh I thought you meant to implement a user management system, in which users can register, manage skins, add friends, etc. This seems is just for password locked names(like admin?).

**Comment by Jackster35** [comment]
When the client receives that packet, it should pull up a little menu saying "Registered name, please use something else"

**Comment by Jackster35** [comment]
Yes @Eureka22, that's what I was proposing for at the other issue thread :)

**Comment by m-byte** [comment]
@Eureka22 I want to implement a user management system. This issue is mainly for the protocol changes.

**Comment by Eureka22** [comment]
I see.

**Comment by m-byte** [comment]
@Eureka22 I just opened another issue for the user management

**Comment by batbug** [comment]
we have passwords implemented without the protocol changes. we just send the password along with nickname in format like this user:::::::pass. Then packethandler handles the string and checks with the username/password list

**Comment by m-byte** [comment]
That looks more like a hack, though.. Could ‎cause some problems later on. I want a solution that can easily be adapted to any kind of authentication. Also, having authentication independent, there could be a permission to use any username.

**Comment by Jackster35** [comment]
batbug, that's very insecure. You could quite easily use another client and use the connect function in your browser to connect. Any authentication should be handled server side

**Comment by batbug** [comment]
@Jackster35 maybe i wasnt very clear, but the authentication is done at the server side in my solution.

**Comment by Jackster35** [comment]
Ooo, could you possibly share?

**Comment by m-byte** [comment]
@batbug I understand, that you are doing authentication on the server. However, as I wrote, I would like the actual authentication to take place on a different page. That way, users could later enable things like facebook/google/... authentication without being forced to use the same name as nick in the game.
Another reason against this: while your solution allows for compatibility with the vanilla client, that is actually pretty dangerous. If you lose connection to your server, the vanilla client will connect you with one of the official servers while maintaining your nick. Since in your case the nick also contains the password, anyone on that server can see both your name and password.

**Comment by m-byte** [comment]
Also, since the token is more like a one-time-password, it is possible to have the authentication done on a different server with ssl. An attacker could only easily get access to the token. This way, security can be greatly increased by simply using an external authenticator.

**Comment by batbug** [comment]
@m-byte Yes, you are right. There are many situations where this can be dangerous. But we dont use vanilla client. We have our own.

**Comment by HAlexTM** [comment]
Sorry if I'm replying to this old thread but you're talking about sending packets with username, password etc... (I'm talking about the user management too) but this can all done through PHP and MySQL

index.php (if no Token cookie --> form --> login.php, else --> check Token in MySQL, show username)
login.php (if Token --> redirect, else --> read POST data and generate Token, save it in MySQL, save cookie)
main_out.js (if Token --> send it through socket)

Server side: (On Token receive --> check from MySQL --> is it valid? --> load user ID, else --> ID = 0 or guest)

Everything else that is needed, is done by the user ID

**Comment by MastaCoder** [comment]
Cigar is now client only.
