### ISSUE TITLE
[SKINNAME] Not working

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#400]
![](http://image.prntscr.com/image/e58a1183f17846fa8730214334296264.png)

![](http://image.prntscr.com/image/1da9de3d294a442b8928bd2456bdb717.png)

![](http://image.prntscr.com/image/98ed92fabc5b4dfaa1ec6304fd153df9.png)

Why doesn't work, it got removed in the last update?

**Comment by Lukkez** [comment]
![](http://image.prntscr.com/image/936d8a4b6cb345d4a21810b35c623487.png)

**Comment by HAlexTM** [comment]
The [...] is the clan tag, Test is the skin, everything inside the [] will be ignored

**Comment by MastaCoder** [comment]
This function was removed because it's been replaced with <skinname>
