### ISSUE TITLE
ROTATOR SKIN

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#404]
if (skinName == "doge") {
				 ctx.translate(this.size, this.size);
                    ctx.rotate( 45 * Math.PI / 180 );
                    ctx.translate(-this.size, -this.size);
                    ctx.drawImage(e, this.x - this.size, this.y - this.size, 2 * this.size, 2 * this.size); 
				
				
				}

is correct?

and where i should put this?

**Comment by CalvinDKHD** [comment]
Should be OK, but an easier way would be using a gift, of course you need
to make your client compatible.

**Comment by PsycoYT** [comment]
WHERE I SHOULD PUT THIS?

**Comment by CalvinDKHD** [comment]
Where the skins code is, but after a ; or just add it so it doesn't
interfere with any other code

**Comment by PsycoYT** [comment]
i cant understod
