### ISSUE TITLE
Skin resize problem on split

### ISSUE THREAD

**Issue by cedrsgaming** [CigarProject/Cigar#406]
Hello
When you split (from bigger to smaller) the split animation take a small delay but the skin picture is resized instantly.
This create a small "bug" and player see the square based skin.
I think add the same delay of cell resize animation is a good way to fix them.

Nb: yes i enable the grid on my client.

Thanks for all

![bug-skin](https://cloud.githubusercontent.com/assets/24306958/20820285/6447b79e-b83a-11e6-8576-88082154a01f.png)

**Comment by MastaCoder** [comment]
Weird I've never noticed this.

**Comment by CalvinDKL** [comment]
Its not really a bug....
i had this too, to make it look much better just do so the skin makes the cell color different.
So if i pick the shark skin the cell color becomes blue.

**Comment by CalvinDKL** [comment]
Smooth render should also fix it.

**Comment by cedrsgaming** [comment]
Yep, this not append in smooth render, but why not change skin size after resize animation is done (like the true agario)

**Comment by agariotips** [comment]
What we need to figure out is where is the skin resize animation done?

**Comment by MastaCoder** [comment]
There isn't really a "resize" function. It's more of how the cell is drawn and animated: https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1279

**Comment by mrzack506** [comment]
Fixed, this may now be closed.
