### ISSUE TITLE
Spectate issue

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#408]
hello! When i put the server scrambling up on MultiOgar Edited the spectate stops working work. it pumps.
I remember ItzLevi fixed it.

[https://gyazo.com/0e1db0370c2121d44d048d271f19406d](url)

**Comment by CalvinDKL** [comment]
I dont think its a bug, i just think its the server scrambling it. But i dunno!
IT only happens when i put the scrambling level to 2 or up.

**Comment by CalvinDKL** [comment]
Check it out on my server / agarup.us

**Comment by MastaCoder** [comment]
Yeah I noticed this happening as well. I think it does this because the server keeps updating the player position and the client is loading the scrambled method?

Will need to view the code of the scramble to fix this.

**Comment by CalvinDKL** [comment]
Ye, its cuz a player on my server is using minions. And i want to be able to patch them without it affecting my client.

**Comment by MastaCoder** [comment]
Related to #386
