### ISSUE TITLE
Auth Token

### ISSUE THREAD

**Issue by Gimmo** [CigarProject/Cigar#410]
Where,  in Cigars code, can I found/add a Token (https://github.com/forairan/Agar.io-Protocol/blob/master/Protocol.md  Packet 80) in Cigars code, to be sent to server? 
I can't found it to be implemented. Please, just point me correct place, where it should be added to the code to be sent to server.

**Comment by MastaCoder** [comment]
You mean here: https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L68 ?

That's where it listens for key presses and sends a packet based on the keypress.

**Comment by Gimmo** [comment]
I don't see it. Not on L68 , not in sendMouseMove(). not in wsSend(). It shoul be, but I don't understand where. Btw, where is PacketID?  Maybe Token should be sent in a separate packet? With own id?
Seems I don't understand something fundamental....

Packet 80: Send Token

Sent at the beginning of a connection, after packet 255.
Used to authenticate with a one-use token issued by the load balancer.

Position	Data Type	Description
0	uint8	Packet ID
1	string	Token. 8 characters, alpha-numeric, and some symbols. (uint8)

**Comment by Luka967** [comment]
Packet 80 is a token packet specifically used only by agar.io gameservers to confirm that it's a valid vanilla client when connecting. Cigar doesn't need it.

**Comment by MastaCoder** [comment]
@Luka967 February 22nd of this year. - Based commit 5f058c7cace689d31ba5afe3b081fc06d9024c6a.

I pretty much was working on a newer version of Cigar, ItzLevvie made one with MultiOgar. Since the server was getting updated quite fast, we dropped the server and went client only 👍

**Comment by Luka967** [comment]
Oh! I didn't dig into Cigar's history that much xD

**Comment by MastaCoder** [comment]
Haha yeah I kept quite on this project over the summer 😄 @Luka967
