### ISSUE TITLE
How to add a 2nd skin directory?!

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#412]
Hey so in the main_out, there is a skin directory.
I tried adding a 2nd one by just copying and pasting, BUT. Then only 1 of them works.
How do i do it?

Thanks!

**Comment by MastaCoder** [comment]
It'd be a bit harder since you'd have to also copy the contents of the checkdir.php to work with it to. Then you'll have to check the client to check if the file exists in one folder, if not check another. Or, completely add another pack of variables.

It's way too much work. Just use one, it'll save you lag!

**Comment by CalvinDKL** [comment]
Yes but then ppl can find secret skins lol

**Comment by MastaCoder** [comment]
They'll find it either way just by looking in the network through chrome. 💯

**Comment by CalvinDKHD** [comment]
Wait i  know how! just do like ../private/skins which is a private folder,
won't that work?

**Comment by HAlexTM** [comment]
Absolutely no, your skins will never be private

**Comment by CalvinDKHD** [comment]
Not what i mean. What i mean is that only a certain person can use a skin.
and he uses a code (the name) which is just random numbers. Its a bit hard
but i would have to make something like a login system.

**Comment by Gimmo** [comment]
Why not to use approach offered by alis.io?

**Comment by CalvinDKHD** [comment]
Approach? please explain

**Comment by Luka967** [comment]
@CalvinDKHD Use URLs to pictures as a skin

**Comment by HAlexTM** [comment]
What you're requesting needs both server and client modifications

**Comment by CalvinDKHD** [comment]
Yes, BTW i am using links, but they are public links on my server. Can i
add it to a private directory??

**Comment by MastaCoder** [comment]
For what you're requesting, you'll need to add a members system that will check user information which the client sends to the server. It's quite a bit of work, since security would also have to be important while working on this.
