### ISSUE TITLE
how to draw borders

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#415]
how to draw borders of the map?

**Comment by iamtaeuk** [comment]
Please search before you post an issue.

Check this issue: #393

**Comment by PsycoYT** [comment]
borders of map , no grid.

**Comment by MastaCoder** [comment]
I highly discourage drawing a border. It can be done by drawing a line between the ends of the map in the main_out.js. Don't do it because serverScramble will break it, and you'll need it if you don't want bots raiding your servers.
