### ISSUE TITLE
Login with OgarUnlimited

### ISSUE THREAD

**Issue by tweenkapy** [CigarProject/Cigar#417]
Im trying to play with ogar unlimited, but when join i get this error on console

main_out.js:604 Uncaught RangeError: Offset is outside the bounds of the DataView

I can join just with MultiOgar and OgarServer, but OgarUnlimited is better.
Possible to play cigar with ogar unlimited?

**Comment by PsycoYT** [comment]
are incompatible

**Comment by MastaCoder** [comment]
Ogar-Unlimited uses another protocol that is not supported by Cigar.
