### ISSUE TITLE
Challenge: how to select...

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#422]
How to select a main_out, according to the ip that has been connected?

**Comment by CalvinDKL** [comment]
What i would do is to simply copy and paste the main_out and maybe name the new one main_out2
and then make a new index.html which just uses that instead.

BTW send me your server link! :D

**Comment by HAlexTM** [comment]
What you want is weird, probably what you want really to do can be done in other ways, what do you want to do?

**Comment by RelTakeover** [comment]
I want to get every server I have its own main_out, without changing index

**Comment by HAlexTM** [comment]
I know that, but why would any server have its own js file? what should change in these files?

**Comment by PsycoYT** [comment]
To have specific configurations for each server

**Comment by MastaCoder** [comment]
This is a very very bad practice. It can be done with PHP. Simple check the URL and if it matches to echo the main_out.js for you. 

We're going to start promoting people to learn how to code themselves. So I'm not going to provide examples, you'll have to work on finding out how to add it yourself 👍 We just give hints now.
