### ISSUE TITLE
Changing the zoom distance players can zoom.

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#424]
Title says it, how can i do it?

Thanks!

**Comment by Luka967** [comment]
You can do it by editing the function [`calcViewZoom` in main_out.js line 686.](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L686)

**Comment by CalvinDKL** [comment]
THank you!

**Comment by tweenkapy** [comment]
What do I need to change to make the zoom unlimited?

**Comment by tweenkapy** [comment]
Change your handleWheel function for this
`    function handleWheel(event) {
        zoom *= Math.pow(.9, event.wheelDelta / -120 || event.detail || 0);
        0 > zoom && (zoom = 1);
        zoom > 1 / viewZoom && (zoom = 1 / viewZoom)
    }
`
