### ISSUE TITLE
How to change the color of the buttons?

### ISSUE THREAD

**Issue by AlexByte918** [CigarProject/Cigar#426]
For example, Play is blue, I want to change that

**Comment by HAlexTM** [comment]
[index.html #L48](https://github.com/CigarProject/Cigar/blob/master/www/index.html#L48)
```html
<button type="submit" id="play-btn" onclick="setNick(document.getElementById('nick').value); return false;" class="btn btn-play btn-primary btn-needs-server">Play</button>
```
Inside `class="btn ...."` change `btn-primary` to one inside this [list](http://www.w3schools.com/bootstrap/bootstrap_buttons.asp)
