### ISSUE TITLE
Leaderboard long name problem

### ISSUE THREAD

**Issue by HAlexTM** [CigarProject/Cigar#430]
If you use some special character making your name really long you will look like this in the leaderboard:
![onpaste 20161211-190857](https://cloud.githubusercontent.com/assets/11839341/21082142/6f44fa74-bfd5-11e6-93a0-04bb839a12f5.png)

On the original client (Agar.io) the first character is always the rank number:
![onpaste 20161211-191651](https://cloud.githubusercontent.com/assets/11839341/21082170/6204faa2-bfd6-11e6-8476-86354791ae9a.png)

**Comment by MastaCoder** [comment]
I have also realized this when playing with my client. I think it's due to us forcing center first then moving onto it?

**Comment by HAlexTM** [comment]
Probably, we need more tests

**Comment by HAlexTM** [comment]
So I think that [measureText();](http://www.w3schools.com/tags/canvas_measuretext.asp) will do the work

**Comment by Luka967** [comment]
I'm working on this

**Comment by HAlexTM** [comment]
fixed 481103a69798c6ec08525032000681984fcfd1dd
