### ISSUE TITLE
User authentication colour (admin colour)

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#432]
Hey!

What i would want is for admins or people who login in the chat to get a certain colour of something so people know that they are real. I know this is server sided and client sided, but does anyone know how to do this??

Thank you!

**Comment by HAlexTM** [comment]
Pseudo code:
You could use the nick as a password, on the server if you're using this nick and mark your Cell as Admin then when you send the cells list you add a flag where you say if this cell is an Admin, if so you can change the Nick color when drawing the cell.

**Comment by MastaCoder** [comment]
^, there is almost no way to do this. It's either the top method or with MySQL.

Also, MultiOgar does have a user system in place, we should probably add the flags to Cigar though. I'll add an issue on this.
