### ISSUE TITLE
Bots Skins

### ISSUE THREAD

**Issue by Gimmo** [CigarProject/Cigar#436]
When I use MultiOgar with agar.io client, bots I run get the skins. All botnames on server have a tag `<xxxx>` in the name. What should I do to force Cigar to work the same way?

**Comment by HAlexTM** [comment]
We are working on this

**Comment by MastaCoder** [comment]
It should work the exact same way on Cigar, no?

**Comment by HAlexTM** [comment]
Check out the [bot names](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/ai/BotNames.txt#L1) you should have skins with this name

**Comment by Gimmo** [comment]
@HAlexTM `you should have skins with this name` > have where?

**Comment by HAlexTM** [comment]
I guess in the `skins` directory, I need to test it tho.

**Comment by HAlexTM** [comment]
I wrote <doge> before every bot name, every bot got that skin, working, closing.
