### ISSUE TITLE
Changing the background color.

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#439]
Title says it, i want the background of the game changed.
Its in the mainout but i dont know where.

**Comment by Luka967** [comment]
[Here](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L720) and [here](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L825) for background, [here](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L828) for grid.

**Comment by MastaCoder** [comment]
@Luka967 Is spot on. 👍
