### ISSUE TITLE
Chat flood

### ISSUE THREAD

**Issue by smatch999** [CigarProject/Cigar#44]
Players can flood the chat and lag the server.
How can we put a limit of messages per second?
Thx!

**Comment by matrixreal** [comment]
yes me too got same lagg specially on mobile
maybe disabling chat will help
did anyone know how to disable chat by default (wihout going to settings etc ...)

**Comment by TheMaskedMonkey** [comment]
I'd recommend they take down the repo before Miniclip's does.

**Comment by matrixreal** [comment]
@m-byte 
it will be great that (for mobile) chat is disabled (since it will certainly helps about the lagg issue)
and peoples enable it only if they like to use it
so disabled by default ... and enable it if they want

**Comment by m-byte** [comment]
@smatch999 I'll try to think of a way to limit the number of chat messages a client is allowed to send. This will have to be implemented on the server side. Would you rather have the server drop any message over the limit or have the spamming client be banned?

@matrixreal We could add a setting to the config to disable the chat on the server side.

@TheMaskedMonkey I have no clue what you are trying to say.

**Comment by m-byte** [comment]
@matrixreal That's definitely possible.

**Comment by matrixreal** [comment]
@m-byte 
@smatch999 
yes the spamming client will be banned for couple of days / hours will be perfect
it will be perfect if you add a setting to config to disable chat on the server code
MANY THANKSSSSS WE LIKE YOU IN FRANCEEEE

**Comment by matrixreal** [comment]
any news about disabling (not hiding :D) the chat by default ?

**Comment by smatch999** [comment]
@m-byte 
The server does not go down, but can give much lag.
A limit of messages per second would solve it.

Thx.

**Comment by xmicro** [comment]
If you could implement a way for the client's messages to be dropped, or auto-banned would be fascinating!

**Comment by Logan7432** [comment]
so what happened to this? it sounded like this idea was going so well and never happened cause people spam so much on my server and i really need a chat delay. Also a word filter would be great if someone can help me.

**Comment by Logan7432** [comment]
I found a way to stop flood!

**Comment by matrixreal** [comment]
@Logan7432 
can you share with us the solution?

**Comment by Logan7432** [comment]
Well. I completely re designed the main_out.js but I'm not sure if I would share it because of all the time I put into it.

**Comment by MastaCoder** [comment]
I added this :)
