### ISSUE TITLE
error in gallery

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#442]
![image](https://cloud.githubusercontent.com/assets/24230169/21333407/3d5ca26e-c62e-11e6-8897-42cedcd5b0fd.png)

is default...

**Comment by MastaCoder** [comment]
Are you sure you didn't change anything? Show us the code inside of the gallery.php file.

**Comment by PsycoYT** [comment]
i changed nothing.

**Comment by HAlexTM** [comment]
Post a screenshot of your `skins` folder

**Comment by PsycoYT** [comment]
DEFAULT

**Comment by HAlexTM** [comment]
Holy sh*t, do you want the help? Do what I said.

**Comment by MastaCoder** [comment]
Clearly it's not default because that error in the folder. You clearly changed something..

**Comment by HAlexTM** [comment]
1- the user won't reply
2- cannot reproduce bug/not default files
