### ISSUE TITLE
help

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#443]
I NEED KNOW HOW TO SET SKIN THROUGH THE CONSOLE

**Comment by HAlexTM** [comment]
What console?

**Comment by PsycoYT** [comment]
google javascript console ( F12) -_-

**Comment by HAlexTM** [comment]
You can't.

**Comment by MastaCoder** [comment]
You can set it through the chat. /skin, but it only works if the user is not spawned yet.

**Comment by PsycoYT** [comment]
If I could give skin via google console , 
Could change the color to the cell depending on the skin, why not?

**Comment by HAlexTM** [comment]
We need to work on it
