### ISSUE TITLE
Add admin color and indentificator

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#444]
FOR ADMINS IN MULTIOGAR

**Comment by HAlexTM** [comment]
Color: server side
What do you mean by identificator?

**Comment by CalvinDKHD** [comment]
Yesssss sir!

**Comment by PsycoYT** [comment]
IDENTIFICATOR WHEN A ADMIN ENTER TO THE SERVERS THIS NICKNAME CHANGE TO [ADMIN] WITH A SPECIFIC COLOR

**Comment by HAlexTM** [comment]
The [Admin] prefix server sided
As we need more flags that currently MultiOgar Isn't sending we cannot do that

**Comment by MastaCoder** [comment]
@HAlexTM This is where the flags are, I tried converting to decimal or just adding them, but it doesn't seem to work.

https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/ChatMessage.js#L30-L37

https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L439-L449

**Comment by HAlexTM** [comment]
@MastaCoder I thought he was talking about the cell's name

**Comment by MastaCoder** [comment]
🌱 

I should find some time to add the flags later this week. Ugghhh
