### ISSUE TITLE
cell.sh

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#447]
that agar using cigar based main_out and have system level LOL

**Comment by HAlexTM** [comment]
Requires server modifications

**Comment by zettabyte918** [comment]
lol why server modifications its just some line php and facebook application ! @HAlexTM

**Comment by AlexDicy** [comment]
@hossemThecoder
Not exactly, levels data are calculated by the server, we cannot handle that
Anyway, I'm not working, no more, for this project, so don't mention me.
