### ISSUE TITLE
How would I change the leader board alignment.

### ISSUE THREAD

**Issue by TheJustExper** [CigarProject/Cigar#448]
The leaderboard is centered atm but how would I change is so the text is at left of the box

**Comment by HAlexTM** [comment]
[main_out.js#L898](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L898)
Change this
```javascript
var start = (ctx.measureText(c).width > 200) ? 2 : 100 - ctx.measureText(c).width * 0.5;
```
to this
```javascript
var start = 2;
```
