### ISSUE TITLE
what languajes?

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#449]
what languajes use the main_out.js ?

canvas , javascript and nodejs ¿?

**Comment by MastaCoder** [comment]
JavaScript.

**Comment by PsycoYT** [comment]
and nodejs?

**Comment by MastaCoder** [comment]
Nope. Just JavaScript.

**Comment by iamtaeuk** [comment]
By the way, skin uses PHP.

**Comment by Luka967** [comment]
"canvas" language
xD
