### ISSUE TITLE
white screen freez issue

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#45]
hi all
@m-byte hi
i just notice that i got frezz screen like the screenshoot below on safari 5.1.7 (screen shoot 1 from pc)
also the game got white screen with chat pop up and nothing display 
![sans titre](https://cloud.githubusercontent.com/assets/6823974/9006761/4f27c948-378b-11e5-8d46-0adcaad6df0f.png)

**Comment by m-byte** [comment]
Can you open the developer tools (F12) and see if there are any error messages or warnings?

**Comment by deniskrop** [comment]
I have this issue too

**Comment by CalvinDKHD** [comment]
i have the same issue
