### ISSUE TITLE
Intercepting chat messages

### ISSUE THREAD

**Issue by iamtaeuk** [CigarProject/Cigar#452]
Hello,

I am trying to make a notification whenever `SERVER`, `ADMIN`, or `MOD` sends a message by using the flags they send with. The most recent commit `f5891bf` got the flags from the server (MultiOgar), so I am trying to use that. 

When the admin says 'Hello', I want the notification to pop up saying 'Hello', but I'm not sure where I could extract that text from.

Thanks.

**Comment by HAlexTM** [comment]
[Line 486](https://github.com/CigarProject/Cigar/blob/f5891bf8ccf130c95086bb3a705fcc721bb11876/www/assets/js/main_out.js#L486)
```javascript
if (flags & 0x40) {
    // ADMIN Message
}
```
Do your things and stop it here.
```javascript
if (flags & 0x40) {
    // ADMIN Message
    openMyPopup(...);
    return;
}
```

**Comment by iamtaeuk** [comment]
Works perfectly. Thanks!
