### ISSUE TITLE
Increase cell speed

### ISSUE THREAD

**Issue by Flavorounet** [CigarProject/Cigar#453]
Hi,

I am creating an online agario server using Cigarproject. I am searching how to increase the speed of a player cell for some minuts.

I search many times on the web but i have not really find interesting issues, so please can you say me where i can find the cell speed function or the cell speed value ?

Thank's you !

**Comment by HAlexTM** [comment]
It must be done by the server, ask to them

**Comment by Flavorounet** [comment]
Yes, that's why i create this issue. If you know how i can contact them in another way please tell me.
