### ISSUE TITLE
Error in the Main_out

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#455]
https://gyazo.com/4537dead84a257b5186101ffb12a52dd

Anyone know how to fix this?
I havent touched the mainout for a long time, it just appeared randomly.

**Comment by HAlexTM** [comment]
You modified it, the original is
```javascript
    wjQuery.ajax({
        type: "POST",
        dataType: "json",
        url: "checkdir.php",
        data: data,
        success: function(data) {
            response = JSON.parse(data["names"]);
            for (var i = 0; i < response.length; i++) {
                if (-1 == knownNameDict.indexOf(response[i])) {
                    knownNameDict.push(response[i]);
                }
            }
        }
    });
```

**Comment by CalvinDKHD** [comment]
Thats not it!
that is not the correct code
its this -
https://gyazo.com/166223eb722ee945420aca33940e4ccb

**Comment by HAlexTM** [comment]
Are you kidding me? What I wrote was taken from from the original file.
