### ISSUE TITLE
where

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#457]
where is the code of the virus¿?

**Comment by HAlexTM** [comment]
In the drawOneCell() function [main_out.js](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1322)

**Comment by PsycoYT** [comment]
lines?

**Comment by HAlexTM** [comment]
Click that link :(

**Comment by PsycoYT** [comment]
especify lines in function drawonecell ?

**Comment by MastaCoder** [comment]
All of it.

**Comment by Luka967** [comment]
It's actually the `movePoints` function if you're interested in changing the virus draw lines, but beware that changing it can do weird stuff.
