### ISSUE TITLE
What is the onchange event for hiding the grid?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#459]
Sup! the title says it,
i'm using this - 
`onchange="setHideGrid($(this).is(':checked'));"`

This is the error i get when i try to use the checkbox

1:  https://gyazo.com/2cbf29902b1cb5d3de39cbf0c5477b05

2:  https://gyazo.com/83b6b258f9693bd69ce4c768f0bbdd33

**Comment by HAlexTM** [comment]
Hover your mouse on the red x (second screenshot) what does it say?

**Comment by PsycoYT** [comment]
you trying adapt ogarul client to multiogar servers -_-

**Comment by CalvinDKHD** [comment]
what? no i am trying to fix the grid feature

**Comment by CalvinDKHD** [comment]
Halex, this comes up - https://gyazo.com/ee4811ea9c81cf8b2f7c15b8a1a18a27

**Comment by HAlexTM** [comment]
@PsycoYT please wait 10 seconds before writing (or simply don't write) anything here, thanks.
@CalvinDKHD you obviously copied this from somewhere else :) anyway the correct way to do this would be

[main_out.js#L1004](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1004) add the variable `hideGrid`:
```javascript
        showSkin = true,
        hideGrid = false,
```
[main_out.js#L1068](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1068) add your function:
```javascript
    wHandle.setHideGrid = function(arg) {
        hideGrid = arg
    };
```
[main_out.js#L867](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L866) hide the grid with `if (hideGrid) return;`
```javascript
    function drawGrid() {
        ctx.fillStyle = showDarkTheme ? "#111111" : "#F2FBFF";
        ctx.fillRect(0, 0, canvasWidth, canvasHeight);
        if (hideGrid) return;
        ctx.save();
        ctx.strokeStyle = showDarkTheme ? "#AAAAAA" : "#000000";
        ctx.globalAlpha = .2;
        ctx.scale(viewZoom, viewZoom);
        var a = canvasWidth / viewZoom,
            b = canvasHeight / viewZoom;
        for (var c = -.5 + (-nodeX + a / 2) % 50; c < a; c += 50) {
            ctx.moveTo(c, 0);
            ctx.lineTo(c, b);
        }
        ctx.stroke();
        ctx.beginPath();
        for (c = -.5 + (-nodeY + b / 2) % 50; c < b; c += 50) {
            ctx.moveTo(0, c);
            ctx.lineTo(a, c);
        }
        ctx.stroke()
        ctx.restore()
    }
```
