### ISSUE TITLE
What is the onclick event for setting a skin??

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#462]
The title says it.

Thanks!

**Comment by HAlexTM** [comment]
It doesn't exists

**Comment by CalvinDKHD** [comment]
Ok ok, thanks.

**Comment by MastaCoder** [comment]
Are you talking about this onclick? https://github.com/CigarProject/Cigar/blob/master/www/include/gallery.php#L11

**Comment by CalvinDKL** [comment]
Nope, but its ok. Don't worry :)
