### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#463]
what is variables of:

- points cells.
- player cells.
- virus cells.
- The variable that defines the top 1

**Comment by Luka967** [comment]
- All cell variables are [here](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L958)
- [Here](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L990) although you can only get players' names and nothing else.
