### ISSUE TITLE
Operator Javascript

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#466]
```
else if (this.name == '{kraken}') {
					
					ctx.fillStyle = "#006944";
					ctx.strokeStyle = "#006944";
				
					
					
				}
```

**I want to make it recognize that the name in a part has the word {kraken} and not that it is equal to {kraken}**

**I mean that the name contains {kraken} and not that it is fully equivalent to {kraken}**

**What is the operator or how to do this?**

**There is an operator or some function that says: "Contains this" 

Or something similar according to what I have explained**

> _i think is 👍 
> else if (this.name.indexOf('{kraken}')) {
> 
> but not work.. with indexOf_

**Comment by HAlexTM** [comment]
```javascript
else if (this.name.indexOf("{kraken}") !== -1) {
    //...
}
```

**Comment by PsycoYT** [comment]
I think that is the method for color according to skin =)
