### ISSUE TITLE
Setclan ?

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#467]
You can create a setnick equivalent to setClan, 
Just copying all variables and replacing them for 'clan'

And changing the position of the clan text above that of the name?

is like that

![image](https://cloud.githubusercontent.com/assets/24230169/21528589/617ccd50-cd12-11e6-9fe9-0eed61dd07f1.png)

**Comment by Luka967** [comment]
Yes however we want to go vanilla only and will not accept any modifications apart from vanilla-like.
You can code it yourself though, it's pretty similar to name drawing

**Comment by PsycoYT** [comment]
@Luka967  recently i create setclan , but 
Gives me the error that tolowerCase is not defined -_-

**Comment by Luka967** [comment]
It's `toLowerCase` not `tolowerCase`
