### ISSUE TITLE
sMacro is not defined error

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#469]
Sup!
Normally i look in the console to see if there is any errors, i saw this one. It does not seem to affect anything, but it would still be nice to have a error free console :)

Anyone know how to fix this? 

https://gyazo.com/ed2b4abd774fcdb56ce63d66acefbe67
https://gyazo.com/5918bf7f6b8712e605995a67a4b572c4

**Comment by HAlexTM** [comment]
https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L90

Modified file
