### ISSUE TITLE
how can i increase speed ?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#47]
hi all,
did you know how can i increase the cell (player) speed ?
because at the begining it's slow comparing to agar.io 
thanks

**Comment by matrixreal** [comment]
if we compare with this server (ogar) example http://fxia.me/agar/
just the cell / player speed of this cigar project is low (nothing related with lagg or performance) just the speed of the cell
the initial speed is low and also it decrese quickly than

**Comment by smatch999** [comment]
Hi, send-me the configuration hardwares you have installed the Cigar Server (CPU, RAM, BANDWIDTH NETWORK...)

**Comment by matrixreal** [comment]
cpu : Intel Core i5 430Mram : 8 gb 1066Mhz DDR3graphics : intel hd 3000hard drive : ssd 120 go kingstone sv300
what you suggest me ? is it enough ?
how to get bandwich ?

Date: Sat, 1 Aug 2015 17:06:19 -0700

**Comment by matrixreal** [comment]
@smatch999 
i just want to increase the game speed ... nothing related with performance or lag
just the movement speed ... you understand me ?
thanks in advance

**Comment by m-byte** [comment]
@matrixreal you should be able to adjust it by editing `Cell.prototype.getSpeed` in `server/entity/Cell.js`. Just play around with the values until it works the way you want.

**Comment by matrixreal** [comment]
@m-byte 
thanks a lot i appreciate your help ... this is what i was searching about many thanks
and about the game title ? where can i ajust it ? i was searching all the night about "ogar" title and don't find it ?

**Comment by m-byte** [comment]
Are you using the latest version of Cigar with the integrated client? If so, you can change the name in `server/web/routes/index.js`

**Comment by matrixreal** [comment]
yes lastest version
and sorry i don't find it ...
here is my server 88.167.14.2 ... the title of the main page is ogar and i want to change it
but server/web/routes/index.js no found ogar title game ? confused !!!

**Comment by matrixreal** [comment]
@m-byte 
i dowload the lastest cigar
i go to index.js as you told me
but it still show agar clone title

**Comment by m-byte** [comment]
Are you using the integrated client?                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.

**Comment by matrixreal** [comment]
@m-byte 
thats is simple .... look
i download cigar-master.zip from this repo ... extract it 
i go to server/web/routes/index.js
i change var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function (req, res, next) {
    res.render('game', {title: 'Cigar', game: true});
});

router.get('/gallery', function (req, res, next) {
    res.render('gallery', {title: 'Cigar skins', gallery: true});
});

module.exports = router;

i change 'cigar' to my favorite title (cigar no more agar) (like that :D)

it's strange when i lunch cigar.exe
i still get "agar clone"
look to the picture
![cigar](https://cloud.githubusercontent.com/assets/6823974/9112520/456fd576-3c4f-11e5-88c4-1bd0d734168d.png)

**Comment by m-byte** [comment]
Try reloading the page with Ctrl+Shit+R to clear your cache.
