### ISSUE TITLE
It may be good

### ISSUE THREAD

**Issue by Gimmo** [CigarProject/Cigar#470]
It may be good to have a reference to other clients in desctiption to be able compare Cygar with them .
Fast and smooth bubble.am. May be old protocol (dont want to work for me with servers from tracker).

**Comment by Gimmo** [comment]
http://dual-agar.online/

**Comment by HAlexTM** [comment]
Our is a client which you can use for your own website, what you're linking are websites! Not Clients projects

**Comment by Gimmo** [comment]
If you try to press appropriate keys, you can access to client of each website and learn why and where it's better then yours. No-one never can make the best if not learn competitors.

**Comment by HAlexTM** [comment]
@Gimmo, these are modified clients, that differ from the original Agar so... we got no competitors at all

Will reopen if OP posts valid reasons
