### ISSUE TITLE
Smooth Render bugs

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#471]
**The zoom affects smoothrender and the cell looks like a decagon**

**In vanilla does not happen that**

**And in addition the smoothrender of cigar is very slow, in agar.io is fast as if the UpdatePos was in 60 instead of 120**

![image](https://cloud.githubusercontent.com/assets/24230169/21540340/672051b6-cd8d-11e6-8f29-6a55cc590fce.png)
![image](https://cloud.githubusercontent.com/assets/24230169/21540597/fea3f5a0-cd8e-11e6-9877-a0a10444d7f8.png)

![image](https://cloud.githubusercontent.com/assets/24230169/21540347/7122d792-cd8d-11e6-9ae3-93303e69a9bf.png)

**Comment by Luka967** [comment]
Whar's your resolution? It doesn't happen for me, not even on that site.

**Comment by HAlexTM** [comment]
@Luka967 I can confirm that sometimes it happens to me too, FHD.

**Comment by PsycoYT** [comment]
@Luka967 
Happens to me in varied resolutions.-

**Comment by PsycoYT** [comment]
new issue.

**Comment by Luka967** [comment]
I've just expirienced this.
The entire code needs to be rewritten with performance and vanilla style in mind. I'll try it a few times and will try to use protocol 7

**Comment by MastaCoder** [comment]
@Luka967 No open source server supports Protocol 7 yet, right?

**Comment by HAlexTM** [comment]
has anyone got any Protocol changelog?

**Comment by MastaCoder** [comment]
@HAlexTM https://github.com/issy123/agario-protocol/issues/15

**Comment by HAlexTM** [comment]
Awesomw ty

**Comment by MastaCoder** [comment]
Why are there two issues on this 😆

**Comment by ZfsrGhS953** [comment]
As far as I know, these 4 accounts are owned by one person:
https://github.com/PsycoYT
https://github.com/RelTakeover
https://github.com/arxn
https://github.com/supportAC
He probably made them to bypass bans.

**Comment by ZfsrGhS953** [comment]
@Luka967 Current protocol is 9, not 10.

**Comment by PsycoYT** [comment]
@Luka967  you have been able to fix it

**Comment by Luka967** [comment]
@ZfsrGhS953 I keep thinking it's 10 for some reason

**Comment by PsycoYT** [comment]
@Luka967  ok please try =)

**Comment by PsycoYT** [comment]
yet trying? @Luka967

**Comment by Luka967** [comment]
@PsycoYT This will take a few days to reconstruct if I keep up the current pace

**Comment by MastaCoder** [comment]
Haha awesome @Luka967 

But this hexagon thing is weird, I have never seen this happen and nobody has complained about it yet on my website..

**Comment by PsycoYT** [comment]
You must lower the number of smoothrender from .4 to .2 , like agar.io

**Comment by Luka967** [comment]
I've got successful connection to the server with protocol 6 in mind, as of now on the rewrite. Has some basic drawing logic but seems to not be working.

**Comment by PsycoYT** [comment]
Come on, you can do it @Luka967

**Comment by Luka967** [comment]
Errorless data flow between server and new client. Only the drawing stuff is left, this will be hard to optimize

**Comment by Luka967** [comment]
Finally something is working
![home - cigar - google chrome 1_1_2017 5_40_02 pm](https://cloud.githubusercontent.com/assets/15956695/21582032/81205386-d049-11e6-884a-b5e177a600e9.png)

**Comment by mrzack506** [comment]
reader.js and writer.js seem to despise Main_out, the functions are there, but it's just not picking up.

**Comment by Luka967** [comment]
I've actually forgot to add those two files for loading.

**Comment by MastaCoder** [comment]
Wow that is really cool, I'll see what I can see to commit to it as well :)

**Comment by Luka967** [comment]
![lol](https://cloud.githubusercontent.com/assets/15956695/21583317/3d0ac82e-d07c-11e6-884d-1ce3fe50db78.JPG)
At least better than nothing... xD

**Comment by MastaCoder** [comment]
If agar.io was squares, that's what would happen xD

**Comment by Luka967** [comment]
![a](https://cloud.githubusercontent.com/assets/15956695/21583426/7930a9fa-d080-11e6-8a02-a2aa032e8e03.JPG)
I have to address this color issue

**Comment by MastaCoder** [comment]
Wow, if you can manage to remake it that would be awesome! (It also technically wouldn't be a copy from Agar.io anymore like it is right now 👍 )

**Comment by HAlexTM** [comment]
Yeah, this work is awesome

**Comment by PsycoYT** [comment]
@Luka967  nice job ! how to connect to the server ip ?=)

**Comment by PsycoYT** [comment]
nice job @Luka967

**Comment by Luka967** [comment]
So I accidentally removed `beginPath` and `closePath` for cell drawing... and this happened xD
![kik](https://cloud.githubusercontent.com/assets/15956695/21583599/3646cef0-d088-11e6-983e-b5ff501ea136.JPG)

**Comment by PsycoYT** [comment]
@Luka967  when will be ready?

**Comment by Luka967** [comment]
@PsycoYT 2-3 days. Currently fixing a weird destruction bug.

**Comment by Luka967** [comment]
![as of now](https://cloud.githubusercontent.com/assets/15956695/21592822/32b8d042-d111-11e6-8ad7-68e11f5c819e.JPG)
Client as of now

**Comment by PsycoYT** [comment]
@Luka967  i cant connect to my server 
How do you do

**Comment by HAlexTM** [comment]
Right click on a white space in the menu, press "Inspect element"
There is a div with id "overlays" at the left (or bottom) remove "display:
block"
Then use the chat and write in your server ip (eg: localhost:443) then open
the console and write play("name");

If it doesn't work, it won't work, wait for updates

Il Lun 2 Gen 2017, 6:11 PM PsycoYT <notifications@github.com> ha scritto:

**Comment by HAlexTM** [comment]
Right click on a white space in the menu, press `Inspect element`
There is a div with id `overlays` at the left (or bottom) remove `display:
block`
Then use the chat and write in your server ip (eg: localhost:443) then open
the console and write `play("name");`

If it doesn't work, it won't work, wait for updates

**Comment by PsycoYT** [comment]
ok thx

**Comment by Luka967** [comment]
It didn't work because uint8 insertion was wrongly compared. Should work now, also it has a leaderboard.

**Comment by Luka967** [comment]
Hey look!
![hey look](https://cloud.githubusercontent.com/assets/15956695/21594683/bd7b114a-d125-11e6-9acd-30c743631936.JPG)
xD

**Comment by Luka967** [comment]
![hey](https://cloud.githubusercontent.com/assets/15956695/21595367/908db6ee-d12d-11e6-8d54-13b49e40c964.JPG)
Almost done! Making finishing touches

**Comment by HAlexTM** [comment]
Todo:
 - Text stroke
 - Virus shape
 - Cell points

**Comment by PsycoYT** [comment]
@Luka967  you can add CLAN TEXT ABOVE OF THE NAME? =)

**Comment by Luka967** [comment]
No

**Comment by HAlexTM** [comment]
Direct reply.

**Comment by Megabyte918** [comment]
rekt

**Comment by Luka967** [comment]
Client as of now
![a](https://cloud.githubusercontent.com/assets/15956695/21608688/6593fa8e-d1be-11e6-8ec4-e04c3b49a32c.png)
Making virus points now

**Comment by Luka967** [comment]
![kek](https://cloud.githubusercontent.com/assets/15956695/21618888/7c30d3c8-d1ed-11e6-99c3-a031d34003fb.png)
xD

**Comment by ZfsrGhS953** [comment]
There's a small defect on the bottom of the virus, but other than that it looks quite good.

**Comment by Luka967** [comment]
![pellets](https://cloud.githubusercontent.com/assets/15956695/21624739/7cf437f8-d208-11e6-9426-aa1b2e01ff96.JPG)
Now has full line drawing.
Also, works on Edge without major FPS drops!
![microsoft edge 1_3_2017 11_06_16 pm](https://cloud.githubusercontent.com/assets/15956695/21624902/59ecdce6-d209-11e6-98e8-539676d5afe2.png)
The biggest loser FPS-wise right now is Firefox.

**Comment by MastaCoder** [comment]
@Luka967 That explains so much of why it never worked for me. I just tried to connect through localhost or 127.. it never works. However, using my raspberry pi on a local ip: 192.168 it works fine. That's really weird.

I just got home, looking good on the progress!

**Comment by MastaCoder** [comment]
Oops ;-;

**Comment by Luka967** [comment]
![playable](https://cloud.githubusercontent.com/assets/15956695/21692621/fc78a178-d37d-11e6-8fba-3b9b206b7625.JPG)
Touches and point colliding is left.
