### ISSUE TITLE
About Smooth Render ( BUGS REPORT )

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#473]
1) - Smooth Render produces lag , in agar.io this does not happen.
2) - Smooth Render is bug , looks like a decagon.
3) - Smooth Render is slow , instead of be faster like agar.io 
4) - The smoothRender of agar.io looks like if the updatePos was 60 instead 120 as cigar. (faster) (I think this is similar to point 3)

I think this is closely linked to the zoom and position update (UpdatePos function)

**Comment by MastaCoder** [comment]
> Smooth Render produces lag , in agar.io this does not happen.

Agar.io has smooth render? I though they only had quality changing.

**Comment by HAlexTM** [comment]
They removed the smooth render

**Comment by mrzack506** [comment]
They definitely did not. It's just not an option. They made it after a certain mass/amount of cells it would enable it.

**Comment by MastaCoder** [comment]
Oh right forgot about that.

**Comment by MastaCoder** [comment]
Update on what I said. @HAlexTM is right, I'm currently spectating players with far more than 5000 mass and smooth render is not enabling.

**Comment by HAlexTM** [comment]
Agar.io scripts have changed their structure in the while, we need to understand the new sources

And @MastaCoder Agar.io, custom server 16 cells every 22k, and i can still notice the cell's points without lag (at least on my desktop)

**Comment by MastaCoder** [comment]
@HAlexTM Same on my desktop, no lag. However, on my laptop it's a nightmare.

**Comment by HAlexTM** [comment]
Idem, my laptop has 6GB ram and i5 cpu but it can't handle Agar with low graphics @MastaCoder

**Comment by MastaCoder** [comment]
Looks like we have dupes.
