### ISSUE TITLE
how can i fix this error?

### ISSUE THREAD

**Issue by coffee1209** [CigarProject/Cigar#475]
POST /checkdir 500
....i cant fix this error
help me please...haha..

**Comment by MastaCoder** [comment]
Just in case if someone else if having the issue.

1. Make sure PHP is up to date and working.
2. Verify the file exists.
3. Make sure it's checkdir.php, not just checkdir. (unless if your webserver supports this.)

**Comment by HAlexTM** [comment]
@MastaCoder for the third point, he is using the old Cigar server

**Comment by Niall7459** [comment]
what does checkdir.php do?

**Comment by HAlexTM** [comment]
It list your skins
