### ISSUE TITLE
Better code for cell border

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#477]
```
 var lw = this.size * 0.03;
                    ctx.lineWidth = lw;
                    ctx.arc(this.x, this.y, this.size - lw * 0.5 + 5, 0, 2 * Math.PI, false);

```

How to apply that border to all cells except ejected mass and points?

**Comment by Luka967** [comment]
Remove [this line](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1353)

**Comment by PsycoYT** [comment]
Perhaps the food does not have a specific id?

**Comment by Luka967** [comment]
Nope

**Comment by PsycoYT** [comment]
oh lol
