### ISSUE TITLE
how to ?

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#478]
how to draw border only to eject mass ?

if (!this.isEject) {

ctx.linewidth = 10;

}

correct? on function drawonecell?

**Comment by Luka967** [comment]
```js
if (!this.isEjected) {
ctx.linewidth = 0;
}
```

**Comment by PsycoYT** [comment]
WHY 0 ?

**Comment by Luka967** [comment]
Because you wanted no border. No border is zero.

**Comment by PsycoYT** [comment]
i want border only to ejected mass

**Comment by HAlexTM** [comment]
```javascript
if (!this.isEjected) { //everything except ejected mass
    ctx.linewidth = 0; //got no border
}
```

**Comment by PsycoYT** [comment]
where i should put this ? draw one cell ? what lines ? help me pls :)
