### ISSUE TITLE
FIX ! mouse move

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#479]
Sometimes the client does not react to the movement of the mouse ..}

In other clients like alis.io or ogarul, it does not happen to me

**Comment by HAlexTM** [comment]
This is because you modified your client/server, this doesn't happen on the default Cigar

**Comment by PsycoYT** [comment]
not modified.

**Comment by PsycoYT** [comment]
http://ogar.pw/assets/js/mt.js

**Comment by HAlexTM** [comment]
And you call this not modified?? ![http://i.imgur.com/SAOF2LA.jpg](http://i.imgur.com/SAOF2LA.jpg)

**Comment by MastaCoder** [comment]
I just checked your index.html, you're not even using mt.js...

**Comment by PsycoYT** [comment]
i using mt.js on http://ogar.pw/x.html

**Comment by HAlexTM** [comment]
I used v1.html - still modified
![http://i.imgur.com/Nr36j7v.jpg](http://i.imgur.com/Nr36j7v.jpg)

**Comment by PsycoYT** [comment]
http://ogar.pw/x.html that using mt.js

**Comment by HAlexTM** [comment]
x.html still modified...

**Comment by PsycoYT** [comment]
index 
Affect performance?

**Comment by HAlexTM** [comment]
Yes and no, but why I got "Super zoomout"??

**Comment by PsycoYT** [comment]
con o sin zoom, muchas veces no reacciona al mouse , solo debes jugar un buen tiempo.

**Comment by MastaCoder** [comment]
1. Your server latency could be bad.
2. The minimap you have added is poorly made.
3. You have a bad connection with the server.

Yeah, either of those.

**Comment by PsycoYT** [comment]
1 - with others client not happen.
2 - http://ogar.pw/x.html not have map
3 - i have good connection only happen with cigar client

**Comment by ZfsrGhS953** [comment]
It does happen to me as well (at least it did on old Cigar) about 5 minutes after opening the page. It has something to do with (this setInterval)[https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L178], because when I press W or Space (pressing them calls sendMouseMove()) the mouse position updates. Windows 8.1 x64, Chrome x64.

**Comment by Luka967** [comment]
@ZfsrGhS953 Every time you press an action key (Space, W, Q, E, R, T, P) a `SendMouseMove` is triggered. For example, for [Space](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L88):
```js
                case 32: // space
                    if ((!spacePressed) && (!isTyping)) {
                        sendMouseMove();                     // <--
                        sendUint8(17);
                        spacePressed = true;
                    }
                    break;
```
My client doesn't have this for now.

**Comment by MastaCoder** [comment]
@Luka967 On my website mine is set to send every 40ms just like Cigar is set, nobody has issues with this. I don't know if I have changed code in the sendMouse function, but I'm pretty sure I haven't.

Weird.

**Comment by MastaCoder** [comment]
Almost a week no result. Closing.
