### ISSUE TITLE
How to add ads?

### ISSUE THREAD

**Issue by dfiverr** [CigarProject/Cigar#483]
Hi, I have an adsense code, to help pay for my servers, and I see a thing called #adsBottom and #adsBottomInner in layout.hbs, but where do I paste the ad code? Thank you!

**Comment by HAlexTM** [comment]
You're using a old version of Cigar.
You need to add your code inside the [index.html#108](https://github.com/CigarProject/Cigar/blob/master/www/index.html#L108)
