### ISSUE TITLE
The hell have I done?

### ISSUE THREAD

**Issue by Luka967** [CigarProject/Cigar#484]
Sorry for this but apparently I replaced the old client with mine... xD

**Comment by Luka967** [comment]
I guess... I fixed it?

**Comment by MastaCoder** [comment]
LOL xD. Imma go make another repo and click that button now, gotta see what happens!

**Comment by Luka967** [comment]
BTW if you have time, send me the gitter invite again, I didn't get the e-mail.

**Comment by MastaCoder** [comment]
@Luka967 I can't send invites again for some stupid reason. We are planning on moving onto using Discord since it's something we both check much more often and notifications don't seem to be working for @HAlexTM.

You okay with Discord?

**Comment by Luka967** [comment]
Sure!

**Comment by MastaCoder** [comment]
@Luka967 https://discord.gg/tWkaK (Deleting this post in 500 seconds!)

**Comment by HAlexTM** [comment]
We'll just ban whoever uses it ahah

**Comment by Luka967** [comment]
I've joined, removing the comment xD
