### ISSUE TITLE
where?

### ISSUE THREAD

**Issue by PsycoYT** [CigarProject/Cigar#487]
where is the code that hide the name of skin in the game ?

**Comment by CalvinDKL** [comment]
use <SKIN> then you get the skin, and it doesn't show up on in game.

**Comment by MastaCoder** [comment]
The function is literally in front of you. Can you not just ctrl + f?

**Comment by gyeyoqu** [comment]
retards? i asked where is the function that hides the skin name

**Comment by HAlexTM** [comment]
@gyeyoqu you're the retarded here, closing as @MastaCoder provided the solution
