### ISSUE TITLE
Default Lobby

### ISSUE THREAD

**Issue by ElMay0r** [CigarProject/Cigar#488]
How i make a default lobby, i dont it to look like if the server is offline and the gamemoode tab, i want it to set the users in a lobby right when they enter dewebsite.

How i do that?

thanks.

**Comment by CalvinDKL** [comment]
Go into the main_out.js
and change line nr 2.
` var CONNECTION_URL = "127.0.0.1:443", // Default Connection`

**Comment by RelTakeover** [comment]
elmay0r contac me on facebook

**Comment by RelTakeover** [comment]
https://www.facebook.com/profile.php?id=100013177801418

**Comment by MastaCoder** [comment]
@CalvinDKL said it right.

**Comment by ElMay0r** [comment]
Didn't Worked. 

Check outmy website: www.Agar.Blue

**Comment by CalvinDKHD** [comment]
i see that you got it to work

**Comment by ElMay0r** [comment]
the game is working BUT when you enter the page it ask you to select you gamemode i want it to take you straight to the first gamemode when u enter the page.
