### ISSUE TITLE
How to position the chat?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#489]
Hey so i added another theme(bootrap theme) to the client, to see how it would look. The problem is that the chat moved a little up.
https://gyazo.com/ca10041bf2d133d364bb806a73d211ca

Where can i re-position it?

**Comment by Luka967** [comment]
[Here](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L808) is where the chat is drawn
