### ISSUE TITLE
Skin issue

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#490]
Hey
So for me skins isnt working
https://gyazo.com/ed150709b63d73fc956ff7cc8057a297
https://gyazo.com/8741c841a0a95deb0b47cf180afd6edc
https://gyazo.com/e5e0e45af8e6289ace8d6e81c1d46936

everything looks to be good...

**Comment by HAlexTM** [comment]
Are you using Wamp? Skins need PHP to work

**Comment by CalvinDKHD** [comment]
wait ohh, i didnt know they needed php.

**Comment by CalvinDKHD** [comment]
and im using xampp

**Comment by HAlexTM** [comment]
It's because the list of the skins is provided by checkdir.php

**Comment by HAlexTM** [comment]
Wait, so did you resolve?

**Comment by CalvinDKHD** [comment]
yes :)

**Comment by CalvinDKHD** [comment]
wait

**Comment by CalvinDKHD** [comment]
How do i make a 2nd input that is like the skin input.
Like you enter the skin like <doge>
https://gyazo.com/77401d105ea6f7d9d8b9ab1bfbc17f10

**Comment by HAlexTM** [comment]
You need to change the javascript function (setNick or play) to include this input

**Comment by CalvinDKHD** [comment]
NVM GOT IT!

**Comment by CalvinDKHD** [comment]
thank you for the help

**Comment by HAlexTM** [comment]
You're welcome

**Comment by CalvinDKHD** [comment]
wait

**Comment by CalvinDKHD** [comment]
isnt it like this you do it?
https://gyazo.com/91aaebfa0d72b69d6643146277c6ca68

**Comment by HAlexTM** [comment]
It can but in another way: `setNick(document.getElementById('skin').value + document.getElementById('nick').value); return false;`

**Comment by CalvinDKHD** [comment]
very cool, thanks.
