### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by RelTakeover** [CigarProject/Cigar#492]
how to put color clans? if i put in my name "zt" in the leaderbord changes the color ...

**Comment by MastaCoder** [comment]
That would involve editing where the leaderboard is rendered and checking for the test, it's actually really easy.

**Comment by RelTakeover** [comment]
Please help me, I am learning javascript and I am looking for it a long time ago.

**Comment by HAlexTM** [comment]
Ask to StackOverflow (or better, Google) for these type of JavaScript problems
