### ISSUE TITLE
How did you fix the leaderboard issue?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#493]
Hello!
I saw that you fixed this bug
https://gyazo.com/92aff5d6d66a5b6af134485f4e622fb4

on cigar. I dont know how you fixed it, could anyone tell me?

**Comment by ItzLevvie** [comment]
https://github.com/CigarProject/Cigar/commit/481103a69798c6ec08525032000681984fcfd1dd

**Comment by CalvinDKHD** [comment]
thanks
