### ISSUE TITLE
How did you guys fix the skin resize issue?

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#495]
Hello, so the title says it.
I am asking how you fix this issue -
https://gyazo.com/4e979211c8d313602bc546fb619e9a3a

cedrsgaming made an issue on this, and then someone says. Fixed closing issue.
And i cant find the commit.

Thanks!

**Comment by HAlexTM** [comment]
Browse thought the latest commits

**Comment by CalvinDKHD** [comment]
got it!

**Comment by ItzLevvie** [comment]
Btw if you want more skins then 

Free Skins : https://github.com/ItzLevvie/Agario-skins/releases/download/1.0/Free.Skins.zip

Premium Skins : https://github.com/ItzLevvie/Agario-skins/releases/download/1.0/Equippable.Skins.zip

**Comment by MastaCoder** [comment]
How? 😲

**Comment by CalvinDKHD** [comment]
ahh i see ok

**Comment by CalvinDKHD** [comment]
i fixed it btw

**Comment by CalvinDKHD** [comment]
now i just need to fix the problem that the client doesn't work on other
browsers than chrome.
