### ISSUE TITLE
Cell border

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#496]
Hello!
So i did so people can zoom out more.
but when you zoom out just a little the border disappears
https://gyazo.com/90cd9baf4d18b340a69e20812a832a74

Anyone know if i can change that??
thanks

**Comment by HAlexTM** [comment]
I can't understand your problem, please explain better

**Comment by Luka967** [comment]
Well of course the cell borders are going to disappear if you go to really large zoom-outs. This is natural behavior even to agar.

**Comment by CalvinDKHD** [comment]
im just asking if you could keep em.
Like when you zoom out it increases the size

**Comment by Luka967** [comment]
Very performance-costly

**Comment by CalvinDKL** [comment]
alright, dw then.
thanks

**Comment by MastaCoder** [comment]
@Luka967 lmao Moneyclip made their game not take the borders off after zooming out. Really really stupid idea.
