### ISSUE TITLE
virus ?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#497]
Hi,
in order to avoid copyright issue ... is it possible to change the virus shape ?
something like the picture attached will be awesome :)
![virus](https://cloud.githubusercontent.com/assets/6823974/22221875/fd572c1e-e1b4-11e6-9128-27367bb062a5.png)

**Comment by HAlexTM** [comment]
There is no copyright for the virus shape or color

**Comment by matrixreal** [comment]
@HAlexTM 
i was contacted by Agar.io Team asking me to change the virus color and shape ... so that's why

**Comment by Luka967** [comment]
Hmm funny from them. How many players do you have daily?
If you really opt for a different virus shape you need to get quite a lot of code edits. Can't help you right now but can tomorrow

**Comment by matrixreal** [comment]
about 1000 players ...
it's okay for tomorow

**Comment by CalvinDKL** [comment]
Dude, agario can't do that.
Agario can't claim circles with spikes on them WTF.
and then can't claim the colour green.

**Comment by CalvinDKL** [comment]
And pls send me ur website i wanna see it 👍

**Comment by CalvinDKL** [comment]
but what you could do is to make it a circle. Like alis.io did

**Comment by ZfsrGhS953** [comment]
@matrixreal I'm almost sure it's someone impersonating them rather than Moneycrap. I don't think that they're smart enough to DMCA you for that.

**Comment by HAlexTM** [comment]
@ZdsrGhS953 ahahah, agreed.

**Comment by CalvinDKHD** [comment]
yeah lol

**Comment by matrixreal** [comment]
here is website http://216.59.16.52:88/
i will send you their dcma later

**Comment by ZfsrGhS953** [comment]
@matrixreal From where did you get it? If it wasn't from your hosting company email, just ignore it.

**Comment by matrixreal** [comment]
from apple team / Agar.io Team and they removed my game from sale ... and the game was on the top 100 us appstore

**Comment by MastaCoder** [comment]
@matrixreal I'm pretty sure they won't just remove a game because of a virus color. They removed it because it was a straight copy from the Agar.io. There are many more websites I've seen larger than your site (because right now you only have 34 players playing, even my own website gets almost 6 times that amount). You were taken off of the app store because you're just running your website through some browser and calling it an app, not many people do that thus making you pretty much one of the main targets of moneyclip.

You're websites not down, so it wasn't from the web hosting. It's mostly because you brought attention from Miniclip since you were pretty much the only Agar.io clone on the app store actually rising on the charts.

**Comment by matrixreal** [comment]
@MastaCoder 
yes you got reason ... the website is still runing ... the only ios app is removed from appstore
they asked me to : change virus shape , circles food , and remove grid from backgrounds
and yes .... i use a wrapper wich browse the website version and that's normal

**Comment by CalvinDKHD** [comment]
They can't tell you to remove the grid, they can't claim lines/squares.
Cmon this is just nonsense!

**Comment by matrixreal** [comment]
@CalvinDKL 
yes ... but apple did listen to them ... and now i do the appropriate changes except the virus
i send them a message and to apple too ... but they did not reply ... they don't care since i don't have much power :(

**Comment by matrixreal** [comment]
any news?
thanks in advance

**Comment by HAlexTM** [comment]
No, we said everything

**Comment by matrixreal** [comment]
@HAlexTM 
so i can't change the shape of the viruses?

**Comment by HAlexTM** [comment]
You can, but we (or better, me) are not going to do that for you

**Comment by matrixreal** [comment]
@HAlexTM 
you can show me how to please?
thanks in advance

**Comment by HAlexTM** [comment]
So you just asked me to tell you how to do that...

**Comment by Luka967** [comment]
@matrixreal alright sorry for not responding, I've completely forgot to check back on this.
Give me 10 minutes to figure out the easiest way to draw the virus as an image.

**Comment by Luka967** [comment]
shit didn't mean to close

**Comment by matrixreal** [comment]
@HAlexTM
@Luka967
thanks a lot
waiting for :)

**Comment by Luka967** [comment]
[main_out.js, line 1324](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1324)
replace the line with this:
```js
var b = (0 != this.id && !this.isAgitated && smoothRender > viewZoom);
```

[line 1031](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1031)
replace this line:
```js
        noRanking = false;
        virusIcon = new Image;
    virusIcon.src = /* add location of the virus image here */;
```

[line 1386](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1386)
add this:
```js
                if (isVirus) c = virusIcon;
```

Not tested if works but it should in theory.
Reply if there's an error.

**Comment by matrixreal** [comment]
line1386 ? replace with this ? if (isVirus) c = virusIcon;

**Comment by Luka967** [comment]
After the `}` add that code;
```js
...
                } else {
                    c = null;
                }
                if (isVirus) c = virusIcon;
                b || ctx.stroke();
                ctx.fill(); //Draw cell content
...
```

**Comment by matrixreal** [comment]
@Luka967 
Hi,
i do exactly what you say but it seem to not work
i got white screen with chat box


[main_out.zip](https://github.com/CigarProject/Cigar/files/765964/main_out.zip)

**Comment by Luka967** [comment]
![image](https://cloud.githubusercontent.com/assets/15956695/22826126/0c2ee422-ef91-11e6-9701-0a9f745258b0.png)
```js
   else {
                    c = null;
                }
```
Seems like this is causing errors. Remove this.

**Comment by matrixreal** [comment]
@Luka967 
are you sure ?
cause i did a try and it still same

**Comment by matrixreal** [comment]
@Luka967 
any news please :( ?
thanks in advance

**Comment by matrixreal** [comment]
![viruserror](https://cloud.githubusercontent.com/assets/6823974/22856471/15c069b4-f092-11e6-827b-ce81bfa7ecd3.png)

**Comment by ItzLevvie** [comment]
Try ```this.isVirus``` instead of ```isVirus```

**Comment by matrixreal** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/6823974/22857074/4ef80cee-f09e-11e6-98d0-3c80ebe734ba.jpg)

**Comment by matrixreal** [comment]
still got same problem :(

**Comment by MastaCoder** [comment]
http://bfy.tw/AuKs

**Comment by matrixreal** [comment]
:)
