### ISSUE TITLE
How to make never dissapaer border of cell?

### ISSUE THREAD

**Issue by AlexGallegos908** [CigarProject/Cigar#499]
tittle

**Comment by HAlexTM** [comment]
If you use this project, why don't you learn programming?

**Comment by CalvinDKL** [comment]
I've made an issue about this before, if you try to do this you will only get to experience more lag.

**Comment by AlexGallegos908** [comment]
@CalvinDKL Im want the border. the lag im dont care

**Comment by HAlexTM** [comment]
@AlexGallegos908 You can learn programming if you want to run a website based on a project and modify it
