### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#50]
@m-byte 
it will be funny if you add small sound effects when you eat / spawn / game over / start game
i have attached a link with complete sound effects you can take a look and it will be awesome if you add them to the repo
thanks
https://www.dropbox.com/s/5n7sz4cc9xzyn85/agar%20sounds.zip?dl=0

**Comment by matrixreal** [comment]
@m-byte 
any news ?

**Comment by m-byte** [comment]
@matrixreal sorry for letting you guys wait this long. I am currently swamped with work. I started a merge with the latest version of Ogar a week ago, but while I was working on it, the hdd of the laptop I used broke. Hopefully, I'll be able to redo the merge by the end of next week.

**Comment by matrixreal** [comment]
@m-byte 
thats okay ... we are waiting :dancer: 
anyway thanks

**Comment by MastaCoder** [comment]
This could be easy to add.
