### ISSUE TITLE
skin problem

### ISSUE THREAD

**Issue by dark84s** [CigarProject/Cigar#500]
Hello, after choosing skin, the nick changes.
When user selects skin
Do not have the ability to use their own nick?

**Comment by CalvinDKHD** [comment]
yes

**Comment by CalvinDKHD** [comment]
but they could add < & > around the skin name so the skin name doesn't
show, but the bit that isn't surrounded by the < & > still shows.

**Comment by dark84s** [comment]
28/5000
I do not understand much without coding :(

**Comment by CalvinDKHD** [comment]
Its not coding lol

**Comment by CalvinDKHD** [comment]
ok, here.
For example players could use <Kraken> Dark84s    in the nickname box

**Comment by MastaCoder** [comment]
Have the user write their name after the skin name with <> around the skinname.
