### ISSUE TITLE
Changing the color of a certain nickname on the leaderboard.

### ISSUE THREAD

**Issue by CalvinDKHD** [CigarProject/Cigar#501]
The title says it.
For example the nickname "test" would have a blue color to it. Which everyone can see.

**Comment by gyeyoqu** [comment]
require protocol modifications.

**Comment by MastaCoder** [comment]
@gyeyoqu No it wouldn't. Just add an if statement for the name and change the color is the easiest way to do it.

**Comment by CalvinDKL** [comment]
ill try :)
thanks

**Comment by CalvinDKL** [comment]
Sorry for giving a late response
I tried this
https://gyazo.com/73cce8808f87fda9bc546526369b78b7

But even though you dont use calvin as your name, it still changes to the set color.

**Comment by MastaCoder** [comment]
You added another if statement inside of an if statement.

It'd be something like:
```javascript
if (name == "calvin") {
    ctx.fillStyle..
}

**Comment by Y4ssine** [comment]
@MastaCoder  hey sorry for bothering 
but i'm noob in js can u tell me how to color nicks in the lb ?
*without telling me easily add the if statement bla bla bla *
because i'm 0 at javascript just tell me which code goes on which line :D ty ;)

**Comment by CalvinDKHD** [comment]
You learn more by kind of figuring it out your self

**Comment by Y4ssine** [comment]
calvin can you please help me :)  i just don't know javascript can you please tell me what have you done :) ty

**Comment by RevengePlayz** [comment]
@CalvinDKHD add me on discord Revenge#5285 you will be buzzing after what i tell you!

**Comment by MastaCoder** [comment]
Please don't bump old topics with useless information and requests.
