### ISSUE TITLE
No more this.cellType?

### ISSUE THREAD

**Issue by deniskrop** [CigarProject/Cigar#502]
I used to be able to use the property this.cellType in drawOneCell in main_out.js to be able to tell what type of a cell that a cell is (player, food, or virus) but that was taken out. How can I do it now?

**Comment by Luka967** [comment]
No more of these. You only have [isVirus, isAgitated and isEjected](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1165-L1167) that come from cell flags.
