### ISSUE TITLE
Client doesnt run with 'uws'

### ISSUE THREAD

**Issue by deniskrop** [CigarProject/Cigar#503]
When I switch the server to use the 'uws' the client breaks and looks like this 

<img width="1404" alt="screen shot 2017-01-27 at 01 37 54" src="https://cloud.githubusercontent.com/assets/23563565/22366393/486c426a-e431-11e6-8161-670f613a4a19.png">

**Comment by deniskrop** [comment]
Any suggestions?

**Comment by HAlexTM** [comment]
Why are you using a nonexistent protocol? Use ws

**Comment by Luka967** [comment]
UWS is buggy server-side.
