### ISSUE TITLE
How to make a connection with Miniclip (skins)

### ISSUE THREAD

**Issue by AlexByte918** [CigarProject/Cigar#504]
In this image you see a fan made (client) of agar.io,
In this client you can see your own skins,
Image:
http://i.imgur.com/DCmjqIB.png

In the config are some like to this

`var url = "https://configs-web.agario.miniclippt.com/live/v5/271/";
var configFile = "GameConfiguration.json";
var config = JSON.parse(httpGet(url + configFile));
function httpGet(theUrl) {
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open("GET", theUrl, false); // false for synchronous request
    xmlHttp.send(null);
    return xmlHttp.responseText;
}

MC.getSkinInfo = function (a) {
    var skinName = a;
    var imageName = "";
    var color = "244,441,222";

    var skinArray = config["gameConfig"]["Gameplay - Equippable Skins"];

    for (var i = 0; i < skinArray.length; i++) {
        if (skinArray[i].productId == skinName) {
            imageName = skinArray[i].image.substring(0, skinArray[i].image.length - 4);
            imageName += "_hi.png";
            color = skinArray[i].cellColor.substring(0, skinArray[i].cellColor.length - 2);
            return { url: url + imageName, color: color };
        }
    }
}

function inject()
{
    $('h2').html("JoseFredo");
    $('#settings').after("<span id='version-tag'>(v72 : Extension by NuclearC & DrGoat)</span>");
    $("#nick").attr('maxlength','50');
    document.title = 'JoseFredo.tk';

    window.v72.hooks.drawCellMass = function(cell, old_draw) {
        if(cell.size > 20) return cell;   
    }
	window.v72.drawGrid = false;
}
console.log("Succsesful")
inject();
</script>`

Im want to put this skins in cigar master, but im cant

**Comment by gyeyoqu** [comment]
is agario v72 client ;-;

**Comment by HAlexTM** [comment]
This looks like an extension for the original client, you can't use Miniclips servers, closing this issue unless owner can prove I'm wrong

**Comment by SAV-404** [comment]
**PLZ HELP**
how abt changing the GameConfiguration.json file's direction to my local computer.

**Comment by zettabyte918** [comment]
lol u can xDDDDD btw i make my own stroke color rule its look something like this :3 
`function cellcolor(l) {
    return "Kraken" == l ? "#00470e" : "Shark" == l ? "#002861" : "Cougar" == l ? "#700001" : "T-Rex" == l ? "#700001" : void 0
}
this.id && (a.strokeStyle = cellcolor(c), a.fillStyle = cellcolor(c));`

**Comment by zettabyte918** [comment]
![qq](https://user-images.githubusercontent.com/18426424/51540334-75917b00-1e56-11e9-90c9-fbee8d72dc30.PNG)

**Comment by SAV-404** [comment]
u got more than **300** skin, typing all their names and finding their stroke color is gonna cost a lot of work, u should make it somehow related with a **json** file which it already exists (i got it), it has the skin names & their own stroke color, and after u'll need to use the **XMLHttpRequest** method to be able to use ur **json** file, the script already exists, but it's for **v72**, _u'll have to make some changes to make it work for cigar project_, u're not gonna be able to use the skins from the **original source**, u can download them i guess, so that's gonna make it easier to use and without internet, **we have to talk abt that on Discord**.

**Comment by zettabyte918** [comment]
https://configs-web.agario.miniclippt.com/live/v12/1938/GameConfiguration.json ik but i want to make my own work here :3

**Comment by hossemThecoder** [comment]
ur discord btw ??

**Comment by zettabyte918** [comment]
ur discord btw ?? @SAV-404

**Comment by SAV-404** [comment]
it's **Rain 雨#8795**
