### ISSUE TITLE
the skins name problem 

### ISSUE THREAD

**Issue by Y4ssine** [CigarProject/Cigar#505]
hi guys i have the normal skins can be deployed with  the name only 
how ever i've seen some people who have fixed that ☺  such as @CalvinDKHD :+1: 

so can he , or any body help me to fix that ? 
 i'm not good with Js :-1:  ;)

**Comment by gyeyoqu** [comment]
<skin>

**Comment by Y4ssine** [comment]
no man i want to make users choose from the gallery any soulution ? @gyeyoqu

**Comment by MastaCoder** [comment]
This is already implemented. Simply make it add ```<>``` into the name.
