### ISSUE TITLE
Skins help ? 

### ISSUE THREAD

**Issue by Y4ssine** [CigarProject/Cigar#506]
i have nearly 1200 Skin in my site and if a user wants to get a skin from the gallery he has to play with the name of the skin and most of them are random names like " 0SxZXlst.png"
 any way to make the user play without the skin name as his blob name ? 
i belive some ppl have done it 
@Megabyte918

**Comment by CalvinDKHD** [comment]
Maybe you could try to make a set skin function?

**Comment by MastaCoder** [comment]
The packet for <skin> has already been added. Just pass forward the <skinname> player name.

**Comment by Y4ssine** [comment]
but if i have 100 user at my site how do i force them to do that is theree any code to add that ? @MastaCoder

**Comment by Y4ssine** [comment]
what code do i need to add can you help me out please ?
