### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by RasyiidWho** [CigarProject/Cigar#508]
![untitled](https://cloud.githubusercontent.com/assets/19422415/22493754/9aca16d6-e864-11e6-8919-d884e2231122.png)

**Comment by HAlexTM** [comment]
Today it's my birthday, so I'll just be honest with you: dude, you're running a website, a custom one, you modified buttons with HTML and CSS, if you don't know JavaScript, try to learn it and if you're getting problems ask to StackOverflow, not here!

**Comment by Megabyte918** [comment]
Happy birthday mate :tada:

**Comment by HAlexTM** [comment]
Thanks @Megabyte918 !!

**Comment by CalvinDKHD** [comment]
yh, happy bday :)
How that you have gotten good gifts!

**Comment by CalvinDKHD** [comment]
Guys, ill take my time today to make a full tutorial on this, cuz i am
tired of seeing people who all ways ask this.

**Comment by HAlexTM** [comment]
@CalvinDKHD thanks but usually I don't celebrate my d-day XD

**Comment by RasyiidWho** [comment]
thanks @CalvinDKHD 
@HAlexTM sorry, im noob in js. This is local site too..

**Comment by CalvinDKL** [comment]
Lol ur d-day xD

**Comment by Luka967** [comment]
@RasyiidWho 
find this function in main_out.js:
```js
   wHandle.setNick = function(arg) {
        hideOverlays();
        userNickName = arg;
        sendNickName();
        userScore = 0
    };
```
replace
```js
userNickName = arg;
```
with this:
```js
userNickName = "<" + document.getElementById("<id for skin textbox here>") + "> " + arg;
```

**Comment by RasyiidWho** [comment]
thanks :D

**Comment by Luka967** [comment]
wait shit
replace it with this:
```js
userNickName = "<" + document.getElementById("<id for skin textbox here>").innerHTML + "> " + arg;
```
forgot to add `.innerHTML` xD

**Comment by RasyiidWho** [comment]
@Luka967 

![1](https://cloud.githubusercontent.com/assets/19422415/22508915/98b44b64-e8be-11e6-9a33-bc8b2f4aadbb.PNG)
![2](https://cloud.githubusercontent.com/assets/19422415/22508924/9d1dd8a0-e8be-11e6-8cd6-c9dc3328a28a.PNG)
![3](https://cloud.githubusercontent.com/assets/19422415/22508927/a01f07ea-e8be-11e6-89af-c69f6cf151c7.PNG)
![4](https://cloud.githubusercontent.com/assets/19422415/22508939/a27d9c18-e8be-11e6-8688-f1e53aae4330.PNG)

**Comment by Luka967** [comment]
I see that there isn't any problem, it's probably the server that's hiccuping.
Instead of `"<"` and `"> "` try using `"{"` and `"} "`

**Comment by MastaCoder** [comment]
@Luka967 For a textbox it's .value, not .innerHTML lol.

**Comment by Luka967** [comment]
xD

**Comment by Luka967** [comment]
rip my knowledge of DOM html

**Comment by RasyiidWho** [comment]
@MastaCoder @Luka967 Thanks :D

![capture](https://cloud.githubusercontent.com/assets/19422415/22530047/89316228-e90c-11e6-867b-cdd30a961aca.PNG)

**Comment by malekksa505** [comment]
http://e.top4top.net/p_438rb8if1.png
http://f.top4top.net/p_438gx6yg2.png
http://a.top4top.net/p_438rfo9o3.png
http://b.top4top.net/p_438t8er24.png


.. 
did not work,,, what is the reason ?



@RasyiidWho @HAlexTM @Luka967 @MastaCoder

**Comment by HAlexTM** [comment]
Don't. Tag. Me.

**Comment by malekksa505** [comment]
Please Help Me

**Comment by malekksa505** [comment]
@RasyiidWho @Luka967 @MastaCoder

**Comment by Luka967** [comment]
I think it's `value` instead of `innerHTML`.
@MastaCoder i forgot xdddddd

**Comment by malekksa505** [comment]
@Luka967

http://e.top4top.net/p_438rb8if1.png
http://f.top4top.net/p_438gx6yg2.png
http://a.top4top.net/p_438rfo9o3.png
http://b.top4top.net/p_438t8er24.png

..
did not work,,, what is the reason ?
