### ISSUE TITLE
Player name class on cell

### ISSUE THREAD

**Issue by matthewaptaylor** [CigarProject/Cigar#509]
Is there a css class on the text of the player's name? I.E, when I press "Play", my cell that I can move around with my mouse, does the text on that have a CSS class attached to it?

**Comment by MastaCoder** [comment]
You can't really attach CSS to canvas objects. You can alter them when they are being created, but you can't attach normal CSS classes to it.

**Comment by Niall7459** [comment]
It is draw using in the main_out.js using ctx, You can probably find it around the following area https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1404
