### ISSUE TITLE
what about make log file?

### ISSUE THREAD

**Issue by Ganggroid** [CigarProject/Cigar#51]
Chat log, connect log and another!
plz.!

**Comment by happyhg3927** [comment]
PLZ!!!!

**Comment by matrixreal** [comment]
what you mean by chat log ?

**Comment by MastaCoder** [comment]
A log that shows every message, connection, etc. I'll see if I can do this.

**Comment by tveloper** [comment]
Yup. I was going to ask for this too.
@MastaCoder wow your work is fantastic. 

Wows from South Korea.

**Comment by MastaCoder** [comment]
That you :+1: @tveloper
