### ISSUE TITLE
ios Problem

### ISSUE THREAD

**Issue by dark84s** [CigarProject/Cigar#511]
I tried to enter the script te with the iPhone 6s.
The window does not come.
Mobile iOS also has a problem.

**Comment by iamtaeuk** [comment]
This is NOT an iOS app, this is a web app.
You must host this on a server capable of PHP.

If hosted, than use Safari/Chrome whatever browser you use and go to that website.

**Comment by matrixreal** [comment]
@dark84s 
it not work on safari iphone browser
try to use chrome / mozilla browser
