### ISSUE TITLE
"An unnamed cell" Skin

### ISSUE THREAD

**Issue by matthewaptaylor** [CigarProject/Cigar#514]
Is there any way to add a skin by default, to a player with no name?

**Comment by Niall7459** [comment]
you should be able to change sendSkin on the player join, check if it is undefined/null or = ""

**Comment by Luka967** [comment]
[main_out.js, line 1039](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L1039)
replace the line with this:
```js
userNickName = arg || /* insert skin here enclosed in either {} or <> */;
```

**Comment by Niall7459** [comment]
Matthew please stop copying my ideas....
And why have you got "**nagar.io nagar ETC**" In your metadata **TAG FOR YOUR SITE???**
Please remove them
