### ISSUE TITLE
Can you plz explain me this,

### ISSUE THREAD

**Issue by Crypton918** [CigarProject/Cigar#516]
Im want to you explain me WATH ARCHIVE IM MODIFIED, no how. plz, im modified main out?, vector?, index? plz tell me (#515 #512)

**Comment by Luka967** [comment]
*sigh*
[One of the first line of `assets/js/main_out.js` is this one](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L3):
```js
        SKIN_URL = "./skins/"; // Skin Directory
```
MastaCoder told you to change it to this in a very simple way:
```js
         SKIN_URL = "https://configs-web.agario.miniclippt.com/live/v5/450/";
```
