### ISSUE TITLE
Server messages HTML

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#520]
Hello, title says it.
How would i make a part of a message a hyper link?
https://gyazo.com/6675b63ca701eece2736150d6ca26b56
i have done that so far, but i am not sure 

i have added the `chatTwitterText`

**Comment by CalvinDKL** [comment]
how about this?
`var chatText = new UText(18, '#666666');
			var chatTwitterText = new UText(18, '#84f6ff');
            chatText.setValue(':' + chatBoard[i + from].message);
			chatTwitterText.setValue('Follow us on <a href="http://agarup.us/">Twitter!</a>');
            a = chatText.render();
			aTwitter = chatTwittweText.render();
            ctx.drawImage(a, 15 + width * 1.8, chatCanvas.height / scaleFactor - 24 * (len - from - i));
			ctx.drawImage(aTwitter);
        }
    }`

**Comment by CalvinDKL** [comment]
https://gyazo.com/daef17abe4c3365bbf9e7ec99d29ec10
that happens if i use that code

**Comment by CalvinDKL** [comment]
This happens now
https://gyazo.com/47871c31360942db12ae51de466f5861
A new one appears each time someone types a message. Isnt that because of the packet number?

**Comment by HAlexTM** [comment]
You CANNOT use HTML inside a canvas, you'll need to add a event listener for click events on the chat

**Comment by CalvinDKL** [comment]
alright, can you tell me what event the server messages is??

**Comment by HAlexTM** [comment]
No, you need to add a click event, not a message event

A "server message" event for chat just doesn't exist

**Comment by CalvinDKL** [comment]
ahh, wait so when someone clicks play the message displays??

**Comment by CalvinDKL** [comment]
`onclick="setNick(document.getElementById('nick').value).addEventListener('click', displayTwitterChatMSG);"` ??

**Comment by CalvinDKL** [comment]
Would i then add a function? or can i add a var that displays?

**Comment by HAlexTM** [comment]
Open a StackOverflow account and add a question, write in "Add an event listener to the canvas to open a link" for the title
On the message write "I need to add an event listener so that when someone clicks on this text it opens a link" and add your code + some image

**Comment by CalvinDKL** [comment]
My code? do you mean the whole mainout, because i havent coded anything on it.

**Comment by HAlexTM** [comment]
Closing because not related to the project / user removed the repository backlink

**Comment by HAlexTM** [comment]
Not the whole file, just the code that you used to write the message

**Comment by Luka967** [comment]
You'll need to make a canvas element with the link written on it, put an `onclick` event that opens a new page, move it along the chat canvas when new messages appear, make sure the chat text doesn't overlap that canvas and append the canvas onto the document.

**Comment by CalvinDKL** [comment]
Ohh, i dont have that xD

**Comment by CalvinDKL** [comment]
Luka i want it all to be in one page, and not to be seperate files.

**Comment by Luka967** [comment]
You can also try the `textarea` element or find something similar to what gota.io's chat.

**Comment by CalvinDKL** [comment]
Luka it would be amazing if it was like a message, so it isnt complicated.

**Comment by CalvinDKL** [comment]
like Germs.io

**Comment by HAlexTM** [comment]
Good work @Luka967 and Good luck @CalvinDKL, good bye.

**Comment by Luka967** [comment]
![image](https://cloud.githubusercontent.com/assets/15956695/23330869/a3b555f4-fb5a-11e6-8f67-707857f8045c.png)
![image](https://cloud.githubusercontent.com/assets/15956695/23330875/da83f838-fb5a-11e6-8a94-35574305ebfc.png)
germs.io uses element injections.

**Comment by CalvinDKL** [comment]
Ohh, lol. Never knew.
But can we clarify which files needs to be coded on for this to work? the mainout only?

**Comment by Luka967** [comment]
index.html, index.css and main_out.js. You'd be better off with a special file just for the chat to make code readable.

**Comment by CalvinDKL** [comment]
yeah, but does the chat need to be completely recoded them?!

**Comment by Luka967** [comment]
Everything expect the packet handling.
gota.io uses element injections too.

**Comment by CalvinDKL** [comment]
well, that was the end of a beautiful thought!
Thanks though

**Comment by CalvinDKL** [comment]
I thought that this would be muuucchhh easier.
