### ISSUE TITLE
Adding your own leaderboard position if you are not on it

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#521]
Example:
https://gyazo.com/03bb6d206027a815fc8fbd74b1d104f9

I kind of know how to do this, but. There is something that i dont know how to do.
I am working with `if (!noRanking)`, and i am just wondering how you add another leaderboard rank.
I was thinking of it being like this, if no ranking then add another leaderboard rank with the cells name and leaderboard position.

Sorry if its unclear!

**Comment by Luka967** [comment]
Requires protocol modifications.
Easiest way I can think of is complicated too xd

**Comment by CalvinDKL** [comment]
hahahahah

**Comment by MastaCoder** [comment]
We could use the new protocol, but then again we're too lazy to make it work ;-;

**Comment by CalvinDKHD** [comment]
hahahaha
