### ISSUE TITLE
Chat background

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#525]
Hello! so i would like to know how to give the chat a background, i tried my self with no luck.

This is an example of what i want
https://gyazo.com/8369576f7ac90b3928b14a524ddc667e

Cant i use
`chatCanvas.backgroundColor = "black";`
and maybe change the opacity?

**Comment by aqweqwel123** [comment]
Hey man its me alex_ playzz ur old skype friend my new skype is ccbots.cf or my old 1 split.run add me ill try to help code it.

**Comment by aqweqwel123** [comment]
@CalvinDKL

**Comment by CalvinDKL** [comment]
Im still open for help btw.
