### ISSUE TITLE
Login system. Can someone make it?

### ISSUE THREAD

**Issue by CiMFULL** [CigarProject/Cigar#526]

**Comment by CiMFULL** [comment]
Abs0rb.me use this https://github.com/MastaCoder/MyUsers login system, but idk how XD

**Comment by CalvinDKL** [comment]
I tried using this, but i am getting an error.
I posted the error on MyUsers issues page.

**Comment by MastaCoder** [comment]
That's the very very very base of a login system. I remade the whole thing so that it works with abs0rb.me :3 

Currently remaking it even more, don't think it'll ever be supported by CIgar. Yet.
