### ISSUE TITLE
Skin gallery issue

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#527]
Hello! So when i try to open the skin gallery this happens 
https://gyazo.com/5f47462bd56da08702c38805228da3d4

Help? Thanks!

**Comment by MastaCoder** [comment]
Probably a lag from your server getting the files to it outputting them. Try locally, if that works then you might want to switch server locations.

**Comment by CalvinDKL** [comment]
Even if i upload it to a webhost it still doesnt work.
I uploaded it here / http://agarup.us/test/

**Comment by CalvinDKL** [comment]
Local doesnt work either

**Comment by MastaCoder** [comment]
Use a fresh copy of Cigar, we can't really help with this too edited.

**Comment by CalvinDKL** [comment]
Ok, so a fresh copy of cigar worked! BUT, i have checked the code! Nothing wrong!

**Comment by CalvinDKL** [comment]
FIXED, i found out that it was a problem with bootstrap.min.js

**Comment by MastaCoder** [comment]
oops ;-;
