### ISSUE TITLE
Skin modal issue *UPDATE

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#528]
Hey!
Masta, just to update you on the issue.
![c32d492dc91e7f6a4f694a2908a12174](https://cloud.githubusercontent.com/assets/23283642/23525002/3e0603ca-ff8d-11e6-8f9a-1d0728a0578c.png)

**Comment by MastaCoder** [comment]
we still see closed issues lol

**Comment by CalvinDKL** [comment]
ohh lol k
