### ISSUE TITLE
[BUG] Client incompatible with some browsers [Critical impact]

### ISSUE THREAD

**Issue by AdaptCharm** [CigarProject/Cigar#529]
A lot of tests has been conducted and I can confirm that the Cigar client does not work in some browsers.

I have not tested every single browser, but here's a list of those I have tested so far.

The client is fully functional in:
- Google Chrome
- Mozilla Firefox

The client is NOT functional in:
- Microsoft Edge
- Safari

From my observations, I suspect that there is something wrong with the canvas.

Please investigate and look into this issue as soon as possible.

**Comment by CalvinDKHD** [comment]
Hey Jamie, i have already made an issue on this :)

**Comment by MastaCoder** [comment]
Duplicate. (Thanks for letting us know the browsers, Edge doesn't seem to be a problem with the canvas however. WS looks like it's not wanting to connect.)

**Comment by CalvinDKL** [comment]
THe issue with WS was fixed in the recent Multiogar-edited update.
