### ISSUE TITLE
I have a problem in index cigar - Bootstrap Tabs

### ISSUE THREAD

**Issue by malekksa505** [CigarProject/Cigar#531]
Hello ,

Iam added Code Bootstrap Tabs down title cigar - master ,

I want examples you through Bootstrap Tabs Which are placed in the title 

            <form role="form">
                <div class="form-group">
                    <center><img src="aa.png" alt="agararab"></center>
                </div>
				
				<div><ul class="nav nav-pills">
  <li class="active"><a href="#">Home</a></li>
  <li><a href="#">Menu 1</a></li>
  <li><a href="#">Menu 2</a></li>
  <li><a href="#">Menu 3</a></li>
</ul></div>

                <div class="form-group">
                   <b><input id="nick" class="form-control save" data-box-id="0" placeholder="Nick" maxlength="24" /></b>
                    <select id="gamemode" class="form-control" onchange="setserver($(this).val());" required>
                        <option selected disabled>FFA</option>

I want you examples from around the Bootstrap Tabs in the index cigar

**Comment by MastaCoder** [comment]
https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_comp_dropdown-menu&stacked=h

**Comment by Y4ssine** [comment]
there must be a JS script 
it wont work only with html tho 
read this might help you http://getbootstrap.com/javascript/#tabs

**Comment by malekksa505** [comment]
Thx MastaCoder
ومشكور اخوي ياسين

**Comment by MastaCoder** [comment]
No problem 😄

**Comment by Y4ssine** [comment]
@malekksa505  العفو ياحبيبي 
عندك ديسكورد ؟

**Comment by malekksa505** [comment]
@Y4ssine
هلا والله منور تقدر تكلمني سكايب او ديسكورد :)

sKY : malekksa505
DisCord : https://discord.gg/S7rMP

**Comment by Y4ssine** [comment]
@malekksa505  رسل الديسكورد مره ثانيه الدعوه انتهت !

**Comment by malekksa505** [comment]
https://discord.gg/UrXjVEf
