### ISSUE TITLE
Skins don't work anymore

### ISSUE THREAD

**Issue by matthewaptaylor** [CigarProject/Cigar#532]
Even when the player types in <skin>Nick the cell does not display. I've looked at the code, tried different browsers, even computers running different Operating Systems.

Help!

**Comment by MastaCoder** [comment]
What server are you using?

**Comment by CiMFULL** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/issues/625

**Comment by matthewaptaylor** [comment]
MultiOgar-Edited @MastaCoder 
Turns out other players can see your skins, except you. Even them, only some of people's cells show skins.

**Comment by Unai144** [comment]
@matthewaptaylor 
Happens the same to me

**Comment by MastaCoder** [comment]
It was fixed in the latest commit for m-ed.
