### ISSUE TITLE
how can i add extra zoom and add my macro script to the game  

### ISSUE THREAD

**Issue by plazo123** [CigarProject/Cigar#534]
please tell me thx
plazo..

**Comment by CalvinDKL** [comment]
@MastaCoder Made a macro script
Edit the zoom here
https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L730
(you might have to play around with the function)

**Comment by MastaCoder** [comment]
I made a macro script? I don't remember lol. (To get macros, just add the same flag and remove checking for spacePressed or wPressed.

**Comment by Y4ssine** [comment]
isn't this the macro ? https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/scripts/AgarMacros.js ??!?!

**Comment by MastaCoder** [comment]
It won't work on Cigar, I think. (Well it wasn't made to work with Cigar!)
