### ISSUE TITLE
no names or skins !

### ISSUE THREAD

**Issue by Y4ssine** [CigarProject/Cigar#535]
i'm getting no names or skins when i link my server to a cigar client ! 
![image](https://cloud.githubusercontent.com/assets/25416932/23583301/a4482d50-0151-11e7-96c7-2b3e5a728f29.png)

http://omar-me.ga 
i also tried a client that looks like agarplus still nulls

**Comment by Y4ssine** [comment]
i'm 100% this prob is from the cigar client

**Comment by MastaCoder** [comment]
Are you using anything other than MultiOgar?

**Comment by Y4ssine** [comment]
no not at all

**Comment by Y4ssine** [comment]
i tried cigar with someone's else server it worked fine i think this is server sided !

**Comment by MastaCoder** [comment]
Confirmed server issue.
