### ISSUE TITLE
old main_out.js more smooth than cigar main_out.js

### ISSUE THREAD

**Issue by CiMFULL** [CigarProject/Cigar#536]
With this, the animation are so smooth and more nice..
But this is using old protocol, and skins don't work anymore, try it..

Download, extract to cigar folder, open cigar.html (127.0.0.1/cigar.html)

[here](https://drive.google.com/file/d/0Bw9Q_8yUWWcMUWRFck1rZzItMXc/view?usp=sharing)

**Comment by MastaCoder** [comment]
The old main_out.js is p4 and the new one is p5. Nothing in terms of rendering has really been changed in that case. 

Don't use Luka's version if you're planning on production use.
