### ISSUE TITLE
Join Here Plz

### ISSUE THREAD

**Issue by malekksa505** [CigarProject/Cigar#538]
hello everybody
I want to know how the number of players on a server

http://b.top4top.net/p_4312jd8i1.png

**Comment by MastaCoder** [comment]
Status port. However, that's been known to have a memory leak. 

I read through the code once and I think the server sends a packet with server information, but I can't confirm.

**Comment by malekksa505** [comment]
Please Help me @mastacoder

**Comment by Luka967** [comment]
All Ogar-based servers support a server statistics HTTP server. It always returns a JSON containing some server info. The default port is 88.
Easiest way to do it is to use jQuery to send a request and retrieve the data then edit the `#gamemode` option `innerHTML`s.

**Comment by malekksa505** [comment]
Can I communicate with you @Luka967

PLZ

**Comment by malekksa505** [comment]
skype : malekksa505

**Comment by zettabyte918** [comment]
254 packet !!

**Comment by makandz** [comment]
Don't bump old topics.
