### ISSUE TITLE
How to hide skin text !!

### ISSUE THREAD

**Issue by eevaqueen** [CigarProject/Cigar#540]
I read this #508 before posting,my question is:
How to hide skin text !!

I need to hide [1] please help me @Luka967 @RasyiidWho @MastaCoder @CalvinDKHD @ItzLevvie

![name](https://cloud.githubusercontent.com/assets/17146668/23728700/1bc89ab8-0413-11e7-8d5a-a3f46903967b.jpg)

**Comment by MastaCoder** [comment]
<> has been added to protocol list. You're probably not using the latest version of MultiOgar or Cigar.

Next time don't mention everyone.

**Comment by Y4ssine** [comment]
@MastaCoder  i have this problem but skins not working at all 
can u tell me how to download multiogar 1.5.0 or to fix it ?

**Comment by MastaCoder** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/commits/master

Just go until you find a working commit. Click all files after clicking the commit, download as zip.
