### ISSUE TITLE
How to change Food color

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#541]
Hello! I am trying to change the color of the food
i set the ctx.fillstyle like this `ctx.fillStyle = "#000000";`
And this is what comes out, i would only like the food to be colored.
![64a9b43fa9e1a7cbdc7c7ab8155da365](https://cloud.githubusercontent.com/assets/23283642/23831207/acfc9b22-071c-11e7-81c9-d4fea0abf857.png)

**Comment by MastaCoder** [comment]
This should be done server side, since the server sends the colours to the client.

**Comment by CalvinDKL** [comment]
This has also been done on client side
http://alis.io/

**Comment by MastaCoder** [comment]
There really shouldn't be a reason to do it client side. As for how to change, you'd need to use the flags provided in updateNodes. Remember food doesn't have it's own flag.
