### ISSUE TITLE
Where is messages drawn?

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#542]
Hello! so i would just like to know where messages are drawn
because i would like to use materializes dialogs as messages.
Thanks

**Comment by CalvinDKL** [comment]
This is where i have got so far
https://gyazo.com/b5333827854f79e0387cc9e3d1ccef0f

**Comment by MastaCoder** [comment]
https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L511

**Comment by CalvinDKL** [comment]
MastaCoder, can you please look at the image i sent??

**Comment by MastaCoder** [comment]
Because drawCanvas writes the same messages over the canvas drawn before. You're simply pushing the messages without deleting the last one. You'd need to modify the code and remove that portion to just add the 1 chat sent through.

**Comment by CalvinDKL** [comment]
Yeah, but where is the last message drawn?

**Comment by MastaCoder** [comment]
Right there in the function lol. The chatboard has the list of messages and they're drawn to the chat.

**Comment by CalvinDKL** [comment]
ctx.drawImage ??
Sorry i am super confused

**Comment by MastaCoder** [comment]
chatBoard is an array with everything.

**Comment by CalvinDKL** [comment]
I have tried deleting a lot of things i just dont know what does it and what doesnt
