### ISSUE TITLE
Leaderboard colors, (getting other players to see it).

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#543]
Hello, so i made a feature that makes your Nickname on the leaderboard a certain color, if you are using a certain nickname. Example: Nickname = calvin then the color of your self would change to Blue instead of red

Now i would like other people to see the the color on the leaderboard 
This is what a player sees if they use the nickname "calvin"
![8425dced7cb24dba25de67b4fc951f8b](https://cloud.githubusercontent.com/assets/23283642/23834648/5c041aea-075a-11e7-9b42-e7bf4a33bbbd.png)
And a random person just sees it as white
![ade5d5ada994b744f0311b88aa78643a](https://cloud.githubusercontent.com/assets/23283642/23834655/69065f78-075a-11e7-99f1-864d49f31db7.png)
Im guessing that i have to play around with 
`me ? ctx.fillStyle = "#FFAAAA" : ctx.fillStyle = "#FFFFFF";` (the ending part of it)
But i am not sure, got any advice?? thanks!

**Comment by MastaCoder** [comment]
Duplicate. #501

**Comment by CalvinDKL** [comment]
@MastaCoder Its not a dupe! This is how to get other people to see the colors, before it was only for the person using it!

**Comment by MastaCoder** [comment]
Nope. The if statement will work on all client, last post before the closing lol.

**Comment by CalvinDKHD** [comment]
I know, but people who is not using the name "calvin" they dont see the
other person named "calvin" as blue

**Comment by MastaCoder** [comment]
You're placing it wrong then, right below the part where a name is highlighted you need to add it. If you want calvin to also see it you're going to need to add an if else statement right below it.

This is really really basic JavaScript, you just need to find where to put it lol

**Comment by CalvinDKHD** [comment]
i put it in the right place, but i think you are getting it wrong. I want
all players to see someone using the name calvin as blue.

**Comment by MastaCoder** [comment]
It has to be it's own if statement, AFTER the check for the current user. You're not putting it in right because it should be on all clients, so it will affect all users. If you actually put it in the right place the client will highlight anything with that name.

**Comment by CalvinDKL** [comment]
What i mean is that OTHER players NOT using the name! should be able to see the blue color on someone using the same.

**Comment by CalvinDKL** [comment]
`if (c == "calvin") {
		me ? ctx.fillStyle = "#89ceff" : ctx.fillStyle = "#FFFFFF";
							}`
Just to be sure, is that right? because it works for me, but as i said others cant see it.

**Comment by CalvinDKL** [comment]
GOT IT!
THANKS!!!

**Comment by CalvinDKL** [comment]
i wasnt supposed to use me

**Comment by CalvinDKL** [comment]
Hello, can i get this done by ip aswell?
I know this, but its WS.
`if (ws.remoteAddress == "insert ip here") {
    blah blah
}`
