### ISSUE TITLE
Skins selection

### ISSUE THREAD

**Issue by malekksa505** [CigarProject/Cigar#544]
Hi everbody ..

I've watched issues #508 It has been applied in the work but of no use at work

I wish you to help me , thank you 

Footage at work : 
http://e.top4top.net/p_438rb8if1.png
http://f.top4top.net/p_438gx6yg2.png
http://a.top4top.net/p_438rfo9o3.png
http://b.top4top.net/p_438t8er24.png

**Comment by malekksa505** [comment]
@Luka967

**Comment by MastaCoder** [comment]
use .value, it was already said in the last issue..

**Comment by malekksa505** [comment]
I do not understand

Did you mean so  userNickName = "<" + document.getElementById("sm").value, + "> " + arg;

I did this but no avail

I'm use Multiogar

**Comment by malekksa505** [comment]
@MastaCoder

**Comment by MastaCoder** [comment]
should work, make sure to follow everything in the issue.
