### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by Logan7432** [CigarProject/Cigar#548]
What was the admin commands for the old server? Like what do I type in game to use a command.

**Comment by Logan7432** [comment]
@MastaCoder

**Comment by malekksa505** [comment]
Put your data in userRoles  so you can write commands Admin

**Comment by Logan7432** [comment]
@malekksa505 UserRoles? On the old server you signed into an admin account and you could type commands in through the chat box.

**Comment by MastaCoder** [comment]
same thing with userroles. Set the information, login, same process.

**Comment by Pollogy** [comment]
Hey @Logan7432  can u add me in skype (isubrath7) I have to ask something

**Comment by Logan7432** [comment]
@Mr-BroxkLee Hey, What would you like to ask? I looked up Isubrath7 and nothing came up, Would it be just iSuBrath?
