### ISSUE TITLE
Leader board colors according to user role

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#550]
Hello!
So recently i got Leader board colors to work by the help of @MastaCoder (Thanks a lot)
I am now thinking of doing it by user role, im guessing that this is also server sided.
I was thinking of something like

If user-role = "admin" then ctx.fillStyle blah blah blah

does anyone have an idea??
thanks

**Comment by CalvinDKL** [comment]
do i need to make flags?

**Comment by Luka967** [comment]
>do i need to make flags?

Yes.
Your best option is to change [this](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/packet/UpdateLeaderboard.js#L58-L60) uint32 to send flags; 1 = me, 2 = guest, 3 = user, etc.

**Comment by CalvinDKL** [comment]
@Luka967 
Sup Luka! i finished the flags, now i am having issues on the client side!
`		if (flags & 0x40) {
            // ADMIN Message
			console.log("You are an admin!"),
			chatName.setValue("[ADMIN]" + chatBoard[i + from].name);
			
        }`
If you look at the code i have added a console log, if the flag is recieved or sent or what ever, that works. The Console log appears when i login! So now i am trying to set the chat name, problem is that when you login now, with the chatname setvalue thing included nothing appears in the chat when you try to type......
https://gyazo.com/788c938b06e5b56aad63115d8c1d6a40
