### ISSUE TITLE
how to add minimap in the cigar/multiogar

### ISSUE THREAD

**Issue by malekksa505** [CigarProject/Cigar#551]
Hello ,,

how to add minimap in the cigar/multiogar

**Comment by CalvinDKL** [comment]
There is multiple ways of doing it.
1. Code it
2. Look at someones code and get ideas
3. Look at someones code and steal it

**Comment by malekksa505** [comment]
CalvinDec: I want you to bring me MINIMAP with the code

**Comment by Tyler3D** [comment]
Isn't it illegal to steal someone's code and claim it as your own.

**Comment by Luka967** [comment]
@malekksa505 This is a base for a client. Further edits are to be made by people.
Use:
HTML+CSS+jQuery or `ctx`
[These four variables](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L999-L1002) for map width/height
[These two variables](https://github.com/CigarProject/Cigar/blob/master/www/assets/js/main_out.js#L983-L984) for center position


@Tyler3D It isn't until something somewhere states that that part of code is copyrighted.

**Comment by Tyler3D** [comment]
k

**Comment by Luka967** [comment]
xd

**Comment by CalvinDKHD** [comment]
Tyler it depends, if the ppl who made it claimed it under some company then
yes, if not. Then no. And most ppl don't have any code claimed.

**Comment by haylinmoore** [comment]
No.. any code you produce is copyrighted under a nobody else can steal this. Unless you specify a new license or make it public domain
