### ISSUE TITLE
Admin TAG [almost done, just need a little help]

### ISSUE THREAD

**Issue by CalvinDKL** [CigarProject/Cigar#552]
I finished the flags, now i am having issues on the client side!

```
if (flags & 0x40) {
            // ADMIN Message
			console.log("You are an admin!"),
			chatName.setValue("[ADMIN]" + chatBoard[i + from].name);
			
        }
```
If you look at the code i have added a console log, if the flag is recieved or sent or what ever, that works. The Console log appears when i login! So now i am trying to set the chat name, problem is that when you login now, with the chatname setvalue thing included nothing appears in the chat when you try to type......
https://gyazo.com/788c938b06e5b56aad63115d8c1d6a40

**Comment by Mr-BrockLee** [comment]
calvin whats ur skype? i need to ask you something

**Comment by CalvinDKL** [comment]
got twitter?

**Comment by Mr-BrockLee** [comment]
Nah , Sry

**Comment by Mr-BrockLee** [comment]
Actually Yes @Mr_BrockLee Just made it

**Comment by Mr-BrockLee** [comment]
@CalvinDKL Twitter:Mr_BrockLee

**Comment by CalvinDKL** [comment]
Why was this issue closed?

**Comment by CalvinDKL** [comment]
And Levvie why did you refer it to another issue which is nothing like this one?

**Comment by MastaCoder** [comment]
Because it's not really an issue. The code is probably wrong.
