### ISSUE TITLE
Making Changes (index.css) 

### ISSUE THREAD

**Issue by Mr-BrockLee** [CigarProject/Cigar#554]
- Whenever I make changes to index CSS, It doesn't change anything. It changes after days and days.

> I am Sorry If this is a Duplicate. I tried searching it. Didn't know the exact words that's why I am making this Issue

Thx for Helping :D :1st_place_medal:  💯

**Comment by Luka967** [comment]
Do Shift+F5. Many browsers cache CSS files to use less traffic.

**Comment by Mr-BrockLee** [comment]
@Luka967 That works but what abt the ppl with saved cache, which have already visited my site before?

**Comment by MastaCoder** [comment]
You're gonna need to force Apache to restore the cache.

**Comment by Mr-BrockLee** [comment]
`index.html src="assets/js/main_out.js?v=2" use ?v=x change the number every time you make an edit `
#498 Would This Work? @MastaCoder @Luka967

**Comment by Luka967** [comment]
Yes.

**Comment by Mr-BrockLee** [comment]
Alrt
