### ISSUE TITLE
Issues With The Skins.

### ISSUE THREAD

**Issue by Mr-BrockLee** [CigarProject/Cigar#557]
> I am Pretty Sure this has been asked/reported before but , I haven't found an Solution/Answers 

 I am Currently Facing  these Issues with the Skins

# - Skins aren't Showing in The Gallery 
[Here is what I mean](https://gyazo.com/e49f8463e353c7daeaade10d42605da4)

# - When I select skin nick changes to the skin name. So if My nick was Lol and I want Doge skin ad I Select it from the gallery, Lol changes to doge ( No Tags Ex:  [] or <> or {})

Pls Help me 
-------------------------------------------------------------------
 Question: Is there a way to use skin without using  [] or <> or {}? Because in some website, once you have selected an skin the name of the skin appears no where on the nick box. 
-------------------------------------------------------------------
Thank You For Your Help :D 💯  Have a Gud Day 🎉

**Comment by Mr-BrockLee** [comment]
Anyone, @MastaCoder @Luka967 @AlexisTM ?

**Comment by Pollogy** [comment]
Anyone?

**Comment by AlexisTM** [comment]
Sorry @Mr-BrockLee, but I am not actively following the project and as there is no reference to the code itself, I can't help
