### ISSUE TITLE
Error when no arg

### ISSUE THREAD

**Issue by ryush00** [CigarProject/Cigar#57]
Around CommandList.js Line 109

        // Check if int/float
        if (value.indexOf('.') != -1) {
            value = parseFloat(value);
        } else {
            value = parseInt(value);
        }

This code should check is "value" undefined 

        if (typeof value != 'undefined') {
            // Check if int/float
            if (value.indexOf('.') != -1) {
                value = parseFloat(value);
            } else {
                value = parseInt(value);
            }
        }

**Comment by matrixreal** [comment]
wich file please?

**Comment by ryush00** [comment]
__CommandList.js__

And I found another bug.

In GameServer, this code must work when "start".

        // Gamemodes init
        this.gameMode = Gamemode.get(this.config.serverGamemode);

Not in ````function GameServer(realmID,confile) {````

    GameServer.prototype.start = function() {
        // Gamemodes init
        this.gameMode = Gamemode.get(this.config.serverGamemode);
        // Gamemode configurations
        this.gameMode.onServerInit(this);
    
        // Start the server
        this.socketServer = new WebSocket.Server({ port: this.config.serverPort, perMessageDeflate: false}, function() {
            // Spawn starting food
            this.startingFood();

(like this)

**Comment by matrixreal** [comment]
thanks much appreciated you are genious
can you take a look on the lag problem
it lagg much on mobile phone
thanks

**Comment by ryush00** [comment]
Sry, I'm not good at Graphic rendering. But If i can, I will make PR.
Thanks :)

**Comment by matrixreal** [comment]
@ryush00 
thanks wating for your great work ;)

**Comment by m-byte** [comment]
@ryush00 would you mind submitting your patch as a merge request?

**Comment by matrixreal** [comment]
@ryush00 
the mobile lag problem is not related to graphic rendering i think ...
specially on samsung the game lag very much

**Comment by MastaCoder** [comment]
Thanks. I committed these changes!
