### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#59]
@m-byte 
is it possible to add index.html method to server and client ?
because i don't find a way to webhost this project
thanks

**Comment by m-byte** [comment]
I am not exactly sure, what you are trying to do. If you want to change the
index page, edit the template in the server directory.

2015-08-24 22:52 GMT+02:00 MATRIX.REAL <notifications@github.com>:

**Comment by matrixreal** [comment]
I want to make my own server / website Like this one http://fxia.me/agar/
But webhosted not in localhost (home Pc)
Thanks

Envoyé de mon iPhone

**Comment by xmicro** [comment]
you'll get to get a domain and hoster... if you expect low amounts of people go with freenom.com (domain registrar) and 000webhost.com (free hoster), but if you get too many people/too much usage you'll need to buy an actual hoster (or VPS (host the server AND the website)) ;)

**Comment by matrixreal** [comment]
@xmicro 
thats ok thanks for reply but how to put this project on webhosting ? since there are no index.html etc ....

**Comment by m-byte** [comment]
I'll try to put some kind of tutorial together once I have a bit more time to spare.Cigar is already a full server for both the client and the game server. You need to setup nginx as a ‎proxy for both ports. Usually, you have the Cigar client on port 88 and the game server on some other port... So you would set nginx up to proxy requests coming from port 80 (outside the server) to port 88 (the port Cigar is running on) and the same for the server ports.                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.

**Comment by MastaCoder** [comment]
There are many agar-client clones out there. Just grab it and have it load from the gameserver.
