### ISSUE TITLE
Authentication (user management)

### ISSUE THREAD

**Issue by m-byte** [CigarProject/Cigar#6]
We have to add a user management based on passport. This will be used for locking user names and similar things.

**Comment by m-byte** [comment]
Features we could add:
- friends
  - chat messages could be sent to friends instead of other players
- locked names
- skin management
  - users can manage skins the uploaded
  - users can only upload skins for their locked names

**Comment by CineXMike** [comment]
When starting on this?

**Comment by m-byte** [comment]
Once I am done with the improved client

**Comment by mrmarktyy** [comment]
@m-byte what kind of improvement for client side were you working on ?

**Comment by m-byte** [comment]
Currently, Cigar uses agar-clone which has no clear license. It is therefore only partially open source.
The new client will be new code developed from the ground up that should also be easier to understand and modify.

**Comment by CineXMike** [comment]
So this will ne legal to use?

**Comment by m-byte** [comment]
@CineXMike As legal as possible ;) The code will be under a proper open source license and developed from scratch.

**Comment by Qasimmodo** [comment]
Will this still be added when you get time @m-byte or will anyone like to continue this. Since I have no clue on how I would go about doing this :P

**Comment by HAlexTM** [comment]
Sorry if I'm replying to this old thread but you're talking about sending packets with username, password etc... (I'm talking about the user management too) but this can all done through PHP and MySQL

index.php (if no Token cookie --> form --> login.php, else --> check Token in MySQL, show username)
login.php (if Token --> redirect, else --> read POST data and generate Token, save it in MySQL, save cookie)
main_out.js (if Token --> send it through socket)

Server side: (On Token receive --> check from MySQL --> is it valid? --> load user ID, else --> ID = 0 or guest)

Everything else that is needed, is done by the user ID

**Comment by MastaCoder** [comment]
Cigar is now client only.
