### ISSUE TITLE
Message/Chat delay?

### ISSUE THREAD

**Issue by xmicro** [CigarProject/Cigar#60]
Is there any way to implement a message/chat delay so clients can only send messages every x seconds to stop spam?

**Comment by xmicro** [comment]
Or perhaps even an auto-ban mechanic for spamming?

**Comment by Logan7432** [comment]
did you ever find out how to do this? cause i really need a delay or better yet, chat delay and word filter

**Comment by xmicro** [comment]
No, but I found a workaround. Embed a chat service that has the features you're looking for, I'd use xat -> http://xat.com

You can use xat to get your own chat, embedded to any proportion. Xat allows you to promote users to varying ranks, and it comes with an auto-spam and anti-cuss filter coded into the chat system.

**Comment by Logan7432** [comment]
alright ill check this out and ill let you know how i feel about it.

**Comment by Logan7432** [comment]
So im trying to add this to my site and its not working so well. if im adding a chat like this i want to add a login system to my site cause people could have different names in the chat then there in game agario names making it confusing. if someone could please implement or tell me how to add this it would be great. Agario sites like Agarioplay.org have anti spam, anti cuss, and register system which i dont care too much about but the main thing is anti spam and cuss

**Comment by xmicro** [comment]
Look you're not going to get someone to do this for you. Xat does have a login system, if you are unable to implement xat into your website then maybe it's not the best idea to be running your own server, huh?

**Comment by Logan7432** [comment]
What i mean by the login system is what ever there username is in the chat it wont be the same as there nick. Also i wanted help with adding this, not someone to do this for me (but i was hoping someone found a good solution  besides xat.com). I also think i should be running my own server cause mines agario site is very popular and a lot of people play on it (about 20-25 people). I designed the site perfect except for the chat that has people spamming and cussing so bad.

**Comment by xmicro** [comment]
20-25 people isn't even self-sustainable, never mind popular. If you think you should be running your own server, which I highly advise against wasting money on, then you must learn Javascript/node.js. A fair understanding of Javascript should provide you the ability to code whatever you want into the game. If you show no desire in learning Javascript, don't bother expanding your server. With no knowledge of JS, and a stock Cigar package, the only use that's merited is to play with friends. If you plan to keep/expand your server to the point of needing to stop spamming/add a word filter, it's appropriate to continue your current server capacity, if not lessen it. If you do not want to learn Javascript AND do not want to listen to me in that respect, I'd just settle with the no integrated usernames. People can change their own usernames, you know.

**Comment by Logan7432** [comment]
i dont waste money on a server, i host it myself on a very fast pc and fast network. i would love to learn javascript/nde.js cause i really want to expand my server so everyone has fun and so do i. By the way i dont understand what yo mean by "People can change your usernames,you know" i was referring to the xat.com cause your chat name would be different from your agario nick if you didnt change your xat.com username to your nick. But anyway i would love to learn how to code and expand my site cause i just know basic adding words and color coding. i also wanted to ask, Besides the word filter and anti spam is it possible to be able code like an admin thing so when i type -pass (password) it will log me in as a admin and be able to use console commands? Thanks

**Comment by Logan7432** [comment]
I forgot to say, i need this profanity filter and anti spam really bad mostly because my agario server is ran for my school since they blocked every agario website. Even some of the teachers play on there free time. They see the chat and all the bad things people are saying and with 20 some people spamming its just not good. Thats why i all of a sudden really need this for my site. Every code i add to Chat.js in the server folder crashes the console. I really need some help with this one i just cant figure it out.

**Comment by xmicro** [comment]
I'll give you 3 options: 
1.) Remove the chat
2.) Learn JavaScript and familiarize yourself with the Cigar code and do whatever you want with it
3.) Use xat.

People can change their own names if they don't match up with the server, and if they don't it's not that big of a deal. You'll get clan imposters that are going to fake their names anyway, might as well have xat as a method of double checking. You could tel by their xat ID or rank.

**Comment by Logan7432** [comment]
Ok. Im going to do option 2 and 3. I want to learn javascript but in the mean time i guess im gonna try and use xchat,

**Comment by Logan7432** [comment]
micro i have been working on a profanity filter but imnot sure how to code it into my main_out without braking the website. Any ideas?

**Comment by Logan7432** [comment]
Well, after a week of testing and coding i finally was able to add a profanity filter and anti spam/flood to my chat. I was able to do this by messing around in the main_out. Im not sure how i added this to the game myself and they main people working on this cant figure it out. Keeping the code all to myself due to crap responses i got when trying to help with this.

**Comment by MastaCoder** [comment]
Added.
