### ISSUE TITLE
How to change main page?

### ISSUE THREAD

**Issue by agario12300** [CigarProject/Cigar#61]
How to change title of Ogar? What file I need to change?
![image](https://cloud.githubusercontent.com/assets/13993684/9518486/f16d14d0-4cf1-11e5-8af0-a630fa821c95.png)

**Comment by agario12300** [comment]
I want to change korean

**Comment by xmicro** [comment]
you want to find index.html on your client (website)

Ogar/Cigar is a server

**Comment by m-byte** [comment]
@xmicro That's incorrect. The title can be changed in server/web/routes/index.js                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: xmicroGesendet: Donnerstag, 27. August 2015 17:11An: m-byte/CigarAntwort an: m-byte/CigarBetreff: Re: [Cigar] How to change main page? (#61)you want to find index.html on your client (website)

Ogar/Cigar is a server

—Reply to this email directly or view it on GitHub.

**Comment by xmicro** [comment]
I find it easier to edit the former.

**Comment by m-byte** [comment]
But there is no index.html if you don't put It in there. ‎ When using the integrated client, this ‎is the recommended approach.

**Comment by xmicro** [comment]
Oh, okay. Do you know how to implement a message delay, or perhaps even an auto-ban from spamming? It's my issue here --> https://github.com/m-byte/Cigar/issues/60

Thanks.

**Comment by MastaCoder** [comment]
Added.
