### ISSUE TITLE
update ?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#63]
@m-byte 
any news of updating to lastest ogar ?
also can you add index.html method to client ? and solve the mobile latency lagg ?
thanks much appreciated

**Comment by MastaCoder** [comment]
I'm working on the project now :)

**Comment by matrixreal** [comment]
@MastaCoder thanks a lot for the great work
any news about the mobile lagging ?

**Comment by MastaCoder** [comment]
That's an issue with the engine on mobile phones. We need to find something more efficient of sending images and movements. But until then, I guess we can't do much.

**Comment by matrixreal** [comment]
may we can switch to jxcore and use the multithread ?

**Comment by MastaCoder** [comment]
Cigar is already compatible with JXCore. Simply edit the start_x.sh files with all nodes to be jx.

**Comment by matrixreal** [comment]
ok do you know how to use the multithread ?

**Comment by MastaCoder** [comment]
It would be multi-threaded if you just run JXCore.

**Comment by matrixreal** [comment]
no you have to define the number of thread that you want to use
something like "jx mt:n index.js" and n is number of thread

**Comment by MastaCoder** [comment]
Okay I'll look into it.

**Comment by matrixreal** [comment]
@MastaCoder 
Excellent .... the new cigar plus is runing good 
2 things we have to work on
1) benchmarch between jxcore and node
2) run the multithread with jxcore
thank you
can you add me on skype mine is matrix.real

**Comment by MastaCoder** [comment]
Done
