### ISSUE TITLE
Blinking grid on Retina display

### ISSUE THREAD

**Issue by ryush00** [CigarProject/Cigar#70]
<img width="260" alt="2015-09-15 10 35 29" src="https://cloud.githubusercontent.com/assets/4997174/9877838/4e9a76ea-5bfa-11e5-8a0d-d061c659bd68.png">
__Cigar__

<img width="248" alt="2015-09-15 10 36 26" src="https://cloud.githubusercontent.com/assets/4997174/9877840/4f08fed0-5bfa-11e5-9806-627801d86723.png">
__Official Agar.io__

On Retina display, It is really dizzy. Grids are blinking.

**Comment by matrixreal** [comment]
got same here
i think its scaling problem

**Comment by matrixreal** [comment]
@ryush00 
@m-byte 
any news about this issue ?

**Comment by matrixreal** [comment]
@m-byte 
any update about this issue ? thanks

**Comment by matrixreal** [comment]
@ryush00 
any news about this problem ?

**Comment by ryush00** [comment]
Maybe no.

**Comment by matrixreal** [comment]
@ryush00 
peoplefrom this project seem to fix that problem i have tested their example and it's okay
https://github.com/huytd/agar.io-clone

**Comment by J4awesome** [comment]
Try restart the server the server or downloading a new one.I get the issue on other macbook that has a older retina screen.

**Comment by matrixreal** [comment]
i alreadydo it several times .. and still same (but downloading new server not mean something since the server is not updated right ?)

**Comment by J4awesome** [comment]
What mac or pc are you using and how old is it?

**Comment by J4awesome** [comment]
If it still doesn't work test the error on my server  Agarplay.us

**Comment by matrixreal** [comment]
@J4awesome 
wow this is working .... how you done it ?

**Comment by J4awesome** [comment]
I took some classes on html before a started the server to get some idea on how to edit the homepage.I'm getting money from the server using yllix a company based on google adsense but doesn't take that long to get approved.I can help you if you need with the server.

**Comment by matrixreal** [comment]
yes ... absolutly ... i'm searching about it since 3 months
the problem i got is the bad display with retina ... we can discuss on skype ? (by writing ... i don't have earphone) thank you

**Comment by J4awesome** [comment]
Ok my skype is J4awesome

**Comment by matrixreal** [comment]
thank you man mine is matrix.real

**Comment by J4awesome** [comment]
Add me to a message

**Comment by matrixreal** [comment]
ok  now i'm on skype and i already add you

**Comment by J4awesome** [comment]
My skype isn't working let's just talk on here

**Comment by matrixreal** [comment]
did you made changes on client or server for the retina display ?

**Comment by J4awesome** [comment]
No I think it's an download problem.

**Comment by J4awesome** [comment]
Nevermind when you go to your server and click the setting menu it says smooth render I remove that option from the game because I felt the user didn't know what it was.You could try removing that and it might work.

**Comment by matrixreal** [comment]
no i already think about that ... and remove it but still same
can you share with me your server / client please ...
thanks

**Comment by J4awesome** [comment]
The server/client i'm using is the same one in the download it could also be where your hosting because I host my server on a domain if you host it on a sub domain or an ip the server will try to stay connected by lower it's textures.

**Comment by J4awesome** [comment]
I host my website on godaddy which connects to my ip address.

**Comment by matrixreal** [comment]
no i don't think it's related too
and the smooth render ... you remove it completely from game (main_out.js) or just from the main game page ?

**Comment by J4awesome** [comment]
From the game.hbs which is the homepage.

**Comment by matrixreal** [comment]
ok send me your game.hbs my email is metchat2010@hotmail.fr

**Comment by J4awesome** [comment]
Ok I'm sending you it now

**Comment by J4awesome** [comment]
It's sent but I might be hard for you to understand if you don't understand html.

**Comment by matrixreal** [comment]
thank you will check it now

**Comment by matrixreal** [comment]
did not receive it ... and i know some html / javascript so it's okay

**Comment by J4awesome** [comment]
<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'>
<meta http-equiv='X-UA-Compatible' content='IE=edge'>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Eat cells smaller than you and don't get eaten by the bigger ones, as an MMO">
<meta name="keywords"
content="agario, agar, io, cell, cells, virus, bacteria, blob, game, games, web game, html5, fun, flash">
<meta name="robots" content="index, follow">
<meta name="viewport"
content="minimal-ui, width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link id="favicon" rel="icon" type="image/png" href="http://imageshack.com/a/img908/9776/UmkgWe.png"/>
<meta name="apple-mobile-web-app-capable" content="yes">
<title>Agarplay.us</title>
<link href='https://fonts.googleapis.com/css?family=Ubuntu:700' rel='stylesheet' type='text/css'>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="Vector2.js"></script>
<script src="main_out.js"></script>
<style>body {
padding: 0;
margin: 0;
overflow: hidden;
}

#canvas {
position: absolute;
left: 0;
right: 0;
top: 0;
bottom: 0;
width: 100%;
height: 100%;
}

.checkbox label {
margin-right: 10px;
}

form {
margin-bottom: 0px;
}

.btn-play, .btn-settings, .btn-spectate {
display: block;
height: 35px;
}

.btn-play {
width: 85%;
float: left;
}

.btn-settings {
width: 13%;
float: right;
}

.btn-spectate {
display: block;
float: right;
}

#adsBottom {
position: absolute;
left: 0;
right: 0;
bottom: 0;
}

#adsBottomInner {
margin: 0px auto;
width: 728px;
height: 90px;
border: 5px solid white;
border-radius: 5px 5px 0px 0px;
background-color: #FFFFFF;
box-sizing: content-box;
}

.region-message {
display: none;
margin-bottom: 12px;
margin-left: 6px;
margin-right: 6px;
text-align: center;
}

#nick, #locationKnown #region {
width: 65%;
float: left;
}

#locationUnknown #region {
margin-bottom: 15px;
}

#gamemode, #spectateBtn {
width: 33%;
float: right;
}

#helloDialog {
width: 350px;
background-color: #FFFFFF;
margin: 10px auto;
border-radius: 15px;
padding: 5px 15px 5px 15px;
position: absolute;
top: 50%;
left: 50%;
margin-right: -50%;
-webkit-transform: translate(-50%, -50%);
-ms-transform: translate(-50%, -50%);
transform: translate(-50%, -50%);
}

#chat_textbox {
-webkit-transition: all .5s ease-in-out;
-moz-transition: all .5s ease-in-out;
-o-transition: all .5s ease-in-out;
transition: all .5s ease-in-out;
position: absolute;
z-index: 1;
bottom: 10px;
background: rgba(0, 0, 0, .2);
border: 0px;
outline: none;
color: #FFF;
height: 30px;
text-indent: 12px;
left: 10px;
width: 300px;
}

#chat_textbox:focus {
background: rgba(0, 0, 0, .5);
}

#a300x250 {
width: 300px;
height: 250px;
background-repeat: no-repeat;
background-size: contain;
background-position: center center;
}</style>
</head>
<body>
<div id="fb-root"></div>
<div id="overlays"
style="display:none; position: absolute; left: 0; right: 0; top: 0; bottom: 0; background-color: rgba(0,0,0,0.5); z-index: 200;">
<div id="helloDialog">
<form role="form">
<div class="form-group">
<div style="float: left; margin-left: 20px;"><h2>Agarplay.us</h2></div>
<br clear="both"/>
</div>
<div class="form-group">
<input id="nick" class="form-control" placeholder="Nickname" maxlength="15"/>
</select>
<br clear="both"/>
</div>
<div id="locationUnknown">
<select id="region" class="form-control" onchange="setRegion($('#region').val());" required>
<option selected disabled value=''> -- Select A Server --</option>
<option value='Rainbow FFA'>Rainbow FFA</option>
<option value='Rainbow FFA 2'>Rainbow FFA 2</option>
<option value='Teams'>Teams</option>
<option value='Experimental'>Experimental</option>
<option value='Normal FFA'>Normal FFA</option>
</select>
</div>
<div>
<div class="text-muted region-message CN-China">

</div>
</div>
<div class="form-group">
<div>

<p></p>
</div>

<button disabled type="submit" id="playBtn"
onclick="setNick(document.getElementById('nick').value); return false;"
class="btn btn-play btn-primary btn-needs-server">Play
</button>
<button onclick="$('#settings, #instructions').toggle();return false;"
class="btn btn-info btn-settings"><i class="glyphicon glyphicon-cog"></i></button>
<br clear="both"/>
</div>
<div id="settings" class="checkbox" style="display:block;">
<div class="form-group" id="mainform">
<div id="locationKnown"></div>
<button id="spectateBtn" onclick="spectate(); return false;" disabled
class="btn btn-warning btn-spectate btn-needs-server">Spectate
</button>
<br clear="both"/>
</div>
<div style="margin: 6px;">
<label><input type="checkbox" onchange="setNames(!$(this).is(':checked'));"> No names</label>
<label><input type="checkbox" onchange="setDarkTheme($(this).is(':checked'));"> Dark Theme</label>
<label><input type="checkbox" onchange="setShowMass($(this).is(':checked'));"> Show mass</label>
</div>
</div>
</form>
<div id="instructions" style="height:120px;">
<hr/>
<center><span class="text-muted">
Don't Play In School<br/>
Agarplay.us ©<br/>
Press <b>W</b> to eject some mass<br/>
<a href="http://www.freecounterstat.com" target="_Blank" title=""></a><br/>
<script type="text/javascript" src="http://counter8.fcs.ovh/private/counter.js?c=e629cb31bc3f9882366183f4409d46e6"></script>
<script type="text/javascript" src="http://yx-ads6.com/popup.php?section=Agar&pub=312976&ga=g"></script>
</span></center>
<div class="skor" style="height:400px; position:absolute; top:3px;left:-345px;width:325px; background-color:#FFFFFF; border-radius:10px;padding:15px 15px 5px 15px;">
<!DOCTYPE html>
<html>
<script type="text/javascript" src="http://yx-ads6.com/layer.php?section=General&pub=312976&ga=g&show=1"></script>
<head>

<title>
</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style type="text/css">
body {background-color:ffffff;background-repeat:no-repeat;background-position:top left;background-attachment:fixed;}
h4{text-align:left;font-family:Arial;color:000000;}
p {font-family:Arial;font-size:16px;font-style:normal;font-weight:normal;color:FFFFFF;}
</style>
</head>
<body>
<h4>NEW IP ADDRESS!!</h4>
<p>The new ip if you do play it in school (I wouldn't) type in

45:55.102.252:100</p>
<center>
<script type="text/javascript" src="http://yx-ads6.com/banner.php?section=Agar2&pub=312976&format=300x250&ga=g"></script>
</body>
</html>
<br clear="both"/>
<center>
<div class="left" style="height:275px; position:absolute; top:3px;left:735px;width:330px; background-color:#FFFFFF; border-radius:10px;padding:15px 15px 5px 15px;">
<iframe src="http://yx-ads6.com/banner_show.php?section=General&amp;pub=312976&amp;format=300x250&amp;ga=g" frameborder="0" scrolling="no" width="300" height="250" marginwidth="0" marginheight="0"></iframe>
</center>
<div>
</div>
<small class="text-muted text-center"></small>
</center>

</div>
</div>
<div id="connecting"
style="display:none;position: absolute; left: 0; right: 0; top: 0; bottom: 0; z-index: 100; background-color: rgba(0,0,0,0.5);">
<div style="width: 350px; background-color: #FFFFFF; margin: 100px auto; border-radius: 15px; padding: 5px 15px 5px 15px;">
<h2>Connecting</h2>

<p> Sorry but we you couldn't connect to the server right now check if there is an update or the server may be down.
</div>
</div>
</div>
</div>
<div id="topmenu" style="position: absolute; z-index: 9999; top: 10px; left: 175px;overflow:hidden;">
<div class="btn-group-m" style="display:inline-block;float:left;">
<a href="#" id="menubtn" onclick="showMenu($(this));" class="btn btn-primary" style="display: none;"><i class="fa fa-arrow-left"></i> &nbsp;Main Menu</a>
<a href="http://fancytext.blogspot.com" target="_blank" id="menubtn" onclick="showMenu($(this));" class="btn btn-primary"><i class="fa fa-arrow-left"></i> &nbsp;Fancy Text</a>
<a href="#" id="screenshot" onclick="getScreenshot()" class="btn btn-success" style="display: none;"><i class="fa fa-camera"></i> &nbsp;Screenshot</a>
<a href="#" onclick="clearProcess()" class="btn btn-danger btn-block btn-social" id="deletebt" style="display: none; margin-top:8px;"><i class="fa fa-times"></i> &nbsp;Delete</a>
<ul class="gallery">
</ul>
</div>

</div>

<canvas id="canvas" width="800" height="600"></canvas>

<input type="text" id="chat_textbox" maxlength="375" placeholder="Press Enter To Chat"/>
</body>
<script>
function getScreenshot(){
var canvas = document.getElementById('canvas');
var context = canvas.getContext('2d');
var dataURL = canvas.toDataURL('image/jpeg', 0.7);
$(".gallery").html('<a href="' + dataURL + '" target="_blank"><img id="ss" src="' + dataURL + '"></a>');
$("#screenshot").attr("disabled", true).addClass("disabled");
$("#deletebt").show();
}

function clearProcess(){
$("#screenshot").show();
$(".gallery").html('');
$("#deletebt").hide();
$("#screenshot").attr("disabled", false).removeClass("disabled");
}

<canvas id="canvas" width="800" height="600"></canvas>
<input type="text" id="chat_textbox" maxlength="200"/>

<div style="font-family:'Ubuntu'">&nbsp;</div>

<script type="text/javascript">
$('input').keypress(function(e) {
if (e.which == '13') {
e.preventDefault();
if (!isSpectating)
setNick(document.getElementById('nick').value);
}
});
</script>

</body>
</html>

**Comment by J4awesome** [comment]
Do you have a google drive I can send it to you that way

**Comment by matrixreal** [comment]
did not activated it .... try use drop box its easy and fast to upload some files
thanks

**Comment by J4awesome** [comment]
Ok I will just get dropbox I'm downloading it now

**Comment by J4awesome** [comment]
I sent it to your email
