### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by ZombieMIW** [CigarProject/Cigar#71]
I've been reading other issues and I've been trying to read the instructions but they just say "if on windows just open the batch file" and I tried that but I all get is errors :(

![image](https://cloud.githubusercontent.com/assets/14363941/9977816/1b5dab4a-5ec9-11e5-84f0-d501317b76b6.png)

and when I try to open with admin i get this:
![image](https://i.gyazo.com/404a29fbefc9300f7b44923ab323d8e8.png)

**Comment by vram4** [comment]
You need install ws by typing "npm install ws" in command prompt and then run the server using the first method (batch file).

**Comment by matrixreal** [comment]
hi
got this error
when install via ssh putty
what i do 
git clone git://github.com/m-byte/Cigar.git Cigar
npm install ./Cigar
cd Cigar
npm install ws
npm start
![error](https://cloud.githubusercontent.com/assets/6823974/10144808/cf161548-661f-11e5-8232-4a21c9bf4cd9.png)

**Comment by elitajmx** [comment]
i have same problem for express thing

**Comment by Luka967** [comment]
Go to the directory where Cigar is, and type `npm install`. It should automatically install all modules required.

**Comment by elitajmx** [comment]
where do i type npm install?

**Comment by Luka967** [comment]
In command prompt

**Comment by MastaCoder** [comment]
I made a file for this.
