### ISSUE TITLE
server dedicated vps i7 8giga memory but game lagg

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#72]
hi
i just finally install the lastest build of cigar from here with dedicated server i7 8 giga memory
but the game is lagg much look here http://123.30.235.199:8080/
is there any way to optimize it ?
thanks

**Comment by MastaCoder** [comment]
Not really. Are you running Windows?

**Comment by matrixreal** [comment]
centos 6 64 bits

**Comment by MastaCoder** [comment]
Shouldn't be lagging in the newer update. Can you confirm this?

**Comment by matrixreal** [comment]
will test it now

**Comment by MastaCoder** [comment]
Alright.
