### ISSUE TITLE
[Update]

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#76]
@m-byte 
@ other contributors @ all
Cigat is really good and complete agar game ... i think we like it all but it seem that we need update
any contributions will be appreciated ... we want make this repo best in the world

1) update to lastest ogar
2) update / use lastest jquery 2.1.4 (to solve / fix the safari white screen)
3) fix retina problem for idevice (#70)
4) enhancements (add sounds #50)

these are the most update we have to work on ...

thanks a lot to all specially @m-byte  @forairan  @dooglus @subv3rsion @JBoughter

**Comment by FilipeGNU** [comment]
I'm interested in helping the project ...

I own a fly agaric server made ​​with Cigar : http://agarioex.com.br/

In my own server map , radio and jquerry 2.1.4 and some peculiar improvements.

The current n oservidor is sweating Apache, but I'm migrating all pro Cigar , you should give me access can up the changes made to the cigar now.

**Comment by matrixreal** [comment]
@FilipeGNU 
i see your server ... it look nice
but your index.html still use old jquery > result > not run on browser mobile
you need the access to my server ? right ?

**Comment by m-byte** [comment]
@FilipeGNU I just transfered this repo to a new organization named `CigarProject` (Cigar was already taken and I was to lazy to come up with a better name.

@matrixreal sorry for the missing progress. I have lately been swamped with work. Since you are probably the most active user in the issue section, I also invited you to the organization ;)

**Comment by matrixreal** [comment]
@m-byte 
thanks ... i understand that you have a lot of work
we like cigar ... and keep the name like that cigarproject is cool too

**Comment by FilipeGNU** [comment]
anyway I'd like to help the project , all the changes I made on my apache server using a client I finished the built-in cigar client .

Is 100 % functional just a bug in the map that time for pointing the location.

How do I contribute to the project?

**Comment by matrixreal** [comment]
@FilipeGNU 
you share your project here :dancer:

**Comment by matrixreal** [comment]
@FilipeGNU 
any news ? thanks

**Comment by matrixreal** [comment]
@FilipeGNU 
we are witing you

**Comment by matrixreal** [comment]
any one can contribute ?

**Comment by MastaCoder** [comment]
I'm going to keep the separate posts.
