### ISSUE TITLE
Connection between Cilent and Server

### ISSUE THREAD

**Issue by higoing00** [CigarProject/Cigar#77]
On the Start - GameServer, all that keeps showing up is the MasterServer. I can't do a command like Ogar keeps saying it's invalid.

I forget about that and attempt connecting to the server from agar.io. I went into the console and did this. 
                                                         connect("ws://192.168.56.1:443")
I get Socket Error & Socket Close. I know Socket Close means that the browser didn't connect to the server, but I don't understand the Socket Error.

(and if you can tell me, how to host a private server on a domain, that'd be helpful.)

Thanks.

**Comment by matrixreal** [comment]
@higoing00 
ogar and cigar are different
ogar use agar.io
cigar doesn't

**Comment by higoing00** [comment]
@matrixreal 

How do you use Cigar?
