### ISSUE TITLE
[ERROR] Skins don't load

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#79]
I put to upload skins, in the console its ok skin work on gallery and not work on game :(

**Comment by matrixreal** [comment]
what you use to install the server ?

**Comment by Lukkez** [comment]
Node.js but i resolved the error

**Comment by matrixreal** [comment]
Can you share the solution ? 

Envoyé de mon iPhone

**Comment by Lukkez** [comment]
Not upload skins with the name "ABC"
Ex:
"YouTube" is incorrect
"youtube" is correct
:D

**Comment by MastaCoder** [comment]
Great!
