### ISSUE TITLE
[HELP! PLZ]How to put 2 server's in one website + 1 question

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#80]
How? i put gameserver.ini and i put gameserver2.ini to load 2 server but no load.

That command's don't work how to put to work

    Add [Server IP] [Server Port] [Region Name]
        Adds an existing server to the master server list
    All {Command}
        Executes the command on all game servers
    Create [Region Name] [Game mode]
        Creates a server and adds it to the master server list.
    Select [Server ID]
        Same as the game server command.
    Serverlist
        Displays the list of servers that are connected, their ID, region, gamemode, and connected players.
    Remove [Server ID]
        Removes the selected server ID from the server list.

**Comment by J4awesome** [comment]
Here is the answer (To lazy to write it out)
#26 
The easiest way of doing this at the moment is to add custom Regions. E.g. regions = {"Experimental":1, "Teams":1, "Normal":1} in masterserver.ini

**Comment by MastaCoder** [comment]
^^
