### ISSUE TITLE
[simple question]

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#81]
hi all
i installed the server and i want to remove the upload skins (since it not work properly) and i want to let the server using lastest jquery
where can i modify these parameters ?
thanks

**Comment by matrixreal** [comment]
@m-byte 
any help please ? did not find it

**Comment by happyhg3927** [comment]
Just remove 'uploads.html' from client folder.

**Comment by matrixreal** [comment]
@happyhg3927 
won't work
want to cutom the main page ...

**Comment by Lukkez** [comment]
Go to server/web/views/game.hbs and edit on line 35 and remove uploads.html
