### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by iamashay** [CigarProject/Cigar#84]
When I try to connect to my server I get the following error and nothing shows while playing the game: Uncaught RangeError: Offset is outside the bounds of the DataView
![git](https://cloud.githubusercontent.com/assets/7845033/10613296/2ec96068-7772-11e5-8c5c-8e248525f198.png)

**Comment by Lukkez** [comment]
that is a modded client you need to go "localhost:PORT"

**Comment by Lukkez** [comment]
the site not is agar.io for the cigar only ogar is localhost(127.0.0.1:port) like:
localhost:88

**Comment by iamashay** [comment]
Yes, it was client side issue. Its working on other client.

**Comment by Lukkez** [comment]
Set the 2 masterserver.ini like that:
serverIP = localhost
serverPort = 88
gameserverPort = 88
updateTime = 60
regions = {"Experimental 1 [USA]":1,"Teams 1 [USA]":1}

that is a multi server template use "," to put multi server like:
regions = {"Hunger Games [FR]":1,"Multi-ServerTest":1}   Use :1 to online
works see:
http://imgur.com/wylNKso
http://imgur.com/vnJMQUD

**Comment by Lukkez** [comment]
For me worked
