### ISSUE TITLE
A help for windows user's

### ISSUE THREAD

**Issue by Lukkez** [CigarProject/Cigar#85]
Not only install node.js and ws module use all the module listed here:
npm install ws
npm install express
npm install serve-favicon
npm install morgan
npm install cookie-parser
npm install body-parser
npm install connect-busboy
npm install hbs

**Comment by m-byte** [comment]
Or follow README.md and run `npm install ./Cigar` after `git clone git://github.com/CigarProject/Cigar.git Cigar`... It'll install all dependencies.

**Comment by Lukkez** [comment]
That is for only linux, work with windows?

**Comment by Lukkez** [comment]
Or Ubuntu

**Comment by m-byte** [comment]
I updated the readme. If you are able to run `npm install ws`, there's no reason why you wouldn't be able to run `npm install` from within the Cigar directory.
