### ISSUE TITLE
Where is the PHP files?

### ISSUE THREAD

**Issue by Kuchiriel** [CigarProject/Cigar#92]
Sorry, now i see that there is a route for upload. But, anyway, it did not work...

**Comment by matrixreal** [comment]
yes the upload is not working
hope someone fix it

**Comment by iiegor** [comment]
See [app.js#L75](https://github.com/CigarProject/Cigar/blob/master/server/web/app.js#L175). The server is checking for a field called ``avatar`` that is never posted. If you look at the [uploads.hmtl](https://github.com/CigarProject/Cigar/blob/master/client/uploads.html), we are sending ``fileToUpload`` so, changing ``avatar`` for ``fileToUpload`` would solve this.
