### ISSUE TITLE
Client only

### ISSUE THREAD

**Issue by Ciao121** [CigarProject/Cigar#93]
I'm trying to use only client from Cigar. I halready have a ogar server.
I downloaded the client, canged the connection var to xxx.xxx.xxx.xxx:yyy
I used the index.html found here:
https://github.com/CigarProject/Cigar/commit/a4e53eb51ab08ae0a6191b595a9d1b3a9ce3b2bd
(don't know why it was removed). Anyway...

If I try to connect via the cigar client I alway get the connecton message:
Connecting
If you cannot connect to the servers, check if you have some anti virus or firewall blocking the connection.

But if i connect via agar.io/?ip=xxx.xxx.xxx.xxx:yyy it connects fine.
Where am I wrong?

Thank you

**Comment by m-byte** [comment]
Some time ago, the ability to connect alternative clients to Ogar was specifically removed by the developers over there. Also, the client is fairly old. You will most likely be unable to connect it.                                                                                                                                                                                                   Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: Ciao121Gesendet: Dienstag, 10. November 2015 15:04An: CigarProject/CigarAntwort an: CigarProject/CigarBetreff: [Cigar] Client only (#93)I'm trying to use only client from Cigar. I halready have a ogar server.
I downloaded the client, canged the connection var to xxx.xxx.xxx.xxx:yyy
I used the index.html found here:
a4e53eb
(don't know why it was removed). Anyway...

If I try to connect via the cigar client I alway get the connecton message:
Connecting
If you cannot connect to the servers, check if you have some anti virus or firewall blocking the connection.

But if i connect via agar.io/?ip=xxx.xxx.xxx.xxx:yyy it connects fine.
Where am I wrong?

Thank you

—Reply to this email directly or view it on GitHub.

**Comment by Ciao121** [comment]
I removed the connection filter on ogar. Probably is the "old" client. Thanks anyway

**Comment by Ciao121** [comment]
Ok, I can connect now (added my host to origin). But client show a big blck cell taking all the server and does not spawn players. Maybe is just old.
Looking for a new one.. any help?

**Comment by MastaCoder** [comment]
Yeah this is because the packets it sends are old. I don't know if we can update to the new one because then that will mean we have to update the client at the same time.
