### ISSUE TITLE
[question] how do i ?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#94]
Hi,
i want to add sounds in different stats of the game

and i need to know where can i find lines when : 

1- eat cells
2- split
3- feed
4- gameover

thanks

**Comment by matrixreal** [comment]
@forairan 
@dooglus 
@m-byte 
any help please ?

**Comment by J4awesome** [comment]
You can edit the html somehow in the game.hbs file

**Comment by MastaCoder** [comment]
This is more of a personal preference.
