### ISSUE TITLE
Change leaderboard to top 20

### ISSUE THREAD

**Issue by AgarioCheats** [CigarProject/Cigar#95]
Hi, how do i change the leaderboard to show top 20 players? Or atleast, top players UNTIL 20, so if there are only 15 users on the server, show top 15.

**Comment by helma27** [comment]
Go to server/gamemodes/FFA.js

Find 
```javascript
} else if (lb.length < 10) {
```
or line 90

change the  10 to the number that you want

**Comment by MastaCoder** [comment]
I'm adding this to the config!
