### ISSUE TITLE
skins selection?

### ISSUE THREAD

**Issue by matrixreal** [CigarProject/Cigar#96]
Hi,
is there a way to change the name skins system to system selection ?
as players are not forced to use the name of skins ?
for example we access to the skins page and we select them manually and we can use any name (nick) with the skins ?

**Comment by matrixreal** [comment]
anyone have an idea ?

**Comment by matrixreal** [comment]
any one have infos about what are the lines related to skins ?

**Comment by matrixreal** [comment]
@m-byte 
@all
can you tell me where in the code i can add the skins selection (not by name)
also where can i add sound when you eat and game over
i have search and ask all persons i know and ask persons on fiveer and no one knows
i'm stuck since 3 months and nothing 
help me please
will be very thankfull

**Comment by MastaCoder** [comment]
This is a lot of work by remaking the client.
