### ISSUE TITLE
How to add a minimap

### ISSUE THREAD

**Issue by J4awesome** [CigarProject/Cigar#98]
How do I add a minimap

**Comment by Kuchiriel** [comment]
Minimap is a client side script in javascript, you can rip from another works, and adjust the html, css and js.

**Comment by J4awesome** [comment]
Where would I put the html file

**Comment by iamashay** [comment]
You can take help of this client: http://www.mediafire.com/download/zf0yik27z16ryzn/agarweb-client-byChrisF.rar . It has a minimap.
