### ISSUE TITLE
Somebody help me

### ISSUE THREAD

**Issue by msofoke** [CigarProject/Cigar#99]
Could someone please help me create a full server, I have the agarplix.com just that the game modes are not edited and the rest

**Comment by J4awesome** [comment]
I could help you with the html or the servers if you want.

**Comment by matrixreal** [comment]
@J4awesome 
Hi,
do you have an idea about this problem
thanks you
i'm trying to find solution since 2 months and nothing
https://github.com/CigarProject/Cigar/issues/70
